// What each of the 64 gates actually means inside a specific area of life.
//
// The gate data itself (keynote, shadow, gift) is universal: gate 26 is gate 26 wherever it turns
// up. But a season pressing on gate 26 lands completely differently in love than it does in money,
// and reading the same universal keynote on every area page is what makes a feature feel generic.
// So each area gets its own lens over all 64 gates, and a season shows every gate it activates
// rather than only the handful that happen to sit in that area's centres.
//
// An area with no lens yet falls back to the universal keynote, so this can be rolled out one area
// at a time without any page breaking.

export const AREA_GATE_LENS: Record<string, Record<number, string>> = {
  career: {
    1: "Your original contribution, the thing only you would have made. Playing it safe here is the real risk this season.",
    2: "Direction. Knowing which way your work should go, before you can justify it on a spreadsheet.",
    3: "New ventures start badly. The difficult early phase is the shape of building something, not a verdict on it.",
    4: "Pressure to have the answer at work. Producing a confident one you have not tested is the trap.",
    5: "Consistency beats intensity. The unglamorous weekly rhythm is what actually compounds into a career.",
    6: "Friction with colleagues or clients. Handled well it produces an agreement, avoided it produces a slow leak.",
    7: "Leadership, and whether you are willing to be the one out front rather than the one enabling.",
    8: "Getting credit for your actual contribution. Being valued for what makes you different, not for fitting the mould.",
    9: "Focus. What you give sustained attention to this season is what will look like luck in a year.",
    10: "Behaving like yourself at work. The cost of a professional persona you have to maintain is higher than it looks.",
    11: "Ideas, plenty of them. Ideas are not the bottleneck, choosing one and staying with it is.",
    12: "Knowing when to speak and when the moment is wrong. Timing matters more than the content here.",
    13: "You are the one people confide in at work. Useful influence, and a role that can quietly consume your week.",
    14: "Resources and the material power to do the work properly. Funding, tools, time.",
    15: "Working at your own pace inside a system built for someone else's. The mismatch is the fatigue.",
    16: "Enthusiasm turning into skill. Repetition is what converts talent into a career.",
    17: "Your professional opinions. Strong views, and whether they are still being updated by evidence.",
    18: "Seeing what is broken. This is genuine quality control and it can become the thing people brace for.",
    19: "Sensitivity to what the team or client actually needs, often before they articulate it.",
    20: "Acting in the present rather than planning indefinitely. This season rewards doing the thing now.",
    21: "Control and autonomy. Who decides, who owns the budget, and whether you can work under someone else's authority.",
    22: "Grace under professional pressure. How you handle being challenged in public.",
    23: "Making the complicated idea simple enough to be bought, funded or understood.",
    24: "Returning to the same career question. The answer comes from trying it, not from another round of thinking.",
    25: "Doing the work for its own sake, not only for what it returns. This is what keeps a career survivable.",
    26: "Selling and persuading. Where confident positioning tips into overclaiming is the line this season.",
    27: "Looking after your team or clients, and whether that care is reciprocated or simply expected.",
    28: "Whether this work means anything. The struggle for purpose over security is live.",
    29: "Committing to a project properly. This is also where over-committing begins, so notice which one it is.",
    30: "Ambition and desire for a particular outcome. Powerful fuel, and it is not the same as strategy.",
    31: "Your voice and influence. Leading by being genuinely listened to rather than by title.",
    32: "Instinct about what will endure. You can usually tell which projects have a future, and it is worth trusting.",
    33: "Stepping back to review. Retreat is part of the work here, not a break from it.",
    34: "Raw capacity to do a lot. The power is real, and it is also how people end up doing three jobs for one salary.",
    35: "Hunger for the next thing. Genuine growth signal, and also how half-finished projects accumulate.",
    36: "Professional turbulence. A rough patch is often the career maturing rather than failing.",
    37: "Agreements and partnerships at work. Loyalty, contracts, and whether the deal is actually fair.",
    38: "Fighting for the work you believe in. Worth checking the fight is chosen rather than reflexive.",
    39: "Provoking a reaction to find out where you really stand with someone.",
    40: "Knowing when to stop. This gate is the boundary between working hard and working yourself into the ground.",
    41: "Imagining what is next. The fantasy stage is legitimate, and it is not yet a plan.",
    42: "Finishing. Closing a project properly rather than letting it drift is the whole assignment.",
    43: "A breakthrough you cannot yet explain to anyone. Being early is lonely and often correct.",
    44: "Reading people and patterns. Who to work with, based on evidence you have collected before.",
    45: "Money, resources and who distributes them. This season makes the commercial reality explicit.",
    46: "Being in the right place at the right time. Showing up physically matters more than it should.",
    47: "Making sense of a confusing professional stretch. Clarity comes after, not during.",
    48: "Imposter feelings, and the actual depth sitting underneath them.",
    49: "Your principles about how you will be treated professionally, and whether you would walk.",
    50: "Responsibility for other people's work and standards. What you have taken on, and whether it is yours.",
    51: "Shock. Something disrupts the plan, and initiative matters more than composure.",
    52: "Concentration under pressure. Not reacting immediately is what produces the good decision.",
    53: "Starting something new. The pressure to begin can outrun whether you actually want this project.",
    54: "Ambition and the climb. Real drive, and the trap of measuring yourself only by the next rung.",
    55: "Your professional mood swings. A flat week is a wave, not a verdict on your career.",
    56: "Storytelling. How you frame the work is a large part of whether it lands.",
    57: "Intuition about a work decision, arriving instantly and quietly. Easy to talk yourself out of.",
    58: "Energy to improve things. Genuine vitality, and the version where nothing is ever good enough to ship.",
    59: "Getting properly close in a working relationship, past the professional surface.",
    60: "Constraints. Working with the actual budget, time and capacity rather than the ideal one.",
    61: "Pressure to understand why the work is not landing. Some of it is not knowable yet.",
    62: "Details and precision. Naming things accurately, and where thoroughness becomes a stall.",
    63: "Doubt about the plan. Healthy scrutiny until it becomes a loop that prevents shipping.",
    64: "Mental replay of past professional experience. Confusion is processing, and clarity arrives on its own schedule.",
  },
  "health-body": {
    1: "Creative energy wants an outlet through your body. Unexpressed, it tends to sit in you as restlessness rather than leaving as rest.",
    2: "Your body knows which direction to go before your head does. Appetite, energy and aversion are the data this season.",
    3: "Starting something physical is deliberately uncomfortable at the beginning. The messy first fortnight is the shape of a new habit, not evidence it is wrong.",
    4: "Mental pressure to solve a health question. The answer usually needs a test and time rather than more reading.",
    5: "Rhythm. Eating, sleeping and moving at consistent times does more for you this season than any intense push.",
    6: "Emotional friction lands physically, in your gut and your chest. Conflict you have not processed shows up as a body symptom.",
    7: "The pace you set for others is often the pace that quietly wrecks you. Leading has an energetic cost worth counting.",
    8: "Your body is part of how you show up, not the packaging around it. Dressing and moving as yourself is a health matter here.",
    9: "Sustained focus, and what it costs. Small consistent attention to one physical thing beats a scattered overhaul.",
    10: "How you treat your body when nobody is watching. Self-love here is behavioural rather than a feeling.",
    11: "Ideas about health, most of them absorbed from somewhere else. Worth separating what you believe from what you have actually tested.",
    12: "Holding words in has a physical cost. What you do not say tends to settle in the throat, jaw and shoulders.",
    13: "You carry other people's stories, and that is real weight. Discharging it matters as much as anything you eat.",
    14: "Resources and energy. Whether you have the practical support to actually rest, rather than just the intention to.",
    15: "Your natural rhythm is not the standard one, and forcing it into someone else's schedule is where the depletion starts.",
    16: "Enthusiasm for a new physical practice. Repetition, not the initial excitement, is what turns it into capacity.",
    17: "Opinions about how your body should look or perform. Strongly held ones are worth examining this season.",
    18: "You notice what is wrong in the body early. That is genuine diagnostic instinct, and it can also become health anxiety.",
    19: "Sensitivity, including to food, environment and other people's states. Your needs are physical needs, not preferences.",
    20: "Being in your body in the present moment, rather than living a few feet above it in your head.",
    21: "Control over your own schedule. Health here is largely a question of who owns your time.",
    22: "Emotional openness has a physical release attached. Letting yourself be moved is nervous system work.",
    23: "Explaining what you are feeling physically, simply enough that someone can actually help.",
    24: "The mind loops on a body worry. Repetition is the mind processing, and it is not new information.",
    25: "Accepting your body as it is now, which is different from giving up on it.",
    26: "Pushing past what you have got. Willpower is real, and it runs down, and it does not refill by being told to.",
    27: "Nourishment. Whether you are actually feeding yourself, or feeding everyone else and eating the leftovers.",
    28: "The struggle for meaning can be exhausting. Ask whether the tiredness is physical or existential before treating it as either.",
    29: "Saying yes to a commitment your body has to carry. This is where over-committing physically starts.",
    30: "Desire and appetite. Wanting intensely is energising and it burns fuel, so notice which one is happening.",
    31: "Your voice and your throat. Speaking up, and the physical tension when you do not.",
    32: "Instinct about what will last. Your body usually knows which habits will survive and which are performance.",
    33: "Retreat. Genuine recovery needs actual withdrawal, not a lighter version of the same week.",
    34: "Pure sacral power. This is the gate most likely to make you work past a stop signal, because the power is genuinely there right up until it is not.",
    35: "Hunger for new experience. Novelty is energising and it is also how routines quietly collapse.",
    36: "Emotional turbulence with a physical tail. Crisis is metabolically expensive, so expect it to cost you sleep.",
    37: "The body relaxes around people it trusts. Who you are physically around matters more than it sounds.",
    38: "Fighting. Worth checking whether the tension you are carrying is protecting something or just habitual bracing.",
    39: "Provocation and the startle response. Your nervous system is easily set off this season, which is information rather than weakness.",
    40: "Recovery. This gate is the one that says the rest is not optional and the exhaustion is the invoice.",
    41: "The pressure of anticipation. Imagining what is coming has the same physical cost as living it.",
    42: "Completion. Finishing a cycle properly, and the specific fatigue of leaving several half-open.",
    43: "Knowing something about your body you cannot yet justify. Trust it before you can explain it.",
    44: "Pattern recognition about your own health history. What has happened before is genuinely predictive here.",
    45: "Resources and whether you have enough to look after yourself properly, rather than only enough to keep going.",
    46: "The gate of the body itself. Being in it, enjoying it, moving it for delight rather than for correction.",
    47: "Making sense of a confusing physical stretch. Meaning arrives after the experience, not during it.",
    48: "Fear of not being enough, which shows up physically as never resting because resting feels like falling behind.",
    49: "Your principles about how you treat your body, and where the actual line is.",
    50: "What you carry for your people, including inherited health patterns and inherited habits.",
    51: "Shock to the system. Something disrupts and the body registers it first.",
    52: "Stillness. Sitting with the pressure rather than discharging it immediately is the practice here.",
    53: "Beginning something new physically. The pressure to start is easy, sustaining it is the actual work.",
    54: "Ambition versus recovery. This is the pairing that produces burnout in high-functioning people.",
    55: "Mood and energy move together. A low day is often a wave rather than a diagnosis.",
    56: "The story you tell about your body shapes what you notice in it. Worth checking who wrote that story.",
    57: "Intuitive body clarity, the quiet immediate hit about what is right for you. Easy to override with logic and expensive to ignore.",
    58: "Vitality and the urge to improve. Genuine energy for it, and the trap of never being satisfied with the body you have.",
    59: "Intimacy and physical closeness, and how your body responds to being properly let in.",
    60: "Limitation. Working with your actual current capacity rather than the one you had five years ago.",
    61: "The pressure to know why you feel like this. Some of it will not be knowable, and chasing it costs sleep.",
    62: "Details. Tracking, measuring and naming things precisely, which either helps or becomes its own stress.",
    63: "Doubt about your own health. Useful when it prompts a test, corrosive when it just loops.",
    64: "Mental replay at night. This gate is often behind the wide-awake-at-3am pattern, and it is digestion rather than crisis.",
  },
  relationships: {
    1: "Your own creative self-expression becomes the thing that attracts, or the thing you keep editing down to be easier to love.",
    2: "You get a clearer sense of the direction you want a relationship to go, rather than drifting wherever the other person steers.",
    3: "New beginnings in love feel messy before they feel exciting. The awkward early stage is not a bad sign here, it is the actual shape of starting.",
    4: "You want an answer about where this is going, and the mind will happily invent one. The pressure is mental, the answer is not.",
    5: "Rhythm matters more than intensity. Whether someone fits your natural pace is the real compatibility question this season.",
    6: "The intimacy gate. Your capacity to let someone close opens and shuts in waves, and conflict here is not failure, it is the doorway being tested.",
    7: "Who leads, and whether you are willing to be led. Direction inside a partnership becomes the live question.",
    8: "Being valued for what makes you different, rather than for how well you fit in. Bringing your actual self is the assignment.",
    9: "Attention to the small details of a relationship. What you focus on here compounds, in both directions.",
    10: "Self-love as the precondition. How you treat yourself sets the ceiling on what you will accept from someone else.",
    11: "Ideas about love, the ones you have absorbed and the ones you actually believe. Worth checking which is which.",
    12: "Whether you say the emotionally true thing or the socially smooth thing. Caution here can be wisdom or avoidance.",
    13: "You become the one people tell things to. Holding someone's story is intimacy, and it can also become a role you disappear into.",
    14: "What you bring materially and practically to a partnership, and whether that has quietly become how you earn your place.",
    15: "Your tolerance for other people's rhythms. Love asks you to stretch around difference without dissolving into it.",
    16: "Enthusiasm for someone, and whether you can stay past the exciting first phase into actual skill at loving them.",
    17: "Your opinions about how a relationship should go. Strong views here can be clarity or they can be a fence.",
    18: "You notice what is wrong. Used well that protects the relationship, used badly it becomes a running critique nobody asked for.",
    19: "Sensitivity to what your person needs, sometimes before they say it. The line between attunement and losing yourself is thin this season.",
    20: "Being present with someone rather than managing the impression. What you actually feel, in the moment, said out loud.",
    21: "Control. Who decides, who holds the resources, and whether you can share authority without feeling erased.",
    22: "Emotional grace under social pressure. How openly you let yourself be moved in front of someone else.",
    23: "Saying the complicated inner thing simply enough to be understood. Being misheard here is usually about timing rather than content.",
    24: "The returning mind. You keep going back over the same relationship question, and the answer arrives by living rather than by thinking.",
    25: "Loving without conditions attached, including loving yourself through the part where it is not being returned.",
    26: "Persuasion. How much you shape yourself to convince someone, and where that tips from charm into performance.",
    27: "Caring for someone. This season asks whether the care is mutual, or whether you have quietly become the one who does the nourishing.",
    28: "Whether this relationship means something. The struggle for depth over comfort shows up hard here.",
    29: "Commitment. Saying yes properly, and noticing where you have been half-in and calling it keeping your options open.",
    30: "Desire and longing. Wanting someone intensely is information, but it is not the same thing as clarity about them.",
    31: "Your voice inside the relationship. Whether you influence by being heard or by being loud.",
    32: "Instinct about what will last. You can usually tell early, and this season asks you to trust that read rather than argue with it.",
    33: "Retreat. Needing space to process is legitimate, and using it to avoid the conversation is not the same thing.",
    34: "Raw energy and independence. Your power is attractive, and it can also be the reason you do not let anyone actually in.",
    35: "Hunger for something new. Restlessness in love is real information, though not always about the other person.",
    36: "Emotional crisis as a growth route. Turbulence now is often the relationship maturing rather than ending.",
    37: "The bond itself. Friendship, family, the agreements you have made. Loyalty gets examined, and so does whether it is equal.",
    38: "Fighting for it. Worth checking whether you are fighting for the relationship or just fighting because that is familiar.",
    39: "Provocation. You poke at the thing to get a real reaction, which either produces honesty or a fight, depending on the timing.",
    40: "Needing to be alone, inside a relationship. Denying that need is what produces the exhaustion, not the relationship itself.",
    41: "The fantasy of a relationship, versus the one in front of you. Imagination is the start of desire, and it is not evidence.",
    42: "Endings and completions. Finishing something properly rather than letting it trail off is the work here.",
    43: "You know something about this relationship that you cannot yet explain. Being ahead of your own words is uncomfortable and usually correct.",
    44: "Instinct about people, often about patterns you have met before. Your past is pattern-matching, and it is sometimes right.",
    45: "Sharing resources, and who holds them. This season makes the practical side of togetherness explicit rather than assumed.",
    46: "Being in your body with someone. Physical presence, touch and the delight of the ordinary.",
    47: "Making sense of what happened. You are processing a relationship experience into meaning, and it will feel confused before it lands.",
    48: "Fear of not being enough for someone, and the depth you actually have underneath that fear.",
    49: "Your principles about how you will be treated. Where the line is, and whether you are willing to end something over it.",
    50: "Responsibility to the people who are yours. What you owe, what you have inherited, and which of it is genuinely yours to carry.",
    51: "Shock. Something disrupts the relationship and forces initiative, and courage matters more than composure here.",
    52: "Stillness under pressure. Not acting on the relationship feeling immediately is what gives it room to become clear.",
    53: "Beginning something. New energy arrives, and the pressure to start can outrun whether you actually want this one.",
    54: "Ambition inside a relationship, including the uncomfortable question of whether being with someone raises or lowers you.",
    55: "The emotional weather. Your mood swings between abundance and emptiness, and neither one is the truth about the relationship.",
    56: "Stories. The story you tell about your love life shapes what you notice next, and it is worth checking who wrote it.",
    57: "Intuitive clarity in the present moment. The quiet first hit about someone, which is usually accurate and easy to argue away.",
    58: "Vitality and the urge to improve things. Wanting better for a relationship is love, and constant correction is not.",
    59: "Intimacy and sexuality directly. Breaking through the barrier to actual closeness, and the honesty that requires.",
    60: "Limitation. Accepting the real constraints of a relationship rather than the version you wish it were.",
    61: "The pressure to understand why someone is the way they are. Some of it is not knowable, and sitting with that is the practice.",
    62: "The details. Naming things precisely, which either creates real understanding or turns into pedantry mid-argument.",
    63: "Doubt. Questioning the relationship is healthy inquiry until it becomes a loop, and the difference is whether it produces action.",
    64: "Mental replay of past relationships. Confusion now is the mind digesting something, and clarity arrives on its own schedule.",
  },
};

/** The area-specific reading for a gate, falling back to the universal keynote. */
export function gateLensFor(areaId: string, gate: number, fallback: string): string {
  return AREA_GATE_LENS[areaId]?.[gate] ?? fallback;
}
