// What each of the 64 gates actually means inside a specific area of life.
//
// The gate data itself (keynote, shadow, gift) is universal: gate 26 is gate 26 wherever it turns
// up. But a season pressing on gate 26 lands completely differently in love than it does in money,
// and reading the same universal keynote on every area page is what makes a feature feel generic.
// So each area gets its own lens over all 64 gates, and a season shows every gate it activates
// rather than only the handful that happen to sit in that area's centres.
//
// An area with no lens yet falls back to the universal keynote, so this can be rolled out one area
// at a time without any page breaking.

export const AREA_GATE_LENS: Record<string, Record<number, string>> = {
  "home-environment": {
    1: "Your space as an expression of you rather than a set someone else would approve of.",
    2: "Knowing where you're meant to be. Place has a pull, and it's worth taking seriously.",
    3: "A move or a change at home is chaotic before it settles. The mess is the transition.",
    4: "Wanting certainty about where to live. The answer is felt on arrival rather than reasoned in advance.",
    5: "Your daily rhythm at home. The routine of a place matters more than its square footage.",
    6: "Friction with the people you share space with. Proximity makes everything visible.",
    7: "Your role in the household, and whether it's one you chose.",
    8: "Letting your space show who you actually are, not the tidied version for visitors.",
    9: "One corner done properly beats a whole house half-sorted.",
    10: "How you treat the space you live in reflects how you treat yourself. This one is a direct mirror.",
    11: "Ideas about how a home should look, most of them absorbed from somewhere else.",
    12: "Whether you can be quiet at home in the way you actually need, or whether you're always available.",
    13: "Your home as the place people come to be heard. A real gift, and it needs a door that closes.",
    14: "The resources to make your space work for you rather than merely function.",
    15: "Your natural rhythm at home, which may look nothing like a normal household schedule.",
    16: "Enthusiasm for changing something. Start it before the plan is complete.",
    17: "Fixed opinions about how the space should be. Worth checking they're still yours.",
    18: "Noticing everything that needs fixing. Useful, and it can stop you ever resting in the room.",
    19: "Sensitivity to your surroundings. Noise, light and clutter aren't preferences for you, they're inputs.",
    20: "Being present in your space rather than treating it as somewhere you pass through.",
    21: "Control over your own territory. Having somewhere that's genuinely yours to decide about.",
    22: "The warmth of a room, and whether yours invites people in or keeps them at the door.",
    23: "Saying plainly what you need from a shared space instead of hoping it's noticed.",
    24: "Returning to the same thought about moving. Repetition is processing, not yet a decision.",
    25: "Accepting your home as it's now while still wanting more for it.",
    26: "The performance version of your home, staged for how it looks rather than how it lives.",
    27: "Your home as somewhere you're nourished, not only somewhere you nourish everyone else.",
    28: "Whether where you live actually means something to you, or is simply where you ended up.",
    29: "Committing to a place. Saying yes properly rather than staying provisional for years.",
    30: "Longing for somewhere else. Real information, and not always about the location.",
    31: "Your voice in the household. Who sets the tone of the space.",
    32: "Instinct about whether a place will work long term. Usually accurate on arrival.",
    33: "Retreat. Having somewhere to withdraw to is a requirement rather than a luxury.",
    34: "Energy at home, and whether your space lets you move or asks you to sit still.",
    35: "Restlessness with your surroundings. The urge for somewhere new is worth examining before acting on.",
    36: "Turbulence at home. Upheaval now is often the foundations being rebuilt rather than broken.",
    37: "Family and household bonds, and the agreements underneath them.",
    38: "Fighting for your own space, including the right to close a door.",
    39: "Provoking a change at home to break a stuck atmosphere.",
    40: "Home as recovery. If your space doesn't restore you, nothing else in your week will.",
    41: "Imagining the home you want. Fantasy is the beginning of a move, and not yet one.",
    42: "Finishing the project you started in the house. Half-done rooms sit in the background of your mind.",
    43: "Knowing a place is right before you can justify it. Trust the arrival feeling.",
    44: "Recognising the atmosphere of somewhere from experience. Your instinct about a place has history behind it.",
    45: "Shared resources in a household, and who actually decides how they're used.",
    46: "Being physically at ease where you live. This is the gate of the body, so comfort isn't superficial.",
    47: "Making sense of an unsettled period at home. Meaning arrives once it stops moving.",
    48: "Feeling your space isn't good enough. The inadequacy is usually louder than the reality.",
    49: "Your principles about how your home is treated, and where the line is.",
    50: "Inherited patterns about home and family, and which of them you're keeping.",
    51: "A shock at home. Something disrupts, and it often reorganises more than the room.",
    52: "Stillness. Sitting in your space rather than immediately improving it.",
    53: "Starting something new at home. The pressure to begin, before you know the shape of it.",
    54: "Ambition for a better home, and the trap of never arriving somewhere that feels like enough.",
    55: "Your mood colours how your home feels. A flat week makes any room feel wrong.",
    56: "The story your space tells about you, and whether it's still the story you want.",
    57: "Instinctive read on a room. The quiet immediate sense of whether somewhere is right for you.",
    58: "Energy to improve your surroundings, and the version where nothing is ever finished.",
    59: "Intimacy at home. Who you let all the way in, physically and otherwise.",
    60: "Working with the space you actually have rather than the one you wish you had.",
    61: "Wanting to understand why a place unsettles you. Not all of it will be explainable.",
    62: "The details of a room. Precision that makes it work, and precision that becomes fussing.",
    63: "Doubting a decision about where to live. Scrutiny while it moves you, a loop when it doesn't.",
    64: "Replaying old homes and what they felt like. The mind digesting rather than deciding.",
  },
  "spiritual-growth": {
    1: "Creation as a spiritual act. Making something is a form of practice, not a distraction from it.",
    2: "Receptivity. Being led rather than deciding, which is uncomfortable if you're used to steering.",
    3: "New growth begins in disorder. The chaotic phase is part of the process rather than a sign you have lost the thread.",
    4: "The pressure to have a spiritual answer. Formulating one prematurely is how dogma starts.",
    5: "Practice through rhythm. Daily and unglamorous beats intense and occasional.",
    6: "Intimacy as the practice. Your growth happens in relationship rather than in isolation.",
    7: "Guiding others, and whether you're ready to be looked to.",
    8: "Your contribution as your practice. Expressing what is genuinely yours is the spiritual work.",
    9: "Devotion to one thing. Depth over collecting practices.",
    10: "Self-love as the foundation. Everything spiritual built on self-rejection eventually collapses.",
    11: "Ideas and inspiration flowing through. Holding them lightly rather than turning them into a doctrine.",
    12: "Knowing when to speak about your inner life and when it's not for sharing.",
    13: "Holding what others confide. Witnessing is genuinely a spiritual role.",
    14: "Resources in service of something larger than your own comfort.",
    15: "Acceptance of human variety, including the parts of people you find difficult.",
    16: "Enthusiasm as devotion. What you're drawn to practise badly is worth following.",
    17: "Opinions about the right way to grow. The most spiritual move here is holding them loosely.",
    18: "Seeing what is distorted, in a teaching or a community. Discernment rather than cynicism.",
    19: "Sensitivity to others, and the boundary between compassion and absorbing what isn't yours.",
    20: "Presence. This is the whole practice compressed into one gate: being here, now, as yourself.",
    21: "Surrendering control. This gate makes that genuinely difficult, which is exactly why it's the work.",
    22: "Grace. Being open to being moved, rather than managing yourself in front of others.",
    23: "Putting the ineffable into plain words so someone else can use it.",
    24: "The returning mind. Contemplation and rumination look identical from inside, and the difference is whether it moves you.",
    25: "Universal love. This is the closest thing to a spiritual gate in the system, innocence after experience.",
    26: "Where you dress up your growth for an audience. The gap between practice and performance.",
    27: "Compassion in action. Caring as practice, with boundaries so it survives.",
    28: "The dark night gate. Wrestling with meaning, which isn't a failure of faith but the substance of it.",
    29: "Saying yes and staying with it. Commitment through the unglamorous middle.",
    30: "Desire, including spiritual desire. Wanting enlightenment is still wanting.",
    31: "Leading others in this. Influence carries responsibility for what you transmit.",
    32: "Knowing what will endure. Which practices survive contact with a hard year.",
    33: "Retreat. Solitude as an actual requirement rather than a luxury.",
    34: "Power without display. Strength that doesn't need to be witnessed to be real.",
    35: "Experience as the teacher. You learn this by doing it rather than by reading about it.",
    36: "Crisis as initiation. The hardest passages are usually where the actual growth happened.",
    37: "Belonging to a community of practice, and what you compromise to stay in one.",
    38: "Fighting for meaning. Stubbornness in service of something worth it.",
    39: "Provocation that wakes people up, including yourself.",
    40: "Knowing when to withdraw and restore. Depletion isn't devotion.",
    41: "The pressure to begin a new inner chapter, arriving first as imagination.",
    42: "Completing a cycle so the next can start. Endings are part of the practice.",
    43: "Inner knowing that arrives whole. Trusting it before you can justify it.",
    44: "Recognising a pattern from before. Old material resurfacing to be finished properly.",
    45: "Stewardship of what you have been given, material and otherwise.",
    46: "Embodiment. The body as the site of practice rather than the obstacle to it.",
    47: "Transmutation. Turning confusion and difficulty into meaning, which is this gate's whole job.",
    48: "The fear of not being deep enough, sitting directly on top of genuine depth.",
    49: "Principles worth reorganising your life around.",
    50: "What you have inherited, spiritually and culturally, and which of it you're keeping.",
    51: "Shock as initiation. A jolt that opens something no gradual process would have.",
    52: "Stillness. Meditation in the most literal sense this system offers.",
    53: "Beginning a new practice. The pressure to start, before you know where it leads.",
    54: "Ambition applied inwardly, including the trap of spiritual achievement.",
    55: "Spirit and mood. Your inner weather moves in waves, and the low isn't a loss of faith.",
    56: "The stories and beliefs you transmit. Teaching as practice.",
    57: "Intuitive clarity in the present moment. The quiet knowing that doesn't repeat itself.",
    58: "Joy as a practice, and the drive to improve that can quietly poison it.",
    59: "Dissolving the barrier to genuine closeness, with people and with everything else.",
    60: "Accepting limitation. Transcendence through the constraint rather than around it.",
    61: "The mystery gate. Pressure to know the unknowable, which becomes inspiration or spiralling depending on how you hold it.",
    62: "Naming things precisely, and where precision stops being useful for the ineffable.",
    63: "Doubt. Healthy scepticism about your own beliefs, which is a spiritual practice in itself.",
    64: "Mental images that haven't resolved. Digestion, not confusion, and the meaning arrives later.",
  },
  healing: {
    1: "Expressing what happened to you, in your own form. Creation as processing.",
    2: "Trusting your own direction again after a period of being steered by someone else.",
    3: "Early healing is messy and non-linear. The disorder is the process, not a relapse.",
    4: "Wanting an explanation for the wound. Understanding helps and it doesn't, on its own, heal it.",
    5: "Recovery through rhythm. Regular and boring is what actually rebuilds a nervous system.",
    6: "Emotional friction reopening something. Conflict is where old wounds are most visible.",
    7: "The role you took on for others, often young, and whether you still have to play it.",
    8: "Being yourself without the adaptation you learned to survive.",
    9: "Small, sustained attention. Healing compounds rather than arriving.",
    10: "Self-love as the actual mechanism. This gate is the centre of gravity for healing work.",
    11: "The stories you carry about what happened. Reframing is real work, not denial.",
    12: "What you haven't said. Held words are held tension.",
    13: "Holding others' pain, including the part where you never put yours down.",
    14: "Having the practical resources to actually recover rather than only the intention.",
    15: "Accepting your own pace of healing rather than someone else's timeline for it.",
    16: "Enthusiasm returning. The first sign of recovery is usually interest, not energy.",
    17: "Fixed opinions formed at the time of the wound, which may no longer be accurate.",
    18: "The inner critic. This gate is often where the harshest internal voice lives.",
    19: "Needing people. Allowing that need is frequently the wound and the medicine at once.",
    20: "Being present rather than braced. Coming back into now.",
    21: "Control as a protective strategy. It worked once, and it costs you now.",
    22: "Letting yourself be moved in front of someone, which is often exactly what was unsafe before.",
    23: "Saying the difficult thing simply enough to be understood.",
    24: "The looping mind returning to the same memory. Repetition is processing until it stops moving you.",
    25: "Innocence after experience. Not becoming hard, which is the real work.",
    26: "The performance of being fine. Where you have been managing an impression instead of recovering.",
    27: "Being cared for rather than only caring. Receiving is often harder than giving here.",
    28: "Making the difficulty mean something. The search for purpose inside the pain.",
    29: "Committing to the process rather than being half-in and calling it protecting yourself.",
    30: "Longing. Desire for what was lost, and letting yourself feel it rather than manage it.",
    31: "Finding your voice about it, and the influence that comes from having survived something.",
    32: "Instinct about what will last. Which of your coping strategies deserve to be kept.",
    33: "Retreat and privacy. Genuine withdrawal to process rather than to hide.",
    34: "Power returning. Strength after depletion, which needs pacing not proving.",
    35: "New experience as evidence. Doing the thing safely once rewrites more than analysis does.",
    36: "Crisis. This gate is emotional turbulence as a growth route, and it's genuinely how some healing works.",
    37: "Bonds, family and the agreements made for you rather than by you.",
    38: "Fighting. Whether you're still braced against something that has already ended.",
    39: "Provocation and the startle response. Your nervous system reacting faster than the situation warrants.",
    40: "Exhaustion. The recovery gate, and the boundary that makes recovery possible.",
    41: "Anticipating harm before it arrives. Imagination working as protection and as cost.",
    42: "Finishing something properly so it stops running in the background.",
    43: "Knowing something about your own history you can't yet articulate.",
    44: "Pattern recognition. Recognising a dynamic from before, which is instinct and sometimes over-fitting.",
    45: "What you're owed and what was withheld, materially and otherwise.",
    46: "Coming back into your body. So much of this is physical rather than cognitive.",
    47: "Making meaning from what happened. This gate is the alchemy, and it works slowly.",
    48: "Feeling inadequate to your own life, and the depth underneath that feeling.",
    49: "The line. What you won't accept again, stated clearly.",
    50: "Inherited patterns. What came down the family line, and what you're choosing not to pass on.",
    51: "Shock. The event that reorganised you, and the initiative that comes out of it.",
    52: "Stillness with the discomfort rather than discharging it immediately.",
    53: "Beginning again. Starting a new chapter before the last one feels fully closed.",
    54: "Rising out of it, and the trap of using achievement to outrun the feeling.",
    55: "Emotional waves. A bad week is a wave rather than evidence you haven't healed.",
    56: "The story you tell about what happened, and how much of your identity is built on it.",
    57: "Intuitive knowing about your own safety. Quiet, immediate, and worth trusting.",
    58: "Vitality returning, and the version where you can never leave yourself alone to just be well.",
    59: "Letting someone properly in again after a breach of trust.",
    60: "Accepting what can't be changed, which is different from being resigned to it.",
    61: "Wanting to understand why it happened. Some of it won't resolve, and demanding it does prolongs it.",
    62: "Naming it precisely. Language is genuinely part of processing.",
    63: "Doubting your own account of it. Common, and rarely a reason to dismiss yourself.",
    64: "Replaying it. The mind digesting rather than torturing you, though it doesn't feel like it at 3am.",
  },
  confidence: {
    1: "Your own creative expression, and how much of it you dilute before anyone sees it.",
    2: "Trusting your own sense of direction without needing it validated first.",
    3: "Being bad at something new. Confidence is built in the awkward stage, not after it.",
    4: "Needing to have the answer before you feel allowed to speak. That standard is why you stay quiet.",
    5: "Confidence built through consistency. Showing up repeatedly is the evidence, not a single brave act.",
    6: "Handling conflict without collapsing or hardening. Your steadiness under friction is the confidence.",
    7: "Being willing to be the one out front, which is different from wanting attention.",
    8: "Being yourself in public and letting that be the offer. Editing yourself down is the confidence leak.",
    9: "Confidence from doing one thing properly rather than being adequate at many.",
    10: "The self-love gate, and the closest thing to a confidence gate there is. How you treat yourself sets the whole ceiling.",
    11: "Your ideas are worth sharing before they're perfect. Waiting for polish is where they die.",
    12: "Speaking when it matters. The gap between what you feel and what you say is where confidence lives or leaks.",
    13: "You hold what others tell you. Being trusted is real evidence of your worth, if you let it count.",
    14: "Confidence that comes from having your own resources rather than borrowed permission.",
    15: "Accepting that you're not standard. Your range is the point, not the flaw to correct.",
    16: "Enthusiasm before competence. Being visibly a beginner is the price of eventually being good.",
    17: "Having a view and stating it. The confidence risk is being wrong in public, which is survivable.",
    18: "Your critical eye turned inward. This gate is often the internal voice that undercuts you.",
    19: "Needing others, and whether you experience that as weakness rather than as human.",
    20: "Confidence in the present moment. Acting now rather than rehearsing a better version of yourself.",
    21: "Autonomy. Confidence here depends on controlling your own decisions rather than performing independence.",
    22: "Being emotionally open in front of people. Grace rather than composure.",
    23: "Being understood. Not being heard the first time is timing, not evidence you haven'thing to say.",
    24: "The looping mind returning to an old inadequacy. Repetition isn't new information.",
    25: "Loving yourself without conditions attached to performance.",
    26: "Selling yourself, and the exact point where confidence tips into a bit of a performance.",
    27: "Being valued for what you give, and what happens to your self-worth when you stop giving.",
    28: "Confidence tied to whether your life means something. The search itself isn't a failure.",
    29: "Saying yes to something bigger than you feel ready for. Readiness follows commitment here.",
    30: "Desire. Wanting something openly, without pre-apologising for wanting it.",
    31: "Your voice and whether people follow it. Leading rather than deferring.",
    32: "Fear of failing publicly. Your instinct for what will work is more reliable than the fear.",
    33: "Withdrawing to gather yourself. Retreat is legitimate, and isn't the same as hiding.",
    34: "Raw power and self-belief. This is genuine confidence energy, and it can bulldoze.",
    35: "Confidence from having done a lot of things, rather than from having done one thing perfectly.",
    36: "Coming through emotional turbulence. What you have survived is confidence you already own.",
    37: "Belonging. Being accepted by your people, and how much of yourself you trade for it.",
    38: "The fighter. Confidence through being willing to stand alone on something.",
    39: "Provoking a reaction to find out where you stand, because ambiguity is unbearable.",
    40: "Knowing your own limit and saying no. Boundaries are confidence made practical.",
    41: "Imagining a bolder version of yourself. Fantasy is the start, and it's not yet action.",
    42: "Seeing something through. Finishing builds more self-trust than starting ever will.",
    43: "Trusting an insight nobody else has yet. Being alone with a knowing takes nerve.",
    44: "Confidence from pattern recognition. You have done harder things before, and you can recall the evidence.",
    45: "Owning your authority over what is yours, including money and resources.",
    46: "Being at home in your body. Physical self-acceptance directly drives visible confidence.",
    47: "Making sense of a confusing period. Confidence returns once meaning does, not before.",
    48: "The inadequacy gate. The feeling of not being ready sits directly on top of real depth.",
    49: "Knowing your line and holding it, even when holding it costs something.",
    50: "Responsibility for others, and whether your worth has become conditional on carrying it.",
    51: "Shock. Something knocks you, and initiative is what rebuilds you rather than reassurance.",
    52: "Sitting still with discomfort instead of discharging it. That capacity is quiet confidence.",
    53: "Starting something new. The nerve is in beginning before you're qualified.",
    54: "Ambition to rise, and the trap of confidence that depends on the next achievement.",
    55: "Your self-belief moves in waves. A low day is a wave, not the truth about you.",
    56: "The story you tell about yourself. Worth noticing who wrote it and whether it's still accurate.",
    57: "Trusting your immediate quiet instinct. Overriding it repeatedly is how self-trust erodes.",
    58: "The drive to improve, and the version where you're never allowed to be satisfied.",
    59: "Being genuinely seen up close, past the presentable version.",
    60: "Accepting your actual constraints, and finding confidence inside them rather than after them.",
    61: "The pressure to understand yourself completely before acting. That understanding isn't coming first.",
    62: "Getting the words exactly right. Precision helps, and it can become a reason never to speak.",
    63: "Self-doubt. Useful when it sharpens the work, corrosive when it just runs.",
    64: "Replaying old embarrassments. The mind is digesting, and it's not delivering a verdict.",
  },
  mindset: {
    1: "Original thinking rather than a better-argued version of what everyone already believes.",
    2: "Knowing which way to go without a logical case for it yet. Not everything worth doing is arguable.",
    3: "New thinking is disordered at first. Confusion at the start is the shape of an idea forming.",
    4: "The pressure to find an answer, which is what this gate actually is. It's pressure, not certainty.",
    5: "Mental steadiness through routine. Your thinking is clearer when your days are.",
    6: "Emotional friction clouding your judgement. Don't decide anything important mid-wave.",
    7: "Thinking about direction for a group. Strategy rather than analysis.",
    8: "Expressing an idea in a way that's unmistakably yours rather than the accepted framing.",
    9: "Concentration. Depth on one problem rather than shallow passes across five.",
    10: "How you talk to yourself in your own head. That voice sets the tone of everything else.",
    11: "A wealth of ideas. Having them isn't the problem, choosing between them is.",
    12: "Knowing when to articulate a thought and when it's not ready to survive contact with air.",
    13: "Gathering other people's perspectives into your own thinking.",
    14: "Practical thinking about resources. What the idea would actually take.",
    15: "Mental flexibility across extremes. Holding two contradictory things without forcing a resolution.",
    16: "Enthusiasm for learning something. The willingness to be a beginner mentally.",
    17: "Opinions. This gate is literally opinion formation, and the trap is mistaking one for a fact.",
    18: "The critical mind. Genuinely useful for spotting flaws, exhausting when aimed at yourself.",
    19: "Attunement to what others need, which colours your thinking more than you notice.",
    20: "Present-moment awareness. Thinking that leads to acting now rather than to more planning.",
    21: "Wanting mental control over an outcome that's not actually yours to control.",
    22: "Emotional grace in how you express a difficult thought.",
    23: "Making the complex simple. This is the translation gate, and being misunderstood is usually timing.",
    24: "The returning mind. This is the rumination gate: the same thought, revisited, until it eventually yields something.",
    25: "Thinking without needing to win. Openness rather than defence.",
    26: "How you frame things to persuade, and where framing becomes self-deception.",
    27: "Thinking about how to care for others, and whether you have included yourself.",
    28: "Wrestling with whether any of it matters. This is philosophy, not depression, though they feel similar.",
    29: "Mental commitment. Deciding to properly engage with something rather than dabbling.",
    30: "Desire distorting judgement. Wanting an outcome makes the evidence look better than it is.",
    31: "Thinking out loud in a way that influences others. Leadership through articulation.",
    32: "Instinct for what will work. Often faster and more accurate than the analysis you do afterwards.",
    33: "Reflection. Reviewing what happened is where the actual learning is stored.",
    34: "Power without a mental brief. Energy that acts before thinking, which is sometimes exactly right.",
    35: "Hunger for new mental experience. Learning through doing rather than through study.",
    36: "Mental turbulence during an emotional crisis. Your thinking isn't reliable right now, and that's temporary.",
    37: "Thinking in terms of the group and the agreement rather than the individual.",
    38: "Mental stubbornness. Useful for holding a position under pressure, costly when the position is wrong.",
    39: "Provoking a reaction to shake loose a real answer.",
    40: "Mental exhaustion. Recognising when the thinking has run out rather than pushing through it.",
    41: "Imagination and fantasy. The starting pressure of every new idea, and not yet a plan.",
    42: "Finishing a line of thinking rather than abandoning it near the end.",
    43: "Breakthrough insight arriving whole, without a chain of reasoning behind it. Hard to explain and often right.",
    44: "Recall of patterns. Your instinct about how this will go is built on real past data.",
    45: "Thinking about how resources are shared. Strategic rather than abstract.",
    46: "Thinking with your body involved. Movement genuinely changes your cognition here.",
    47: "Making meaning from confusion. This gate is the mental digestion process, and it's uncomfortable by design.",
    48: "Fear of not knowing enough, sitting on top of considerable depth.",
    49: "Principles as thinking. Where the line is, and what would make you change your mind.",
    50: "Thinking about responsibility and standards, including inherited ones.",
    51: "A shock that reorganises how you think about something.",
    52: "Mental stillness under pressure. Not answering immediately is the discipline.",
    53: "The pressure to start a new line of thinking before finishing the last one.",
    54: "Ambitious thinking. Aiming higher, and the anxiety attached to it.",
    55: "Mood colouring thought. The same situation reads completely differently at either end of the wave.",
    56: "Storytelling and belief. How you narrate something determines what you conclude about it.",
    57: "Instant intuitive clarity, quieter and quicker than reasoning, and easily talked over.",
    58: "The urge to improve and correct. Genuine vitality, and the trap of relentless dissatisfaction.",
    59: "Thinking honestly about intimacy, past the polite version.",
    60: "Accepting limits. Realistic thinking rather than pessimism, though they can feel identical.",
    61: "The mystery gate. Pressure to know the unknowable, which becomes either inspiration or spiralling.",
    62: "Detail and precision in language. Naming things accurately, and the risk of missing the point while getting the words right.",
    63: "Doubt. The logical scepticism gate, useful as inquiry and corrosive as a loop.",
    64: "Mental confusion as processing. Images and fragments that haven't resolved yet, and pushing for the answer delays it.",
  },
  money: {
    1: "Your originality is the asset. What you would make anyway is usually the thing worth charging properly for.",
    2: "Direction with money. Knowing what you actually want it for, before optimising how to get more of it.",
    3: "New income takes a messy while to work. The unprofitable start is the shape of building, not a verdict.",
    4: "Wanting a definite answer about money that nobody can honestly give you yet.",
    5: "Consistency. Regular, unexciting financial habits outperform the occasional dramatic push.",
    6: "Friction in negotiation. The uncomfortable conversation about numbers is the one that changes them.",
    7: "Whether you lead on money decisions or defer, and what deferring has cost you so far.",
    8: "Being paid for what makes you different rather than for delivering the standard version.",
    9: "Focus. One income stream given proper attention beats four half-built ones.",
    10: "How you handle money when nobody is watching. The private habits are the actual financial position.",
    11: "Ideas about money absorbed from family and culture. Worth separating inherited beliefs from tested ones.",
    12: "Knowing when to name your price and when to wait. Timing beats wording.",
    13: "You hold other people's financial confidences. Useful trust, and occasionally a weight.",
    14: "Direct material power. Resources arriving, and whether you're using them or guarding them.",
    15: "Your own financial rhythm, which may not look like anyone else's. Irregular isn't the same as unstable.",
    16: "Enthusiasm for a money idea. Skill and repetition, not the excitement, is what makes it pay.",
    17: "Opinions about what things should cost, including your own work. Worth testing against the market.",
    18: "Spotting what is wrong with a deal. Genuine protection, and it can become an inability to ever commit.",
    19: "Sensitivity to needing support, and how uncomfortable asking for it is.",
    20: "Acting on the financial thing now rather than planning it for another quarter.",
    21: "Control over your own resources. This is the central money gate: who actually decides how yours is spent.",
    22: "Grace around money conversations. Being able to talk about it without shrinking or bristling.",
    23: "Explaining your value simply enough that someone can say yes to it.",
    24: "Returning to the same money worry. Repetition is processing, not new information.",
    25: "Worth that's not conditional on output. Your value isn't the invoice total.",
    26: "Selling and positioning. Confident framing versus overclaiming is the exact line this season.",
    27: "Where your money goes to look after other people, and whether that's generosity or an obligation you never agreed to.",
    28: "Financial risk in service of meaning. Worth it sometimes, and worth naming as a risk.",
    29: "Committing to a financial obligation. Say yes properly or not at all, because half-in is the expensive version.",
    30: "Desire for something specific. Strong motivation, and it distorts judgement about price.",
    31: "Your voice in a negotiation. Influence through being heard rather than through volume.",
    32: "Instinct for what will actually be profitable and last. Usually accurate, often argued with.",
    33: "Stepping back to review the numbers properly rather than reacting to them.",
    34: "The raw capacity to work. Real earning power, and the route to earning by depletion if unwatched.",
    35: "Hunger for the next opportunity. Genuine growth, and how money leaks into unfinished ventures.",
    36: "Financial turbulence. Uncomfortable, and frequently the thing that forces an overdue change.",
    37: "Agreements about money with people you're close to. Loyalty and contracts, and whether they're fair.",
    38: "Fighting for what you're worth. Choose the fight rather than defaulting to it.",
    39: "Provoking a response on price to find out where you actually stand.",
    40: "The point where earning more costs more than it returns. Knowing your limit is a financial skill.",
    41: "Imagining the money before it exists. Anticipation is fuel and it's not yet income.",
    42: "Completion. Finishing and invoicing, rather than leaving several things almost done.",
    43: "Knowing a money decision is right before you can justify it on a spreadsheet.",
    44: "Reading which opportunities and people are financially sound, based on patterns you have met before.",
    45: "The direct money gate: gathering resources and deciding how they're shared out.",
    46: "Being in the right room. Financial serendipity depends on showing up more than it admits.",
    47: "Making sense of a confusing financial stretch. The lesson lands after, not during.",
    48: "Fear of not being good enough to charge more, and the actual depth that says otherwise.",
    49: "Your principles about money. What you won't do for it, and where the line genuinely is.",
    50: "Financial responsibility for other people, chosen and inherited.",
    51: "A financial shock. Initiative matters more than composure here.",
    52: "Not acting on the money impulse immediately. Restraint is the whole practice.",
    53: "Starting a new income stream. Beginning is easy, and sustaining it's the actual work.",
    54: "Ambition and the climb. Real drive, and the trap of never arriving anywhere that feels like enough.",
    55: "Your relationship with abundance swings. A lean-feeling week is a mood, not a balance sheet.",
    56: "The story you tell about money shapes what you notice. Worth checking who wrote it.",
    57: "Immediate intuition about a financial decision. Quiet, quick, and easy to override with logic.",
    58: "Energy to improve your financial position, and the version where nothing is ever enough.",
    59: "Getting properly honest about money with someone close. Intimacy includes the numbers.",
    60: "Constraints. Working with the actual budget rather than the one you wish you had.",
    61: "Pressure to understand why money behaves the way it does for you. Some of it's not knowable.",
    62: "Details. Tracking precisely, and where thoroughness turns into avoidance of the bigger decision.",
    63: "Doubt about a financial plan. Useful scrutiny until it becomes the reason nothing ships.",
    64: "Replaying past financial decisions. Digestion, not crisis, and clarity arrives on its own schedule.",
  },
  purpose: {
    1: "Your original creative direction. Purpose here isn't found, it's expressed, and playing safe hides it.",
    2: "The receptive knowing of which way to go. Direction arrives as a pull rather than as a plan.",
    3: "A new direction begins in confusion. The mess is the beginning, not a sign you chose wrong.",
    4: "The mind demanding certainty about your purpose. It can't supply it, and pretending it can wastes years.",
    5: "Purpose reveals itself through rhythm and repetition, not through a single dramatic decision.",
    6: "Friction with others about your direction. Conflict here often clarifies what you actually want.",
    7: "Leading others somewhere. Whether you're willing to be the one with the direction.",
    8: "Contributing something only you would contribute. This is the closest gate to purpose itself.",
    9: "Sustained focus on one thing. Purpose looks like devotion over time rather than a revelation.",
    10: "Being yourself as the purpose. Self-love and authentic behaviour are the direction, not a step towards it.",
    11: "Ideas about what your purpose should be, most of them absorbed. Worth auditing whose they are.",
    12: "Expressing your direction out loud, and knowing when the moment is right to.",
    13: "Holding other people's stories, which is a genuine calling and not a lesser one.",
    14: "The material resources to actually pursue the direction, rather than only dreaming about it.",
    15: "Your purpose runs at its own tempo. Comparing it to someone else's timeline is where the doubt starts.",
    16: "Enthusiasm as a compass. What you're willing to practise badly is usually pointing somewhere true.",
    17: "Opinions about the right way to live. Strongly held, and worth checking against your actual experience.",
    18: "Seeing what needs correcting in the world. That instinct is often the purpose itself.",
    19: "Sensitivity to what people need. Purpose can arrive as being the one who notices.",
    20: "Purpose lived in the present rather than deferred to a version of you that has it figured out.",
    21: "Wanting control over your own direction. Autonomy is part of the purpose, not a luxury on top.",
    22: "Grace as a contribution. Being the one who makes a room feel different is a real purpose.",
    23: "Translating your inner knowing into words other people can use.",
    24: "Returning to the same question about meaning. The answer comes from living, not from more thinking.",
    25: "Universal love as direction. Purpose that's not about achievement at all.",
    26: "Persuading others towards your direction, and where conviction tips into self-promotion.",
    27: "Caring as a calling. Nourishing others is a legitimate purpose and it needs boundaries to survive.",
    28: "The struggle for meaning directly. This gate is the search itself, and the search isn't a failure state.",
    29: "Committing to a direction before you can see the whole path. Saying yes properly is the work.",
    30: "Desire and longing pointing somewhere. What you keep wanting is data about direction.",
    31: "Leading through your voice. Influence as purpose.",
    32: "Instinct for what will endure. Building something that outlives the enthusiasm.",
    33: "Retreat and reflection. Purpose often clarifies in withdrawal rather than in motion.",
    34: "Power in service of direction. Raw capacity is only useful once it's aimed.",
    35: "Hunger for experience. Collecting it's the purpose for some people, and that's legitimate.",
    36: "Crisis as the route to meaning. What you have been through becomes what you can offer.",
    37: "Purpose inside a family, a team or a community rather than as a solo pursuit.",
    38: "Fighting for what matters. This is purpose as stubbornness, and it's genuinely useful.",
    39: "Provoking others into feeling something. Disruption as a contribution.",
    40: "Knowing when you have given enough. Purpose doesn't require your exhaustion as proof.",
    41: "The pressure to begin a new chapter, felt as fantasy before it's a plan.",
    42: "Completing a cycle so the next one can begin. Endings are part of purpose.",
    43: "Knowing something nobody else has said yet. Being early is lonely and is often the point.",
    44: "Bringing the right people together. Purpose as pattern recognition about who fits where.",
    45: "Stewardship. Gathering resources and directing them somewhere that matters.",
    46: "Purpose through being fully in your body and your life, rather than in a plan for it.",
    47: "Making meaning from what you have been through. This is the alchemy gate.",
    48: "Fear you haven'thing worth offering, sitting directly on top of genuine depth.",
    49: "Principles worth breaking something over. Purpose as a line you won't cross.",
    50: "Responsibility for the standards of your people. Custodianship as a calling.",
    51: "Shock that reorients you. A jolt now often redirects the next decade.",
    52: "Stillness. Not chasing the direction is frequently how it arrives.",
    53: "Starting the new cycle. The pressure to begin, before the shape of it's clear.",
    54: "Ambition to rise, and the question of what you're rising towards.",
    55: "Your sense of meaning moves in waves. A flat week isn't a loss of purpose.",
    56: "Telling the story. Teaching, writing and sharing belief as the contribution itself.",
    57: "Intuitive clarity about direction, arriving quietly and immediately.",
    58: "The drive to make things better. Dissatisfaction pointed usefully is a purpose.",
    59: "Intimacy and connection as the work, breaking through to actual closeness with people.",
    60: "Accepting the limits of your situation, and finding the direction inside them rather than beyond them.",
    61: "The pressure to know why. Mystery is part of this one, and demanding an answer is the trap.",
    62: "Naming things precisely so others can follow. Purpose through clarity.",
    63: "Doubt about whether any of it means anything. Inquiry when it moves you, a loop when it doesn't.",
    64: "Mental replay of your own history, digesting it into something that eventually makes sense.",
  },
  career: {
    1: "Your original contribution, the thing only you would have made. Playing it safe here is the real risk this season.",
    2: "Direction. Knowing which way your work should go, before you can justify it on a spreadsheet.",
    3: "New ventures start badly. The difficult early phase is the shape of building something, not a verdict on it.",
    4: "Pressure to have the answer at work. Producing a confident one you haven't tested is the trap.",
    5: "Consistency beats intensity. The unglamorous weekly rhythm is what actually compounds into a career.",
    6: "Friction with colleagues or clients. Handled well it produces an agreement, avoided it produces a slow leak.",
    7: "Leadership, and whether you're willing to be the one out front rather than the one enabling.",
    8: "Getting credit for your actual contribution. Being valued for what makes you different, not for fitting the mould.",
    9: "Focus. What you give sustained attention to this season is what will look like luck in a year.",
    10: "Behaving like yourself at work. The cost of a professional persona you have to maintain is higher than it looks.",
    11: "Ideas, plenty of them. Ideas aren't the bottleneck, choosing one and staying with it is.",
    12: "Knowing when to speak and when the moment is wrong. Timing matters more than the content here.",
    13: "You're the one people confide in at work. Useful influence, and a role that can quietly consume your week.",
    14: "Resources and the material power to do the work properly. Funding, tools, time.",
    15: "Working at your own pace inside a system built for someone else's. The mismatch is the fatigue.",
    16: "Enthusiasm turning into skill. Repetition is what converts talent into a career.",
    17: "Your professional opinions. Strong views, and whether they're still being updated by evidence.",
    18: "Seeing what is broken. This is genuine quality control and it can become the thing people brace for.",
    19: "Sensitivity to what the team or client actually needs, often before they articulate it.",
    20: "Acting in the present rather than planning indefinitely. This season rewards doing the thing now.",
    21: "Control and autonomy. Who decides, who owns the budget, and whether you can work under someone else's authority.",
    22: "Grace under professional pressure. How you handle being challenged in public.",
    23: "Making the complicated idea simple enough to be bought, funded or understood.",
    24: "Returning to the same career question. The answer comes from trying it, not from another round of thinking.",
    25: "Doing the work for its own sake, not only for what it returns. This is what keeps a career survivable.",
    26: "Selling and persuading. Where confident positioning tips into overclaiming is the line this season.",
    27: "Looking after your team or clients, and whether that care is reciprocated or simply expected.",
    28: "Whether this work means anything. The struggle for purpose over security is live.",
    29: "Committing to a project properly. This is also where over-committing begins, so notice which one it is.",
    30: "Ambition and desire for a particular outcome. Powerful fuel, and it's not the same as strategy.",
    31: "Your voice and influence. Leading by being genuinely listened to rather than by title.",
    32: "Instinct about what will endure. You can usually tell which projects have a future, and it's worth trusting.",
    33: "Stepping back to review. Retreat is part of the work here, not a break from it.",
    34: "Raw capacity to do a lot. The power is real, and it's also how people end up doing three jobs for one salary.",
    35: "Hunger for the next thing. Genuine growth signal, and also how half-finished projects accumulate.",
    36: "Professional turbulence. A rough patch is often the career maturing rather than failing.",
    37: "Agreements and partnerships at work. Loyalty, contracts, and whether the deal is actually fair.",
    38: "Fighting for the work you believe in. Worth checking the fight is chosen rather than reflexive.",
    39: "Provoking a reaction to find out where you really stand with someone.",
    40: "Knowing when to stop. This gate is the boundary between working hard and working yourself into the ground.",
    41: "Imagining what is next. The fantasy stage is legitimate, and it's not yet a plan.",
    42: "Finishing. Closing a project properly rather than letting it drift is the whole assignment.",
    43: "A breakthrough you can't yet explain to anyone. Being early is lonely and often correct.",
    44: "Reading people and patterns. Who to work with, based on evidence you have collected before.",
    45: "Money, resources and who distributes them. This season makes the commercial reality explicit.",
    46: "Being in the right place at the right time. Showing up physically matters more than it should.",
    47: "Making sense of a confusing professional stretch. Clarity comes after, not during.",
    48: "Imposter feelings, and the actual depth sitting underneath them.",
    49: "Your principles about how you will be treated professionally, and whether you would walk.",
    50: "Responsibility for other people's work and standards. What you have taken on, and whether it's yours.",
    51: "Shock. Something disrupts the plan, and initiative matters more than composure.",
    52: "Concentration under pressure. Not reacting immediately is what produces the good decision.",
    53: "Starting something new. The pressure to begin can outrun whether you actually want this project.",
    54: "Ambition and the climb. Real drive, and the trap of measuring yourself only by the next rung.",
    55: "Your professional mood swings. A flat week is a wave, not a verdict on your career.",
    56: "Storytelling. How you frame the work is a large part of whether it lands.",
    57: "Intuition about a work decision, arriving instantly and quietly. Easy to talk yourself out of.",
    58: "Energy to improve things. Genuine vitality, and the version where nothing is ever good enough to ship.",
    59: "Getting properly close in a working relationship, past the professional surface.",
    60: "Constraints. Working with the actual budget, time and capacity rather than the ideal one.",
    61: "Pressure to understand why the work isn't landing. Some of it's not knowable yet.",
    62: "Details and precision. Naming things accurately, and where thoroughness becomes a stall.",
    63: "Doubt about the plan. Healthy scrutiny until it becomes a loop that prevents shipping.",
    64: "Mental replay of past professional experience. Confusion is processing, and clarity arrives on its own schedule.",
  },
  "health-body": {
    1: "Creative energy wants an outlet through your body. Unexpressed, it tends to sit in you as restlessness rather than leaving as rest.",
    2: "Your body knows which direction to go before your head does. Appetite, energy and aversion are the data this season.",
    3: "Starting something physical is deliberately uncomfortable at the beginning. The messy first fortnight is the shape of a new habit, not evidence it's wrong.",
    4: "Mental pressure to solve a health question. The answer usually needs a test and time rather than more reading.",
    5: "Rhythm. Eating, sleeping and moving at consistent times does more for you this season than any intense push.",
    6: "Emotional friction lands physically, in your gut and your chest. Conflict you haven't processed shows up as a body symptom.",
    7: "The pace you set for others is often the pace that quietly wrecks you. Leading has an energetic cost worth counting.",
    8: "Your body is part of how you show up, not the packaging around it. Dressing and moving as yourself is a health matter here.",
    9: "Sustained focus, and what it costs. Small consistent attention to one physical thing beats a scattered overhaul.",
    10: "How you treat your body when nobody is watching. Self-love here is behavioural rather than a feeling.",
    11: "Ideas about health, most of them absorbed from somewhere else. Worth separating what you believe from what you have actually tested.",
    12: "Holding words in has a physical cost. What you don't say tends to settle in the throat, jaw and shoulders.",
    13: "You carry other people's stories, and that's real weight. Discharging it matters as much as anything you eat.",
    14: "Resources and energy. Whether you have the practical support to actually rest, rather than just the intention to.",
    15: "Your natural rhythm isn't the standard one, and forcing it into someone else's schedule is where the depletion starts.",
    16: "Enthusiasm for a new physical practice. Repetition, not the initial excitement, is what turns it into capacity.",
    17: "Opinions about how your body should look or perform. Strongly held ones are worth examining this season.",
    18: "You notice what is wrong in the body early. That's genuine diagnostic instinct, and it can also become health anxiety.",
    19: "Sensitivity, including to food, environment and other people's states. Your needs are physical needs, not preferences.",
    20: "Being in your body in the present moment, rather than living a few feet above it in your head.",
    21: "Control over your own schedule. Health here is largely a question of who owns your time.",
    22: "Emotional openness has a physical release attached. Letting yourself be moved is nervous system work.",
    23: "Explaining what you're feeling physically, simply enough that someone can actually help.",
    24: "The mind loops on a body worry. Repetition is the mind processing, and it's not new information.",
    25: "Accepting your body as it's now, which is different from giving up on it.",
    26: "Pushing past what you have got. Willpower is real, and it runs down, and it doesn't refill by being told to.",
    27: "Nourishment. Whether you're actually feeding yourself, or feeding everyone else and eating the leftovers.",
    28: "The struggle for meaning can be exhausting. Ask whether the tiredness is physical or existential before treating it as either.",
    29: "Saying yes to a commitment your body has to carry. This is where over-committing physically starts.",
    30: "Desire and appetite. Wanting intensely is energising and it burns fuel, so notice which one is happening.",
    31: "Your voice and your throat. Speaking up, and the physical tension when you don't.",
    32: "Instinct about what will last. Your body usually knows which habits will survive and which are performance.",
    33: "Retreat. Genuine recovery needs actual withdrawal, not a lighter version of the same week.",
    34: "Pure sacral power. This is the gate most likely to make you work past a stop signal, because the power is genuinely there right up until it's not.",
    35: "Hunger for new experience. Novelty is energising and it's also how routines quietly collapse.",
    36: "Emotional turbulence with a physical tail. Crisis is metabolically expensive, so expect it to cost you sleep.",
    37: "The body relaxes around people it trusts. Who you're physically around matters more than it sounds.",
    38: "Fighting. Worth checking whether the tension you're carrying is protecting something or just habitual bracing.",
    39: "Provocation and the startle response. Your nervous system is easily set off this season, which is information rather than weakness.",
    40: "Recovery. This gate is the one that says the rest isn't optional and the exhaustion is the invoice.",
    41: "The pressure of anticipation. Imagining what is coming has the same physical cost as living it.",
    42: "Completion. Finishing a cycle properly, and the specific fatigue of leaving several half-open.",
    43: "Knowing something about your body you can't yet justify. Trust it before you can explain it.",
    44: "Pattern recognition about your own health history. What has happened before is genuinely predictive here.",
    45: "Resources and whether you have enough to look after yourself properly, rather than only enough to keep going.",
    46: "The gate of the body itself. Being in it, enjoying it, moving it for delight rather than for correction.",
    47: "Making sense of a confusing physical stretch. Meaning arrives after the experience, not during it.",
    48: "Fear of not being enough, which shows up physically as never resting because resting feels like falling behind.",
    49: "Your principles about how you treat your body, and where the actual line is.",
    50: "What you carry for your people, including inherited health patterns and inherited habits.",
    51: "Shock to the system. Something disrupts and the body registers it first.",
    52: "Stillness. Sitting with the pressure rather than discharging it immediately is the practice here.",
    53: "Beginning something new physically. The pressure to start is easy, sustaining it's the actual work.",
    54: "Ambition versus recovery. This is the pairing that produces burnout in high-functioning people.",
    55: "Mood and energy move together. A low day is often a wave rather than a diagnosis.",
    56: "The story you tell about your body shapes what you notice in it. Worth checking who wrote that story.",
    57: "Intuitive body clarity, the quiet immediate hit about what is right for you. Easy to override with logic and expensive to ignore.",
    58: "Vitality and the urge to improve. Genuine energy for it, and the trap of never being satisfied with the body you have.",
    59: "Intimacy and physical closeness, and how your body responds to being properly let in.",
    60: "Limitation. Working with your actual current capacity rather than the one you had five years ago.",
    61: "The pressure to know why you feel like this. Some of it won't be knowable, and chasing it costs sleep.",
    62: "Details. Tracking, measuring and naming things precisely, which either helps or becomes its own stress.",
    63: "Doubt about your own health. Useful when it prompts a test, corrosive when it just loops.",
    64: "Mental replay at night. This gate is often behind the wide-awake-at-3am pattern, and it's digestion rather than crisis.",
  },
  relationships: {
    1: "Your own creative self-expression becomes the thing that attracts, or the thing you keep editing down to be easier to love.",
    2: "You get a clearer sense of the direction you want a relationship to go, rather than drifting wherever the other person steers.",
    3: "New beginnings in love feel messy before they feel exciting. The awkward early stage isn't a bad sign here, it's the actual shape of starting.",
    4: "You want an answer about where this is going, and the mind will happily invent one. The pressure is mental, the answer isn't.",
    5: "Rhythm matters more than intensity. Whether someone fits your natural pace is the real compatibility question this season.",
    6: "The intimacy gate. Your capacity to let someone close opens and shuts in waves, and conflict here isn't failure, it's the doorway being tested.",
    7: "Who leads, and whether you're willing to be led. Direction inside a partnership becomes the live question.",
    8: "Being valued for what makes you different, rather than for how well you fit in. Bringing your actual self is the assignment.",
    9: "Attention to the small details of a relationship. What you focus on here compounds, in both directions.",
    10: "Self-love as the precondition. How you treat yourself sets the ceiling on what you will accept from someone else.",
    11: "Ideas about love, the ones you have absorbed and the ones you actually believe. Worth checking which is which.",
    12: "Whether you say the emotionally true thing or the socially smooth thing. Caution here can be wisdom or avoidance.",
    13: "You become the one people tell things to. Holding someone's story is intimacy, and it can also become a role you disappear into.",
    14: "What you bring materially and practically to a partnership, and whether that has quietly become how you earn your place.",
    15: "Your tolerance for other people's rhythms. Love asks you to stretch around difference without dissolving into it.",
    16: "Enthusiasm for someone, and whether you can stay past the exciting first phase into actual skill at loving them.",
    17: "Your opinions about how a relationship should go. Strong views here can be clarity or they can be a fence.",
    18: "You notice what is wrong. Used well that protects the relationship, used badly it becomes a running critique nobody asked for.",
    19: "Sensitivity to what your person needs, sometimes before they say it. The line between attunement and losing yourself is thin this season.",
    20: "Being present with someone rather than managing the impression. What you actually feel, in the moment, said out loud.",
    21: "Control. Who decides, who holds the resources, and whether you can share authority without feeling erased.",
    22: "Emotional grace under social pressure. How openly you let yourself be moved in front of someone else.",
    23: "Saying the complicated inner thing simply enough to be understood. Being misheard here is usually about timing rather than content.",
    24: "The returning mind. You keep going back over the same relationship question, and the answer arrives by living rather than by thinking.",
    25: "Loving without conditions attached, including loving yourself through the part where it's not being returned.",
    26: "Persuasion. How much you shape yourself to convince someone, and where that tips from charm into performance.",
    27: "Caring for someone. This season asks whether the care is mutual, or whether you have quietly become the one who does the nourishing.",
    28: "Whether this relationship means something. The struggle for depth over comfort shows up hard here.",
    29: "Commitment. Saying yes properly, and noticing where you have been half-in and calling it keeping your options open.",
    30: "Desire and longing. Wanting someone intensely is information, but it's not the same thing as clarity about them.",
    31: "Your voice inside the relationship. Whether you influence by being heard or by being loud.",
    32: "Instinct about what will last. You can usually tell early, and this season asks you to trust that read rather than argue with it.",
    33: "Retreat. Needing space to process is legitimate, and using it to avoid the conversation isn't the same thing.",
    34: "Raw energy and independence. Your power is attractive, and it can also be the reason you don't let anyone actually in.",
    35: "Hunger for something new. Restlessness in love is real information, though not always about the other person.",
    36: "Emotional crisis as a growth route. Turbulence now is often the relationship maturing rather than ending.",
    37: "The bond itself. Friendship, family, the agreements you have made. Loyalty gets examined, and so does whether it's equal.",
    38: "Fighting for it. Worth checking whether you're fighting for the relationship or just fighting because that's familiar.",
    39: "Provocation. You poke at the thing to get a real reaction, which either produces honesty or a fight, depending on the timing.",
    40: "Needing to be alone, inside a relationship. Denying that need is what produces the exhaustion, not the relationship itself.",
    41: "The fantasy of a relationship, versus the one in front of you. Imagination is the start of desire, and it's not evidence.",
    42: "Endings and completions. Finishing something properly rather than letting it trail off is the work here.",
    43: "You know something about this relationship that you can't yet explain. Being ahead of your own words is uncomfortable and usually correct.",
    44: "Instinct about people, often about patterns you have met before. Your past is pattern-matching, and it's sometimes right.",
    45: "Sharing resources, and who holds them. This season makes the practical side of togetherness explicit rather than assumed.",
    46: "Being in your body with someone. Physical presence, touch and the delight of the ordinary.",
    47: "Making sense of what happened. You're processing a relationship experience into meaning, and it will feel confused before it lands.",
    48: "Fear of not being enough for someone, and the depth you actually have underneath that fear.",
    49: "Your principles about how you will be treated. Where the line is, and whether you're willing to end something over it.",
    50: "Responsibility to the people who are yours. What you owe, what you have inherited, and which of it's genuinely yours to carry.",
    51: "Shock. Something disrupts the relationship and forces initiative, and courage matters more than composure here.",
    52: "Stillness under pressure. Not acting on the relationship feeling immediately is what gives it room to become clear.",
    53: "Beginning something. New energy arrives, and the pressure to start can outrun whether you actually want this one.",
    54: "Ambition inside a relationship, including the uncomfortable question of whether being with someone raises or lowers you.",
    55: "The emotional weather. Your mood swings between abundance and emptiness, and neither one is the truth about the relationship.",
    56: "Stories. The story you tell about your love life shapes what you notice next, and it's worth checking who wrote it.",
    57: "Intuitive clarity in the present moment. The quiet first hit about someone, which is usually accurate and easy to argue away.",
    58: "Vitality and the urge to improve things. Wanting better for a relationship is love, and constant correction isn't.",
    59: "Intimacy and sexuality directly. Breaking through the barrier to actual closeness, and the honesty that requires.",
    60: "Limitation. Accepting the real constraints of a relationship rather than the version you wish it were.",
    61: "The pressure to understand why someone is the way they are. Some of it's not knowable, and sitting with that's the practice.",
    62: "The details. Naming things precisely, which either creates real understanding or turns into pedantry mid-argument.",
    63: "Doubt. Questioning the relationship is healthy inquiry until it becomes a loop, and the difference is whether it produces action.",
    64: "Mental replay of past relationships. Confusion now is the mind digesting something, and clarity arrives on its own schedule.",
  },
};

/** The area-specific reading for a gate, falling back to the universal keynote. */
export function gateLensFor(areaId: string, gate: number, fallback: string): string {
  return AREA_GATE_LENS[areaId]?.[gate] ?? fallback;
}
