// Personalised sign-by-sign readings for each placement

export const HOUSE_READINGS: Record<number, string> = {
  1: "And with this sitting in your 1st house? It's literally tattooed on your aura. This isn't background noise. It's the first thing people feel when you walk into a room. It's your identity, babe. Own it.",
  2: "With this in your 2nd house, it's directly tied to your money, your self-worth, and what you believe you deserve. This placement is basically your abundance blueprint. The question isn't whether you can have it all. It's whether you believe you're allowed to.",
  3: "This lands in your 3rd house, which means it shows up every time you open your mouth, write a caption, or have a conversation. Your communication style, your ideas, your daily interactions. This energy is woven through all of it.",
  4: "This lives in your 4th house, right at the emotional core of who you are. Your home, your family, your roots, the foundation everything else is built on. This is the most private, most tender part of your chart. Protect it fiercely.",
  5: "And this is in your 5th house, which is the most fun, creative, romantic house in the entire chart. This energy fuels your self-expression, your love affairs, your creative projects, and your ability to experience pure joy. This is your inner child on fire.",
  6: "With this in your 6th house, it plays out in your daily rituals, your health, your work habits. The unglamorous stuff that actually runs your life. The routines you build around this placement will either make you or break you. Choose wisely.",
  7: "This sits in your 7th house, which means it plays out most intensely in your closest relationships. Romantic partners, business partners, best friends. The people you go all in with. This energy isn't just yours. It's activated by the people you choose.",
  8: "This is in your 8th house, which is next level. This is the house of transformation, intimacy, other people's money, and everything most people are too scared to look at. You're not most people. This placement gives you power most can only dream of.",
  9: "With this in your 9th house, it's tied to your quest for meaning, adventure, and truth. Travel, higher learning, philosophy, publishing, big-picture thinking. This placement makes you hungry for experiences that blow your mind wide open.",
  10: "This lands in your 10th house, which is literally your career and public reputation. Everyone can see this energy in your work, your achievements, your legacy. This isn't hidden. This is how the world knows you. Make it count.",
  11: "And this is in your 11th house, connecting it to your friendships, your community, and your vision for the future. The groups you belong to, the causes you champion, the collective dreams you're part of. Your people activate this energy in you.",
  12: "This lives in your 12th house, which means most of it is happening beneath the surface. Your subconscious, your dreams, your spiritual life, the stuff you process when nobody's watching. It's incredibly powerful but deeply private. Trust what you feel even when you can't explain it.",
};

export const SUN_READINGS: Record<string, string> = {
  Aries: "You're an Aries Sun, which means you were born to go first, lead loud, and never apologise for wanting more. You're the spark that lights the room. You don't wait for permission. You don't need a plan. You need momentum. Your confidence isn't arrogance, it's medicine for everyone around you who's too scared to go after what they want.",
  Taurus: "You're a Taurus Sun, which means you were built for pleasure, beauty, and the long game. You're not slow, you're intentional. While everyone else is chasing shiny things, you're building something that lasts. Your superpower is your taste. You know what's worth your time, your money, and your energy and you refuse to settle for less.",
  Gemini: "You're a Gemini Sun, which means you were born to be the most interesting person in the room. Your mind moves at a speed most people can't keep up with. You're curious, witty, and endlessly adaptable. You're not flaky, you're evolving in real time. The world needs your ideas, your words, and your refusal to be put in a box.",
  Cancer: "You're a Cancer Sun, which means you feel everything at a depth most people can't even imagine. That's not weakness. That's your superpower. You're the person people come to when they need to feel safe, seen, and held. Your intuition is sharper than anyone's logic. Trust it. Your softness is the most powerful thing about you.",
  Leo: "You're a Leo Sun, which means you were literally born to shine. Not in a 'please look at me' way. In a 'I was put here to inspire people' way. You radiate warmth, generosity, and creative fire. When you dim your light to make other people comfortable, the whole room gets darker. Stop doing that. The world needs your full wattage.",
  Virgo: "You're a Virgo Sun, which means you see what nobody else sees. The details. The patterns. The potential. You're not critical, you're precise. You don't have impossible standards, you have a vision. The world runs on the systems you build and the care you put into everything you touch. Your perfectionism isn't a flaw. It's a gift.",
  Libra: "You're a Libra Sun, which means you were born with an extraordinary sense of beauty, balance, and fairness. You're the person who makes everything more harmonious just by being there. You're not indecisive, you see every angle. That's rare. Stop apologising for taking your time. Your ability to create beauty and peace is a superpower.",
  Scorpio: "You're a Scorpio Sun, which means you see through everything. Every mask. Every lie. Every surface-level performance. You're not intense, you're honest. And the world isn't used to that. Your depth terrifies people who are committed to staying shallow. That's their problem, not yours. Your power is in your ability to transform everything you touch.",
  Sagittarius: "You're a Sagittarius Sun, which means you were born with an insatiable hunger for truth, adventure, and meaning. You're not restless, you're expanding. You need freedom the way other people need security. Your optimism isn't naive, it's visionary. You see possibilities where other people see dead ends. That makes you dangerous in the best way.",
  Capricorn: "You're a Capricorn Sun, which means you were built for legacy. Not just success. Legacy. You think in decades while everyone else is thinking in days. Your ambition isn't cold, it's focused. You know that nothing worth building happens overnight and you're willing to put in the work. When you finally arrive, it looks effortless. It wasn't.",
  Aquarius: "You're an Aquarius Sun, which means you were born ahead of your time. You think differently. You see differently. You exist differently. And that used to make you feel like an outsider but it's actually what makes you essential. You're not here to fit in. You're here to show everyone else what's possible when you stop following the rules.",
  Pisces: "You're a Pisces Sun, which means you live between worlds. You feel things other people can't even name. Your empathy, your creativity, your intuition, your ability to see the magic in the mundane. That's not too much. That's exactly right. You're not naive for believing in something more. You're brave for refusing to let the world make you cynical.",
};

export const MOON_READINGS: Record<string, string> = {
  Aries: "Your Moon in Aries means you process emotions through action. You don't sit with feelings, you burn through them. When you're upset, you need to move, fight, create, do something. Stillness makes you anxious. Your emotional need is autonomy. You feel safest when you feel free, and you fall apart when you feel controlled.",
  Taurus: "Your Moon in Taurus means your emotional world revolves around safety, comfort, and sensory pleasure. You need routine. You need softness. You need your space to feel like a sanctuary. When your environment is chaotic, your nervous system short-circuits. Feed your Moon with luxury, nature, good food, and the knowledge that you are deeply, permanently OK.",
  Gemini: "Your Moon in Gemini means you process emotions through words and ideas. You talk to think. You think to feel. Your emotional landscape changes quickly and that doesn't make you unstable, it makes you complex. You feel safest when you can name what you're feeling and share it with someone who listens. Silence is not your friend.",
  Cancer: "Your Moon is in its home sign, which means your emotional world is incredibly rich, deep, and powerful. You feel everything. Not just your own emotions, everyone's. You need safety, nurturing, and a home that feels like a hug. You're not too sensitive. You're exactly sensitive enough. Your ability to hold space for other people's pain is extraordinary.",
  Leo: "Your Moon in Leo means you have an emotional need to be seen, appreciated, and adored. That's not vanity, that's valid. You process feelings through creative expression and generosity. You feel safest when you feel special. When people take you for granted, it doesn't just hurt, it devastates. Surround yourself with people who celebrate you. You deserve it.",
  Virgo: "Your Moon in Virgo means you process emotions through order, analysis, and service. When things feel chaotic inside, you organise outside. Your emotional need is to feel useful and in control. You worry because you care. Perfectionism is your emotional defence mechanism. Learning to accept 'good enough' isn't lowering your standards, it's saving your nervous system.",
  Libra: "Your Moon in Libra means your emotional world is deeply connected to your relationships. You need harmony, beauty, and partnership to feel balanced. Conflict genuinely destabilises you. Your emotional need is to be in a peaceful, fair environment where love flows both ways. You're not codependent for wanting connection. You're wired for partnership.",
  Scorpio: "Your Moon in Scorpio means your emotional world runs deeper than the ocean floor. You feel things with an intensity that would terrify most people. You don't do surface-level anything. Your emotional need is for truth, intimacy, and transformation. You'd rather be devastated by honesty than comforted by a lie. That takes extraordinary courage.",
  Sagittarius: "Your Moon in Sagittarius means you process emotions by making meaning out of them. You don't just feel things, you need to understand WHY you feel them. Your emotional need is freedom, adventure, and the sense that life is an expansive, meaningful journey. You heal through travel, learning, and conversations that make you see the world differently.",
  Capricorn: "Your Moon in Capricorn means you were taught early that emotions were a luxury you couldn't afford. So you learned to be strong, responsible, and self-sufficient. Your emotional need is for structure and achievement, because success makes you feel safe. The work now is learning that vulnerability isn't weakness. You're allowed to need people.",
  Aquarius: "Your Moon in Aquarius means you process emotions from a distance. You observe your feelings more than you feel them, and that's both your gift and your challenge. Your emotional need is for freedom, intellectual stimulation, and a sense of belonging to something bigger than yourself. You feel safest in groups but struggle with one-on-one intimacy.",
  Pisces: "Your Moon in Pisces means you absorb everything. Every mood in the room. Every unspoken tension. Every emotional undercurrent that nobody else notices. You're an emotional sponge and that's both beautiful and exhausting. Your need is for regular solitude, creative expression, and spiritual practice. Without energetic boundaries, you'll drown in feelings that aren't even yours.",
};

export const RISING_READINGS: Record<string, string> = {
  Aries: "With Aries Rising, you walk into every room like you own it. Your first impression is bold, direct, and magnetic. People see you as confident, competitive, and slightly intimidating. Your physical energy is high and you move fast. You're the person people notice first. Own that. Your rising sign is your superpower in any room.",
  Taurus: "With Taurus Rising, you radiate calm, luxury, and effortless beauty. People see you as grounded, elegant, and quietly powerful. You probably get told you have great taste and an amazing voice. Your physical presence is solid and reassuring. People feel safe around you. You don't need to be loud. Your energy speaks volumes.",
  Gemini: "With Gemini Rising, you come across as witty, curious, and endlessly interesting. People are drawn to your energy because you make everything fun. You probably look younger than you are. Your first impression is friendly, talkative, and slightly unpredictable. You're the person who can talk to anyone about anything. That's a superpower.",
  Cancer: "With Cancer Rising, you radiate warmth, nurturing energy, and emotional depth. People feel instantly comfortable around you. Your face is expressive and your eyes give everything away. You come across as approachable, caring, and deeply intuitive. People tell you their secrets within five minutes of meeting you. That's your rising sign doing its thing.",
  Leo: "With Leo Rising, you are literally the main character. You walk into a room and the energy shifts. People see you as warm, dramatic, and impossibly charismatic. You probably have amazing hair. Your physical presence is golden and magnetic. You were born to be looked at and there's nothing wrong with enjoying it.",
  Virgo: "With Virgo Rising, you come across as put-together, intelligent, and quietly chic. People see you as someone who has their life figured out (even when you don't). Your style is clean, minimal, and considered. You notice everything. First impressions of you are: polished, competent, and slightly intimidating in a 'she definitely has a spreadsheet for that' way.",
  Libra: "With Libra Rising, you are effortlessly charming. People are drawn to your grace, your style, and your ability to make everyone feel seen. You come across as beautiful, balanced, and diplomatically brilliant. Your physical presence is harmonious. You're the person people want to sit next to at dinner. Your rising sign is pure social magic.",
  Scorpio: "With Scorpio Rising, your presence is magnetic, intense, and impossible to ignore. People feel you before they see you. You come across as mysterious, powerful, and slightly dangerous. Your eye contact alone could end someone. You don't reveal yourself easily and that makes people obsessed with figuring you out. Let them wonder.",
  Sagittarius: "With Sagittarius Rising, you come across as adventurous, optimistic, and cosmopolitan cool. People see you as the person with the best stories and the biggest laugh. Your energy is expansive and contagious. You look like someone who just got back from somewhere incredible. Your rising sign makes people want to go wherever you're going.",
  Capricorn: "With Capricorn Rising, you radiate authority, ambition, and quiet power. People see you as someone who means business. Your first impression is serious, polished, and impressive. You age in reverse (you looked mature at 20 and will look 30 at 50). Your rising sign commands respect before you've even spoken. Use that.",
  Aquarius: "With Aquarius Rising, you come across as unique, cool, and slightly from the future. People can't quite figure you out and that's by design. You radiate originality and independence. Your style is unconventional and ahead of the curve. You're the person people describe as 'different but in the best way.' Your rising sign makes you unforgettable.",
  Pisces: "With Pisces Rising, you radiate ethereal, otherworldly beauty. People see you as dreamy, artistic, and slightly magical. Your presence is soft but deeply felt. You probably get told you have 'something about you' that people can't quite name. That's your Pisces Rising casting a spell on everyone in the room without even trying.",
};

export const VENUS_READINGS: Record<string, string> = {
  Aries: "Your Venus in Aries means you love hard, fast, and unapologetically. You're attracted to confidence, boldness, and people who aren't afraid to go after what they want. In style, you gravitate toward red, statement pieces, and anything that says 'I'm here.' You don't do subtle romance. You do grand gestures and electric chemistry.",
  Taurus: "Your Venus is in one of its home signs, which means your sense of beauty and love is world-class. You're drawn to luxury, quality, and things that feel as good as they look. In relationships, you need consistency, physical touch, and someone who makes you feel genuinely safe. Your style is expensive-looking, sensual, and timeless.",
  Gemini: "Your Venus in Gemini means you fall in love with minds first. Conversation is foreplay. You need intellectual stimulation, variety, and someone who can keep up with your wit. In style, you love mixing patterns, playing with trends, and never wearing the same look twice. You get bored easily and that's not a flaw, it's a feature.",
  Cancer: "Your Venus in Cancer means you love with your whole heart or not at all. You need emotional safety, nurturing, and a partner who feels like home. You're attracted to softness, romance, and anyone who makes you feel protected. In style, you gravitate toward silk, linen, pearls, and anything that feels like a warm hug.",
  Leo: "Your Venus in Leo means you love like a movie. Grand. Dramatic. Unforgettable. You need to feel adored, celebrated, and treated like royalty. You're attracted to people who are as bold and generous as you are. In style, you gravitate toward gold, bold prints, statement jewellery, and anything that makes you the centre of attention.",
  Virgo: "Your Venus in Virgo means you show love through acts of service, attention to detail, and quiet devotion. You're attracted to intelligence, competence, and people who have their lives together. In style, you're drawn to minimal, tailored, and incredibly well-made pieces. You'd rather own three perfect things than thirty mediocre ones.",
  Libra: "Your Venus is in its home sign, making you a natural aesthete with impeccable taste. You need beauty, harmony, and partnership to feel alive. You're attracted to elegance, charm, and people who treat love as an art form. In style, you're drawn to romantic coordinates, Parisian chic, and anything perfectly balanced.",
  Scorpio: "Your Venus in Scorpio means you love with terrifying intensity. You don't do casual. You don't do surface. You do soul-deep, all-consuming, transformative love or nothing. You're attracted to mystery, power, and people who aren't afraid of the dark. In style, you gravitate toward black, leather, dark feminine energy, and pieces with an edge.",
  Sagittarius: "Your Venus in Sagittarius means you love freely and need a partner who loves freedom as much as you do. You're attracted to adventurers, philosophers, and people who make the world feel bigger. In style, you gravitate toward eclectic pieces, travel-inspired looks, and anything that says 'I've been somewhere interesting.'",
  Capricorn: "Your Venus in Capricorn means you approach love like a long-term investment. You're attracted to ambition, maturity, and people who are building something real. You show love through commitment, reliability, and quiet acts of devotion. In style, you gravitate toward power dressing, investment pieces, and timeless elegance.",
  Aquarius: "Your Venus in Aquarius means you love unconventionally. You need freedom, intellectual connection, and a relationship that doesn't follow anyone else's rules. You're attracted to originality, brilliance, and people who think differently. In style, you gravitate toward avant-garde pieces, unconventional brands, and anything that makes people ask 'what IS that?'",
  Pisces: "Your Venus is exalted in Pisces, which means your capacity for love is cosmic. You love unconditionally, romantically, and with your entire soul. You're attracted to artists, dreamers, and anyone with depth. In style, you gravitate toward flowing fabrics, ethereal colours, and anything that makes you feel like you're floating through a painting.",
};

export const MARS_READINGS: Record<string, string> = {
  Aries: "Your Mars is in its home sign, making your drive unstoppable. You go after what you want with zero hesitation. You're competitive, direct, and physically energised. When you're angry, it's hot, fast, and over quickly. Your passion is fire and your energy is contagious. You need to be first, to win, and to feel alive.",
  Taurus: "Your Mars in Taurus means you're a slow, steady, and incredibly persistent force. You don't rush into anything, but once you decide you want something, nothing stops you. Your drive is fuelled by security and sensory pleasure. You're patient until you're pushed too far, then you're an earthquake. Your endurance outlasts everyone.",
  Gemini: "Your Mars in Gemini means your drive is intellectual. You fight with words, not fists. Your energy comes in bursts and you need variety to stay motivated. You're attracted to wit and mental sparring. When you're angry, you get sharp-tongued. Your superpower is your ability to multitask and talk your way into (or out of) anything.",
  Cancer: "Your Mars in Cancer means your drive is emotionally motivated. You fight hardest for the people you love. Your energy is connected to your emotional state. You're passive-aggressive when hurt (you know it). Your passion is protective and nurturing. You're most motivated when you're building something safe for yourself and the people who matter.",
  Leo: "Your Mars in Leo means your drive is fuelled by recognition, creativity, and the desire to be extraordinary. You don't just want to succeed, you want to be celebrated for it. Your energy is warm, dramatic, and generous. When you're passionate about something, your enthusiasm is contagious. You need to be proud of what you're doing or you can't do it.",
  Virgo: "Your Mars in Virgo means your drive is precise, methodical, and incredibly effective. You don't waste energy. Every move is calculated and intentional. You're motivated by improvement and mastery. When you're angry, you get critical and sharp. Your superpower is your ability to see exactly what needs to be fixed and fix it perfectly.",
  Libra: "Your Mars in Libra means you're driven by fairness, beauty, and partnership. You fight for justice and balance. Your energy is charming and diplomatic, but don't let anyone mistake that for weakness. You're motivated by collaboration and you perform best with a partner. When you're angry, you get passive-aggressive before you get direct.",
  Scorpio: "Your Mars is in one of its home signs, making your drive intensely powerful. When you want something, you pursue it with single-minded, relentless focus. You never show your full hand. You're strategic, patient, and willing to play the long game. Your passion is all-consuming and your anger is nuclear. Cross you once and you'll never forget.",
  Sagittarius: "Your Mars in Sagittarius means your drive is fuelled by freedom, adventure, and the pursuit of truth. You need to feel like you're going somewhere big. You're motivated by possibility and expansion. When you're angry, you're brutally honest. Your energy is restless, optimistic, and bigger than any single project can contain.",
  Capricorn: "Your Mars is exalted in Capricorn, making your drive disciplined, strategic, and incredibly powerful. You approach goals like a CEO approaches a business plan. You're willing to climb slowly because you know the view from the top is worth it. Your ambition is quiet but relentless. You will outwork everyone in the room.",
  Aquarius: "Your Mars in Aquarius means your drive is fuelled by a vision for the future. You're motivated by innovation, social change, and being different. Your energy is unpredictable and brilliant. When you're angry, you detach and become ice-cold. Your superpower is your ability to see systems clearly and disrupt the ones that aren't working.",
  Pisces: "Your Mars in Pisces means your drive is intuitive, creative, and deeply spiritual. You don't force things, you flow into them. Your energy works best when you surrender to inspiration rather than pushing through. When you're angry, you withdraw. Your passion is connected to a higher purpose and you're most powerful when you're creating from your soul.",
};

export const CHIRON_READINGS: Record<string, string> = {
  Aries: "Your Chiron in Aries means your deepest wound is around identity and self-worth. At some point, you were taught that who you are isn't enough. The healing? Becoming radically, unapologetically yourself. Your gift is helping other people find the courage to be who they really are.",
  Taurus: "Your Chiron in Taurus means your deepest wound is around self-worth, money, and feeling deserving. You may struggle to believe you're worthy of abundance. The healing? Learning that you are inherently valuable, not because of what you have or produce. Your gift is helping others recognise their worth.",
  Gemini: "Your Chiron in Gemini means your deepest wound is around communication and being heard. You may have been told your ideas didn't matter, or struggled to express yourself clearly. The healing? Trusting your voice. Your gift is helping other people find theirs.",
  Cancer: "Your Chiron in Cancer means your deepest wound is around home, family, and emotional safety. You may have grown up feeling emotionally unsupported or like you had to parent yourself. The healing? Creating the safety you never had. Your gift is your extraordinary ability to nurture and hold space.",
  Leo: "Your Chiron in Leo means your deepest wound is around visibility, creativity, and being seen. You may have been shamed for wanting attention or told you were 'too much.' The healing? Shining anyway. Your gift is giving other people permission to be their fullest, brightest selves.",
  Virgo: "Your Chiron in Virgo means your deepest wound is around perfectionism and never feeling good enough. You hold yourself to impossible standards and beat yourself up for falling short. The healing? Embracing imperfection as human. Your gift is helping others see that they're already enough.",
  Libra: "Your Chiron in Libra means your deepest wound is around relationships and self-abandonment. You may lose yourself in partnerships or struggle to set boundaries because you fear losing love. The healing? Learning to choose yourself without guilt. Your gift is teaching others about healthy love.",
  Scorpio: "Your Chiron in Scorpio means your deepest wound is around trust, betrayal, and vulnerability. You may have experienced profound loss or learned early that people can't be trusted. The healing? Letting yourself be seen anyway. Your gift is your ability to sit in the darkness with people and not look away.",
  Sagittarius: "Your Chiron in Sagittarius means your deepest wound is around meaning, belief, and faith. You may have lost faith in something important, or struggled to find your sense of purpose. The healing? Building your own belief system. Your gift is helping others find meaning in their pain.",
  Capricorn: "Your Chiron in Capricorn means your deepest wound is around achievement, authority, and feeling like a failure. You may feel like no matter how much you accomplish, it's never enough. The healing? Separating your worth from your achievements. Your gift is redefining success for others.",
  Aquarius: "Your Chiron in Aquarius means your deepest wound is around belonging and feeling like an outsider. You may have spent your life feeling different, misunderstood, or like you don't fit in anywhere. The healing? Realising your difference is your contribution. Your gift is creating spaces where everyone belongs.",
  Pisces: "Your Chiron in Pisces means your deepest wound is around spiritual disconnection and escapism. You may struggle with boundaries, overwhelm, or numbing out when reality gets too heavy. The healing? Finding healthy ways to connect to something bigger. Your gift is your extraordinary compassion and spiritual sensitivity.",
};

export const SATURN_READINGS: Record<string, string> = {
  Aries: "Saturn in Aries means your biggest life lesson is learning to trust yourself. You may struggle with self-doubt, hesitation, or fear of being assertive. Your growth comes from taking bold action even when you're scared. By your Saturn return, you'll have earned the kind of confidence nobody can shake.",
  Taurus: "Saturn in Taurus means your biggest life lesson is around self-worth and money. You may have grown up with scarcity or fear around finances. Your growth comes from building genuine security and learning that you deserve abundance. Mastery here makes you unshakeably grounded.",
  Gemini: "Saturn in Gemini means your biggest life lesson is around communication and learning. You may have struggled with expressing yourself or been told your ideas weren't serious. Your growth comes from disciplining your mind and committing to mastering your voice. When you do, your words carry real authority.",
  Cancer: "Saturn in Cancer means your biggest life lesson is around emotional vulnerability and family. You may have had to grow up fast or suppress your emotions early. Your growth comes from letting yourself need people and creating the family you always wanted, whether by blood or by choice.",
  Leo: "Saturn in Leo means your biggest life lesson is around self-expression and receiving love. You may struggle with feeling worthy of attention, praise, or joy. Your growth comes from letting yourself be seen and celebrated without guilt. When you master this, your creative power is extraordinary.",
  Virgo: "Saturn in Virgo means your biggest life lesson is around perfectionism and self-acceptance. You hold yourself to standards that would break most people. Your growth comes from learning that 'done' is better than 'perfect' and that your worth isn't measured by your productivity.",
  Libra: "Saturn in Libra means your biggest life lesson is around relationships and boundaries. You may struggle with people-pleasing or staying in partnerships that don't serve you. Your growth comes from learning what genuine equality looks like in love and holding your standards with grace.",
  Scorpio: "Saturn in Scorpio means your biggest life lesson is around power, control, and transformation. You may fear your own depth or struggle to let go. Your growth comes from surrendering control and trusting the process of dying and being reborn. Mastery here gives you incredible psychological strength.",
  Sagittarius: "Saturn in Sagittarius means your biggest life lesson is around belief, truth, and expansion. You may struggle with commitment, dogma, or fear of limitation. Your growth comes from building a philosophy you actually live by, not just talk about. When you master this, your wisdom is unmatched.",
  Capricorn: "Saturn is in its home sign, which means your life lessons around achievement, responsibility, and authority are intense but incredibly rewarding. You may feel the weight of expectation heavily. Your growth comes from leading with integrity. When you master this, you build things that last for generations.",
  Aquarius: "Saturn in Aquarius means your biggest life lesson is around individuality, community, and social responsibility. You may struggle with fitting in while being yourself. Your growth comes from finding your people and leading change without losing yourself. Mastery here makes you a visionary leader.",
  Pisces: "Saturn in Pisces means your biggest life lesson is around boundaries, faith, and surrendering control. You may struggle with escapism or taking on other people's pain. Your growth comes from learning to hold compassion without drowning in it. When you master this, your spiritual authority is profound.",
};

export const NORTH_NODE_READINGS: Record<string, string> = {
  Aries: "Your North Node in Aries means your soul's purpose is to learn independence, courage, and self-leadership. You've spent lifetimes (or your early life) prioritising others. Now you're here to put yourself first without guilt. Your purpose activates every time you choose yourself.",
  Taurus: "Your North Node in Taurus means your soul's purpose is to learn stability, self-worth, and presence. You're here to slow down, build something real, and learn that you don't need chaos to feel alive. Your purpose activates when you choose peace over drama.",
  Gemini: "Your North Node in Gemini means your soul's purpose is to learn, communicate, and stay curious. You're here to gather information, share ideas, and stay flexible. Your purpose activates when you ask questions instead of claiming you already know the answer.",
  Cancer: "Your North Node in Cancer means your soul's purpose is to learn vulnerability, emotional honesty, and nurturing. You're here to build a home within yourself. Your purpose activates every time you let yourself feel instead of performing strength.",
  Leo: "Your North Node in Leo means your soul's purpose is to learn self-expression, creativity, and joy. You're here to step into the spotlight and lead from the heart. Your purpose activates every time you create something from your soul, and let people see it.",
  Virgo: "Your North Node in Virgo means your soul's purpose is to learn service, discernment, and practical mastery. You're here to be useful, to refine, and to make things work. Your purpose activates when you focus on what's real instead of what's ideal.",
  Libra: "Your North Node in Libra means your soul's purpose is to learn partnership, diplomacy, and genuine collaboration. You're here to balance independence with connection. Your purpose activates when you choose cooperation over competition.",
  Scorpio: "Your North Node in Scorpio means your soul's purpose is to learn depth, transformation, and emotional truth. You're here to go beneath the surface and transform. Your purpose activates every time you choose vulnerability over comfort.",
  Sagittarius: "Your North Node in Sagittarius means your soul's purpose is to seek truth, explore, and expand your worldview. You're here to take the big leap. Your purpose activates when you follow your faith over your fear.",
  Capricorn: "Your North Node in Capricorn means your soul's purpose is to learn discipline, leadership, and building a legacy. You're here to create something that outlasts you. Your purpose activates when you take responsibility for your power.",
  Aquarius: "Your North Node in Aquarius means your soul's purpose is to learn innovation, community, and collective vision. You're here to be different and use that difference to change things. Your purpose activates when you prioritise the future over personal glory.",
  Pisces: "Your North Node in Pisces means your soul's purpose is to learn surrender, compassion, and spiritual connection. You're here to trust the universe. Your purpose activates when you let go of control and let yourself be guided by something bigger.",
};

export const JUPITER_READINGS: Record<string, string> = {
  Aries: "Your Jupiter in Aries means luck and abundance come to you when you take bold, independent action. You expand through courage. The universe rewards you for going first, starting things, and betting on yourself. Your abundance code: be brave.",
  Taurus: "Your Jupiter in Taurus means luck and abundance come to you through patience, luxury, and building things slowly. You expand through pleasure and material mastery. The universe rewards you for investing wisely and trusting the process. Your abundance code: slow wealth.",
  Gemini: "Your Jupiter in Gemini means luck and abundance come to you through ideas, communication, and networking. You expand through learning and connecting. The universe rewards you for staying curious and sharing what you know. Your abundance code: talk about it.",
  Cancer: "Your Jupiter in Cancer means luck and abundance come to you through nurturing, home, and emotional intelligence. You expand through family and caring. The universe rewards you for creating safe spaces. Your abundance code: lead with your heart.",
  Leo: "Your Jupiter in Leo means luck and abundance come to you through creativity, self-expression, and generosity. You expand through shining. The universe rewards you for being visible and sharing your gifts. Your abundance code: let them see you.",
  Virgo: "Your Jupiter in Virgo means luck and abundance come to you through service, health, and attention to detail. You expand through being useful. The universe rewards you for doing excellent work and caring about the details. Your abundance code: master your craft.",
  Libra: "Your Jupiter in Libra means luck and abundance come to you through partnerships, beauty, and diplomacy. You expand through relationships. The universe rewards you for creating harmony and choosing collaborators wisely. Your abundance code: partner up.",
  Scorpio: "Your Jupiter in Scorpio means luck and abundance come to you through transformation, depth, and other people's resources. You expand through going deep. The universe rewards you for investigating, transforming, and not being afraid of the dark. Your abundance code: go deeper.",
  Sagittarius: "Your Jupiter is in its home sign, making you naturally lucky and expansive. Abundance comes through travel, education, and following your truth. The universe rewards you for taking risks, exploring, and keeping the faith. Your abundance code: say yes to everything.",
  Capricorn: "Your Jupiter in Capricorn means luck and abundance come to you through discipline, strategy, and long-term planning. You expand through structure. The universe rewards you for showing up consistently and building with intention. Your abundance code: play the long game.",
  Aquarius: "Your Jupiter in Aquarius means luck and abundance come to you through innovation, community, and thinking differently. You expand through networks and ideas. The universe rewards you for being ahead of the curve. Your abundance code: be the future.",
  Pisces: "Your Jupiter is in one of its home signs, making your spiritual abundance extraordinary. Luck comes through intuition, creativity, and surrender. The universe rewards you for trusting, creating, and letting go of control. Your abundance code: let it flow.",
};

export const MIDHEAVEN_READINGS: Record<string, string> = {
  Aries: "Your Midheaven in Aries means your career path is about pioneering, leading, and being the first. You're meant to be in charge. Entrepreneurship, athletics, leadership roles, or anything that lets you forge your own path. You need autonomy in your work or you'll burn out.",
  Taurus: "Your Midheaven in Taurus means your career path is about building something beautiful, valuable, and lasting. Finance, art, luxury, real estate, or anything that combines beauty with material success. You're meant to create wealth through patience and impeccable taste.",
  Gemini: "Your Midheaven in Gemini means your career path is about communication, teaching, and sharing ideas. Writing, media, marketing, education, or anything that lets you use your voice and connect with people. You might have more than one career. That's not indecisive, that's your design.",
  Cancer: "Your Midheaven in Cancer means your career path is about nurturing, creating safe spaces, and emotional leadership. Therapy, hospitality, food, family businesses, or anything that lets you care for people. You're meant to be the person people trust completely.",
  Leo: "Your Midheaven in Leo means your career path is about visibility, creativity, and inspiring others. Entertainment, creative direction, teaching, leadership, or anything that puts you in the spotlight. You're meant to be seen doing your life's work. Don't hide.",
  Virgo: "Your Midheaven in Virgo means your career path is about service, mastery, and making things work better. Health, wellness, editing, consulting, organisation, or anything that lets you solve problems with precision. You're meant to be the expert people trust with the details.",
  Libra: "Your Midheaven in Libra means your career path is about beauty, justice, and bringing people together. Law, design, art curation, diplomacy, mediation, or anything that creates harmony. You're meant to make the world more beautiful and fair through your work.",
  Scorpio: "Your Midheaven in Scorpio means your career path is about transformation, investigation, and power. Psychology, research, finance, healing work, or anything that goes beneath the surface. You're meant to do work that fundamentally changes people or systems.",
  Sagittarius: "Your Midheaven in Sagittarius means your career path is about expansion, education, and inspiring global thinking. Publishing, travel, teaching, philosophy, international business, or anything that broadens horizons. You're meant to show people what's possible beyond their current worldview.",
  Capricorn: "Your Midheaven in Capricorn means your career path is about authority, legacy, and building something that lasts. CEO energy. Government, architecture, corporate leadership, or anything that requires discipline and long-term vision. You're meant to be at the top.",
  Aquarius: "Your Midheaven in Aquarius means your career path is about innovation, social change, and the future. Technology, humanitarian work, science, community building, or anything that disrupts the status quo. You're meant to change how things work.",
  Pisces: "Your Midheaven in Pisces means your career path is about creativity, healing, and spiritual work. Art, music, film, therapy, spirituality, or anything that connects people to something transcendent. You're meant to create work that makes people feel things they can't explain.",
};

export const MERCURY_READINGS: Record<string, string> = {
  Aries: "Mercury in Aries means your mind is fast, direct, and fearless. You think quickly, speak bluntly, and have zero patience for small talk. You're brilliant at making decisions under pressure. Your communication style is bold and your ideas come in like lightning bolts.",
  Taurus: "Mercury in Taurus means your mind is methodical, practical, and sensory. You think things through slowly and thoroughly. Your voice is probably beautiful. You communicate with weight and substance. When you speak, people listen because you've actually thought about it.",
  Gemini: "Mercury is in its home sign, making you one of the most naturally gifted communicators of the zodiac. Your mind moves at light speed. You're witty, versatile, and can talk your way into or out of anything. You process the world through conversation and ideas.",
  Cancer: "Mercury in Cancer means your thinking is deeply intuitive and emotionally intelligent. You remember how things made you feel more than what was said. Your communication style is warm and nurturing. You have a gift for making people feel understood.",
  Leo: "Mercury in Leo means your communication style is dramatic, warm, and theatrical. You're a natural storyteller. When you speak, people are captivated. Your ideas are big and your delivery is bigger. You think with your heart as much as your head.",
  Virgo: "Mercury is in its home sign, making your mind razor-sharp, analytical, and brilliantly precise. You see patterns and details that everyone else misses. Your communication is clear, intelligent, and efficient. You're the person who actually reads the fine print.",
  Libra: "Mercury in Libra means your mind seeks balance, beauty, and fairness in everything. You're diplomatic in communication and consider every perspective before speaking. You have a gift for mediating conflict and your writing is naturally elegant.",
  Scorpio: "Mercury in Scorpio means your mind is investigative, penetrating, and impossible to fool. You think beneath the surface. You hear what people aren't saying. Your communication is powerful, strategic, and cuts straight to the truth that everyone else is dancing around.",
  Sagittarius: "Mercury in Sagittarius means your mind is expansive, philosophical, and always chasing the bigger picture. You think in concepts, not details. Your communication is enthusiastic, honest, and occasionally tactless. You're brilliant at seeing connections others miss.",
  Capricorn: "Mercury in Capricorn means your mind is structured, strategic, and incredibly disciplined. You think long-term and communicate with authority. Your words carry weight because you never speak without purpose. You're brilliant at turning abstract ideas into concrete plans.",
  Aquarius: "Mercury in Aquarius means your mind is innovative, unconventional, and years ahead of everyone else. You think in systems and see the future clearly. Your ideas are radical and your communication style is detached but brilliant. You're the person having the ideas everyone will adopt in ten years.",
  Pisces: "Mercury in Pisces means your mind is intuitive, creative, and connected to something beyond logic. You think in images, feelings, and metaphors. Your communication style is poetic and imaginative. You might struggle with practical details but your creative vision is extraordinary.",
};
