// A fuller, practical paragraph for each of the 64 gates: what the gate actually is
// and how its energy works. Sits alongside GATE_CONTENT (keynote / shadow / gift) so
// the chart page can explain every one of a member's own gates in real depth, not just
// a keynote. Kept in its own file so the gate section can grow without touching the
// shared gate-content or page files.

export const GATE_DESCRIPTION: Record<number, string> = {
  1: "The gate of self-expression and creative power. When activated, you have a deep drive to express your unique creative identity. This is the energy of the individual who creates because creation is their nature.",
  2: "The gate of the direction of the Self. This is the driver that holds your direction in life, and it works through receptivity, letting direction come to you rather than forcing it.",
  3: "The gate of ordering, the energy to bring something new into form. It is fuel for innovation and change, carrying the pressure to begin, and it needs the right timing so beginning does not tip into chaos.",
  4: "The gate of formulization, the mental pressure to find answers and solutions. This is the logical mind building models to understand life, and it lands best when the answer is recognised rather than pushed.",
  5: "The gate of fixed rhythms and universal patterns. This energy attunes you to natural timing and cycles. When you honour your rhythm, life flows; when it is disrupted, everything feels off.",
  6: "The gate of friction and emotional depth, the gateway to intimacy. It governs when and with whom you open up, moving through an emotional wave that asks for patience before clarity.",
  7: "The gate of the role of the Self, the energy of democratic leadership. This is guiding by pointing the way and leading through example and direction rather than force.",
  8: "The gate of contribution, the voice that knows it can make a real contribution. This is your individual creative expression reaching the world through the Throat.",
  9: "The gate of focus, deep determination and attention to detail. This energy lets you concentrate persistently on the small things that build mastery.",
  10: "The gate of the behaviour of the Self, self-love and living life as yourself. At its healthiest it is natural empowerment and self-acceptance, and it connects into three different channels.",
  11: "The gate of ideas, a wealth of concepts and stimulating thoughts. This is a peaceful, idea-rich gate whose ideas are meant to be shared and to stimulate others rather than all acted on.",
  12: "The gate of caution, individual expression delivered with social timing. It knows when to speak and when to stay quiet, and it can be profoundly moving when the mood is right.",
  13: "The gate of the listener, the one who holds space for other people's stories and secrets. This is the keeper of collective memory, able to hear and hold without judgement.",
  14: "The gate of power skills, the energy of abundance and material resource. This is the fuel behind your capacity to build wealth through skill and competence.",
  15: "The gate of extremes, love of humanity expressed through rhythm. It swings between different patterns and tempos and is deeply tied to the flow of collective human rhythms.",
  16: "The gate of skills, enthusiasm and experimentation on the way to mastery. You try many things before finding what to master, so depth arrives through breadth of experience.",
  17: "The gate of opinions, the logical mind forming views and frameworks. It organises information into patterns, and its opinions become valuable once they are invited and tested.",
  18: "The gate of correction, the intuitive drive to improve and perfect. It spots what needs fixing with real precision, and it works best when the correction is invited.",
  19: "The gate of wanting, deep sensitivity to what others need and to belonging. This tribal energy senses what a community requires and moves you to provide it.",
  20: "The gate of the now, pure presence and awareness in the moment. It speaks and acts from immediate knowing and is part of the Integration circuit, connecting into three channels.",
  21: "The gate of the hunter, the willpower to run your own material world. This heart energy needs to be in charge of its own domain and resources.",
  22: "The gate of openness, emotional grace in how you meet people. In the right mood it is deeply charming and expressive; its timing rides your emotional wave.",
  23: "The gate of assimilation, the voice that translates deep individual knowing into simple expression. Its insights can sound radical, and being understood is usually a matter of timing.",
  24: "The gate of rationalization, the mind that returns to a thought again and again. This is the reviewing mind that revisits an idea until it finally yields something.",
  25: "The gate of the spirit of the Self, universal love and innocence. It is unconditional love that flows through you with nothing to prove.",
  26: "The gate of the trickster, the energy of the great salesman. This is tribal ego used to influence and convince, at its best the power of great storytelling in service of others.",
  27: "The gate of caring, the sacral energy to nurture and nourish. This is deep tribal care that sustains a community, and its lesson is knowing when to stop giving.",
  28: "The gate of the game player, the drive to find purpose and meaning through struggle. It pushes you to take risks and fight for what matters, wary of a life without meaning.",
  29: "The gate of perseverance, the sacral power of saying yes and committing fully. It carries devotion and follow-through, so the whole art is being selective about what you say yes to.",
  30: "The gate of the recognition of feelings, the fire of desire and longing. It yearns for new experiences and drives you toward them, moving through an emotional wave.",
  31: "The gate of leading, the voice of democratic leadership that guides the collective. Your words carry natural authority once you wait to be recognised.",
  32: "The gate of continuity, the splenic instinct for what will last. It senses which transformations are worth pursuing and which ventures will endure.",
  33: "The gate of privacy, the energy of retreat and reflection. It steps back from experience to process and remember, sharing the wisdom once perspective is gained.",
  34: "The gate of power, pure sacral strength. This is enormous energy for doing, meant to be used in response, and it connects into three channels.",
  35: "The gate of change, the hunger for the full range of life's experiences. This is jack-of-all-trades energy that grows through variety and progress.",
  36: "The gate of crisis, growth through emotional depth and turbulence. It is drawn to intensity as a path to growth, moving toward humanity and compassion on the other side.",
  37: "The gate of friendship and family, the emotional bonds that hold a group together. It runs on the agreements and loyalty within your closest circle.",
  38: "The gate of the fighter, the individual spirit that struggles to find meaning. This root pressure drives you to fight for what personally matters, even against opposition.",
  39: "The gate of provocation, the root pressure that stirs spirit in others. It tests and prods to find what is genuinely worth feeling passionate about.",
  40: "The gate of aloneness, the willpower to provide while needing solitude. It makes the bargain: I will provide, and I need my alone time to recover.",
  41: "The gate of contraction, the root pressure of fantasy and imagination. It is the spark of human experience, dreaming up new feelings and possibilities before they arrive.",
  42: "The gate of growth, the sacral energy of completion. It is about finishing what you start and finding fulfilment in seeing a cycle all the way through.",
  43: "The gate of insight, the breakthrough knowing of the individual mind. This is inner hearing and unique perception, brilliant even when it sounds unconventional.",
  44: "The gate of coming to meet, the splenic alertness to patterns from the past. It recognises what has worked before and senses whether conditions now are favourable.",
  45: "The gate of the gatherer, the voice of material authority. This is the queen energy that naturally draws resources and people together and distributes them.",
  46: "The gate of the love of the body, physical serendipity and being in the right place at the right time. Success here comes through embodiment and presence.",
  47: "The gate of realization, the mental pressure to make sense of experience. It finds meaning in the seemingly random, turning the past into understanding.",
  48: "The gate of depth, the intuitive well of knowledge. It carries a fear of inadequacy that drives you toward real depth, and it becomes resourcefulness when trusted.",
  49: "The gate of principles, the emotional power of revolution. This tribal gate holds the principles that decide what is accepted, and it fuels necessary change when values are crossed.",
  50: "The gate of values, the splenic awareness of responsibility and care for the group. It holds the values that protect and preserve a community.",
  51: "The gate of shock, the competitive spirit that initiates through a jolt. It can take and deliver shock, the warrior energy that springs into action and tests its own courage.",
  52: "The gate of stillness, the root pressure to concentrate. It brings focused stillness, the ability to sit with pressure without acting on it.",
  53: "The gate of beginnings, the root pressure to start new cycles. It always wants to begin something, and its maturation comes through learning to complete.",
  54: "The gate of ambition, the root drive to rise and transform. This tribal energy fuels the climb toward material and social advancement.",
  55: "The gate of spirit, emotional abundance and depth of feeling. It reaches the full range from melancholy to ecstasy and carries the potential for a new kind of emotional freedom.",
  56: "The gate of stimulation, the voice of the storyteller. It stimulates through stories and belief, engaging people with what could be.",
  57: "The gate of intuition, the most immediate form of awareness there is. This splenic gate gives instant, in-the-moment knowing about safety and timing, and it speaks softly, once.",
  58: "The gate of vitality, the joyful root pressure behind the love of life. It sees what could be better and has the energy to pursue the improvement.",
  59: "The gate of sexuality, the sacral power that breaks down barriers to create intimacy. It is the creative force that dissolves the walls between people.",
  60: "The gate of limitation, the root pressure that turns constraint into transcendence. Change happens within limits, pulsing between restriction and release.",
  61: "The gate of mystery, the mental pressure to know the unknowable. This head-centre gate drives you to understand the deepest questions of existence.",
  62: "The gate of details, expression through precise naming. This logical energy communicates by labelling things accurately and organising understanding.",
  63: "The gate of doubt, the logical pressure to question and test. This is healthy scepticism that demands proof and drives real investigation.",
  64: "The gate of confusion, the mental pressure to make sense of the past. The abstract mind processes memories into meaning, and clarity arrives once the whole cycle completes.",
};
