// Real member quotes, supplied by Betty 2 Oct 2026 (with permission). Keyed by first name so pages
// can pick the quote that fits the section it sits in. First name + initial only.
export interface MemberQuote {
  name: string;
  quote: string;
}

export const MEMBER_QUOTES: Record<string, MemberQuote> = {
  sophie: { name: "Sophie M.", quote: "I genuinely can't believe MY SZN is $88 a month. I've paid hundreds for courses that gave me nowhere near this level of support. The group coaching alone is worth it for me, but then I'm getting the personalised astrology, tapping, hypnosis and community too. It feels much more like being inside a coaching programme than a membership." },
  maya: { name: "Maya T.", quote: "I had my first 10k month after doing the money and visibility work inside MY SZN. The biggest shift was realising I didn't need another business strategy, I needed to look at why I kept hiding every time I wanted to grow. I worked through that in the workshop and started showing up completely differently in my business." },
  jade: { name: "Jade R.", quote: "I finally raised my prices after putting it off for nearly a YEAR. I'd convinced myself it was a practical business decision, but the shadow work made me realise how much of it was actually about worth and being scared people would say no. I raised them anyway and signed two clients at the new price that month." },
  priya: { name: "Priya N.", quote: "I came for the astrology and stayed because I'm actually changing my life 😂 Having MY astrology and Human Design personalised to me is incredible, but I love that Betty doesn't let us stop at knowing ourselves. Every SZN we're taking what we know and actually doing something with it." },
  chloe: { name: "Chloe B.", quote: "The relationship work completely changed what I realised I'd been tolerating. I set a boundary I'd avoided for YEARS because I was terrified of upsetting someone, and the world did not end 😂 I'm communicating differently now, asking for what I need and noticing immediately when I'm about to abandon myself to keep someone else happy." },
  lauren: { name: "Lauren S.", quote: "I BOOKED THE TRIP. Three years of saying I wanted to travel solo and finding approximately 900 reasons why now wasn't the right time 😂 I mentioned it in the community, everyone encouraged me, and eventually I realised I was literally waiting for someone to give me permission. So I booked it." },
  aisha: { name: "Aisha R.", quote: "The community is probably the thing I didn't realise I needed. There's something about watching other women raise their prices, leave situations they've outgrown, book trips, launch things and go after massive goals that makes staying in your own comfort zone increasingly difficult 😂 Everyone genuinely wants to see each other win." },
  georgia: { name: "Georgia L.", quote: "The biggest change for me is that I trust myself. I used to ask EVERYONE what they thought before making a decision and then still overthink it for another week. The coaching and identity work have made me so much more decisive. I'm making moves now that old me would have spent six months thinking about." },
  hannah: { name: "Hannah J.", quote: "I've bought so many manifestation courses where I've consumed all the information and then changed absolutely nothing. MY SZN has been different because we're actually doing the work. I've stopped treating manifestation like something I'm waiting to happen and started looking at my choices, beliefs, habits and the person I'm becoming." },
  amelia: { name: "Amelia K.", quote: "The hypnosis has surprised me the most. I started listening consistently during the SZN and noticed I was responding differently to situations that would normally send me straight into self-doubt. It wasn't this huge dramatic overnight moment. I just suddenly realised one day that I wasn't behaving like the old version of me anymore." },
  danielle: { name: "Danielle C.", quote: "I came into group coaching completely stuck over a career decision I'd been going backwards and forwards on for months. Betty asked me about three questions and suddenly I could see EXACTLY what I was doing 😂 I left knowing what I wanted, made the decision that week and honestly felt about 20kg lighter." },
  zara: { name: "Zara K.", quote: "My 90-day intention was to stop saying I wanted a different life while continuing to make exactly the same choices. I've changed jobs, started earning more, become more visible and finally started a project I'd talked about for nearly two years. Seeing it all written down at the end of the 90 days was actually quite emotional because I hadn't realised how much had changed." },
};
