import type { BankBlock } from "./types";

/**
 * Pricing profiles. The derivation module (facts.ts) assigns exactly one to every
 * chart, so this set is exhaustive by design. Feeds the "Your pricing profile"
 * section. Keys are the profile id.
 */
export const PRICING_PROFILES: Record<string, BankBlock> = {
  "apologetic-discounter": {
    label: "The Apologetic Discounter",
    body: `Watch the exact moment your money leaks out. You get to your price, you say the number, and then you keep talking, adding the justification and the small apologetic wince and the offer to be flexible, all of it arriving before the client has so much as blinked or raised a single objection, so you end up discounting against resistance that never showed up and, far more often than you would believe, was never coming at all. That client in front of you was completely ready to pay the figure you first named, and the only person who talked them down from it, gently and thoroughly and entirely on their own, was you. What is really happening there has very little to do with pricing and almost everything to do with your nervous system, because the silence that opens up after you say a number lands in your body as an emergency you personally have to rush in and fix, so you fill it, and the thing you fill it with is money lifted straight off your own invoice. Your remedy is mechanical long before it is emotional, and it goes like this: say the number, close your mouth, and let the silence sit there belonging entirely to the client until the client is the one who breaks it, which will feel unbearable for about four seconds, and waiting on the far side of those four seconds is the rate you actually meant to charge. Price from the woman who already knows what she is worth, not the version of you that is scared of being called too expensive.`,
    action: `On your next quote, say the number and then say nothing at all until the other person speaks first, and leave the gap completely alone no matter how long it stretches out.`,
  },
  "premium-anchor": {
    label: "The Premium Anchor",
    body: `You anchor high, and you do it without flinching, because somewhere in your chart is a placement that simply does not experience a large number as frightening. You name the top-of-market figure, you let it sit, and you watch clients say yes to the rate that makes your peers go pale, because your certainty does most of the selling before you have even finished the sentence. This is a genuine gift, and it is worth understanding as one rather than assuming everyone could do it. The place it can cost you is that unshakeable confidence occasionally outruns the delivery, so you sell the premium promise and then have to scramble to build the premium thing behind it, and you can price out the aligned client who would have grown into your best case study while chasing only the ones who can pay top dollar today. Your work is to keep anchoring high while making sure the experience you deliver has caught up to the number you are so comfortable naming, and to leave one door open for the right person who is not yet at the top of the market.`,
    action: `Audit one premium offer this week and make sure the delivery genuinely matches the price, upgrading the experience before you raise the rate again.`,
  },
  "generous-overdeliverer": {
    label: "The Generous Over-Deliverer",
    body: `You price low and then give far more than the price ever asked for, packing in the extra call and the bonus and the after-hours reply until the client receives something worth several times what they paid. Your generosity is real and your clients adore you for it, and word of mouth is often your best marketing precisely because nobody has ever once felt short-changed by you. That devotion to over-delivering is a genuine strength when it is a choice rather than a compulsion. The trouble is that it is usually a compulsion, because you over-deliver when some part of you does not quite believe the base price was deserved, so you keep topping it up with free labour until the maths quietly stops working and you are exhausted and underpaid by your own most loyal clients. The generosity becomes the apology. Your work is to raise the price until it matches what you already deliver, and then to stop adding, because the value lives in the work itself, not in how much of yourself you give away for free on top of it.`,
    action: `Take one thing you currently throw in for free, name its real worth, and either charge for it or deliberately remove it this week.`,
  },
  "values-pricer": {
    label: "The Values Pricer",
    body: `You price through the lens of fairness, wanting the exchange to feel good and balanced for everyone in it, and you have a real gift for building the kind of pricing that makes clients feel respected rather than squeezed. Relationships and reputation compound beautifully for you because people trust that you will never overcharge them, and that trust is worth more over a whole career than any single inflated invoice could ever be. The trap is that your definition of fair quietly tilts against you, so you leave money on the table in the name of everyone winning, hesitate to charge what the market easily bears because it feels greedy, and end up subsidising clients who would happily have paid more. Fairness starts flowing in only one direction. Your work is to remember that a price which is fair to the client and unfair to you is simply unfair, and to let your own worth sit on the scale with the same weight you so generously give to everyone else's.`,
    action: `Find one price you set low to be fair and raise it to the figure that is genuinely fair to you as well, this week.`,
  },
  "all-or-nothing-pricer": {
    label: "The All-or-Nothing Pricer",
    body: `You price in extremes, either charging a premium that reflects the full intensity of what you bring or doing the whole thing for nothing because you believe in the person, with very little comfortable middle ground in between. When you are properly paid you deliver with a depth and commitment most people cannot match, and your capacity to go all in is a genuine and magnetic gift. The trap is that the same intensity makes pricing feel personal, so a client who negotiates can land like a betrayal, you swing between over-giving and sudden walls, and the free work you took on out of belief quietly breeds a resentment that poisons the relationship. The middle you keep skipping is exactly where sustainable business actually lives. Your work is to build a calm, consistent, middle-range offer that does not require you to either fall in love or feel used, so your income stops depending on the emotional temperature of each individual deal.`,
    action: `Create one steady mid-tier offer this week priced from strategy rather than passion, and sell it to someone you feel completely neutral about.`,
  },
  "scarcity-pricer": {
    label: "The Scarcity Pricer",
    body: `You price with one eye always on the fear of losing the client, so you keep your rates low enough to feel safe, work harder than anyone to justify them, and compete on being the affordable, reliable, never-quite-expensive option. Your diligence is real and clients trust that you will always show up, which is a genuine foundation for a long career. The trap is that pricing from the fear of loss tends to guarantee the loss anyway, because you fill your time with low-paying work, keep no room for the better clients when they finally arrive, and slowly burn out proving your worth to people who chose you for being cheap. The scarcity you are bracing against becomes the scarcity you build. Your work is to raise your rates before you feel ready and to trust that the right clients value you more when you visibly value yourself, because a price set from fear will always leave you overworked and underpaid.`,
    action: `Raise your rate for the next new client by a meaningful step and let yourself feel the fear without lowering it back down.`,
  },
  "moody-pricer": {
    label: "The Moody Pricer",
    body: `You price by feel, and your feel changes, so on a day you feel safe and full you name a strong, confident number, and on a day you feel wobbly or unseen you quietly quote less for the very same work. Your sensitivity is a real gift in the room, because you read what a client needs before they have said it, and that attunement is a large part of why people love working with you. The trap is that letting your inner weather set your prices makes your income unpredictable and your worth negotiable by your own moods, so two clients end up paying wildly different amounts for the same thing and the gap has nothing to do with either of them. The tide sets the rate instead of the value. Your work is to decide your prices once, in advance, on a steady day, and to write them down somewhere you cannot quietly rewrite them the next time you are having a hard morning.`,
    action: `Set your core prices in writing this week on a good day, and commit to quoting from that list regardless of how you feel when the next enquiry lands.`,
  },
  justifier: {
    label: "The Justifier",
    body: `You price competently and then you explain it, and explain it, layering on the reasoning and the breakdown and the itemised list of everything the client is getting, because some part of you believes a number is not allowed to simply stand on its own. Your thoroughness is genuine and it can reassure the right client, the sort who likes to understand exactly what they are paying for. The trap is that over-explaining a price quietly signals that you are not sure of it yourself, so the very words meant to justify the number are the ones that talk the client into doubting it, and the more you say the smaller the figure starts to sound. The explanation becomes the leak. Your work is to state the price in one clean sentence and then stop talking, because a number delivered with calm brevity reads as far more confident than the same number buried under three paragraphs of reasons nobody actually asked for.`,
    action: `On your next quote, give the price and a single sentence of context at most, then let the silence do the rest without adding another word.`,
  },
  "invisible-pricer": {
    label: "The Invisible Pricer",
    body: `You would honestly rather do almost anything than state your price plainly, so you go vague, defer to the client's budget, say something like whatever feels right to you, and hope the number sorts itself out without you ever having to name it out loud. Your flexibility can feel gracious and unattached, and there is a real generosity of spirit underneath it. The trap is that a price nobody names is a price nobody respects, so you attract clients who happily fill the vagueness with the lowest figure they can find, you undersell without ever deciding to, and the discomfort you avoided by staying quiet arrives later as resentment and unpaid worth. The fog protects you from the ask and quietly costs you the income. Your work is to name a specific, spoken, unmistakable number, out loud or in writing, because a clear price is a form of self-respect that the right clients will actually find reassuring rather than off-putting.`,
    action: `Put an actual figure on your next proposal, specific and written down, instead of inviting the client to suggest one.`,
  },
  "ambition-pricer": {
    label: "The Ambition Pricer",
    body: `You price with the long game in mind, raising your rates deliberately as your reputation and your results grow, and treating your pricing as a ladder you climb rather than a number you are stuck with. This is a genuinely sophisticated instinct, because you understand that price signals status and that moving up-market is a strategy rather than an act of greed, and over a career it compounds into real authority. The trap is that the same patience can tip into waiting too long, so you keep charging the rate that matched who you were three years ago, delay each raise until it is well overdue, and quietly subsidise clients who are paying yesterday's price for today's expertise. The strategic climb stalls on the rung marked later. Your work is to raise your rates on the schedule your growth has already earned, rather than the one your caution keeps postponing, because the market has usually moved you up long before you give yourself permission to move.`,
    action: `Name the rate your current results actually justify, compare it to what you charge now, and close part of that gap with your next client this week.`,
  },
  "rebel-pricer": {
    label: "The Rebel Pricer",
    body: `You price on your own terms and refuse to do it the way the industry insists you must, experimenting with flat fees and unusual models and structures nobody else in your field would dare to try. Your originality is real and it can genuinely set you apart, because the right client is drawn to the person brave enough to reinvent the whole exchange rather than copy everyone else's rate card. The trap is that rejecting the norm can quietly mean rejecting the money, so you build the brilliant unconventional model and forget to check whether it actually pays you, price to prove a point rather than to profit, and under-monetise your best innovation because charging properly for it feels too conventional. The rebellion ends up costing you the reward. Your work is to keep the originality while running the plain, boring numbers underneath it, because a pricing model is only truly radical if it also, quietly, makes you well paid.`,
    action: `Take your most unconventional offer this week and run the actual maths on what it earns you per hour, then adjust it so the innovation also pays.`,
  },
  "worth-wound-pricer": {
    label: "The Worth-Wound Pricer",
    body: `For you, stating a price touches something far older and more tender than business, because somewhere your sense of what you are worth got wounded early, and the number you have to say out loud presses directly on that bruise. When you have done the inner work, this same depth becomes a rare and powerful thing, because you price from hard-won self-knowledge rather than bravado, and clients feel the difference in the quiet steadiness of it. The trap is that until then the wound sets the rate, so your body freezes at the moment of the ask, you quote low to avoid the exposure of wanting more, and you read a client's ordinary hesitation as proof of the very unworthiness you already feared. The old injury does the pricing. Your work is slow and it is real, to separate the number from the wound one quote at a time, and to keep practising a figure that reflects your actual worth even while the old story insists it is far too much.`,
    action: `Choose a price that feels slightly beyond comfortable, say it out loud to yourself ten times until the charge softens, then use it with your next client.`,
  },
};
