// The product catalogue for Shop Your Szn.
//
// Real products from ASOS US, curated by hand and tagged into the same 0-100 vector space as the
// signs, so the engine ranks them per member rather than showing everyone the same grid. Each
// product carries the seasons it belongs to, so an edit can be pre-prepared per zodiac season.
//
// THREE THINGS TO KNOW BEFORE THIS GOES LIVE
// 1. These are plain retailer links, so they earn nothing yet. Wrap them through an affiliate
//    network (Awin covers ASOS, Amazon has its own programme) and put the tag in affiliateWrap()
//    below, which is the single place every outbound link passes through.
// 2. Prices and stock go stale. Each product records checkedAt, and the UI should either hide the
//    price or label it as the price when the edit was built. Refresh at the start of each season.
// 3. Images are deliberately not hotlinked from the retailer. An affiliate feed supplies licensed
//    image URLs, which is the correct source for them.

import { vec, type Sign, type StyleVector } from "./types";

export type Category =
  | "tops"
  | "bottoms"
  | "dresses"
  | "outerwear"
  | "shoes"
  | "bags"
  | "jewellery"
  | "activewear";

export interface Product {
  id: string;
  title: string;
  brand: string;
  retailer: "ASOS";
  category: Category;
  /** Price in USD at the time the edit was built. */
  price: number;
  url: string;
  colours: string[];
  /** Zodiac seasons this piece belongs in. */
  seasons: Sign[];
  vector: StyleVector;
  /** Tags the engine can downrank against, matching the rising/venus downrank vocabularies. */
  attributes: string[];
  /** Retailer image, where one has been captured. Optional on purpose: licensed image URLs arrive
   *  with the affiliate feed, and until then the UI falls back to a colour tile rather than a
   *  broken photo. */
  image?: string;
  checkedAt: string;
}

const CHECKED = "2026-08-30";

const p = (
  id: string,
  title: string,
  brand: string,
  category: Category,
  price: number,
  url: string,
  colours: string[],
  seasons: Sign[],
  vector: Partial<StyleVector>,
  attributes: string[] = []
): Product => ({
  id, title, brand, retailer: "ASOS", category, price, url, colours, seasons,
  vector: vec(vector), attributes, checkedAt: CHECKED,
});

// Product images captured alongside the curation. Keyed by product id so the catalogue entries stay
// readable, and so a feed can replace this wholesale later.
const IMAGES: Record<string, string> = {
  "monki-wide-tailored-gray": "monki-high-waist-wide-leg-tailored-pants-in-dark-gray-melange/207969313-1-grey",
  "jdy-wide-chocolate": "jdy-wide-leg-tailored-pants-in-chocolate-brown/209448608-1-brown",
  "asos-peplum-shell-brown": "asos-design-linen-blend-tailored-peplum-shell-top-in-brown-part-of-a-set/210140965-1-brown",
  "other-stories-poplin-blue": "other-stories-pure-cotton-poplin-shirt-with-back-tie-detail-in-light-blue/210373840-1-lightblue",
  "asos-cinch-mocha": "asos-design-cinch-waist-blazer-in-mocha/209074015-1-mocha",
  "asos-funnel-chocolate": "asos-design-faux-leather-funnel-neck-jacket-in-chocolate-brown/210194842-1-brown",
  "asos-reign-platform-mocha": "asos-design-reign-square-toe-mid-heel-platform-boots-in-mocha-suedette/208592493-1-mochasuedette",
  "asos-linen-wide-cream": "asos-design-linen-blend-wide-leg-pants-with-pleated-detailing-in-cream/209846937-1-cream",
  "asos-evelyn-platform-tan": "asos-design-evelyn-platform-heeled-ankle-boots-in-tan/208592768-1-tanpu",
  "asos-rib-slash-chocolate": "asos-design-rib-slash-neck-shoulder-seam-mini-dress-in-chocolate/210801014-1-chocolate",
  "asos-curve-twill-wide-chocolate": "asos-design-curve-cotton-twill-wide-leg-pants-in-chocolate/210005274-1-chocolate",
};

/** Full image URL at a sensible width, or null when this product has no captured image yet. */
export function productImage(id: string, width = 320): string | null {
  const path = IMAGES[id];
  return path ? `https://images.asos-media.com/products/${path}?$n_${width}w$` : null;
}

export const PRODUCTS: Product[] = [
  // ── bottoms ──────────────────────────────────────────────────────────────────
  p("monki-wide-tailored-gray", "High waist wide leg tailored pants in dark gray melange", "Monki", "bottoms", 51,
    "https://www.asos.com/us/monki/monki-high-waist-wide-leg-tailored-pants-in-dark-gray-melange/prd/207969313",
    ["dark gray"], ["Virgo", "Capricorn", "Aquarius"],
    { structure: 88, minimal: 82, polished: 80, classic: 78, casual: 35, printIntensity: 5, colourIntensity: 20 }),
  p("jdy-wide-chocolate", "Wide leg tailored pants in chocolate brown", "JDY", "bottoms", 51,
    "https://www.asos.com/us/jdy/jdy-wide-leg-tailored-pants-in-chocolate-brown/prd/209448608",
    ["chocolate"], ["Virgo", "Taurus", "Capricorn"],
    { structure: 85, minimal: 75, polished: 78, classic: 82, texture: 60, colourIntensity: 30 }),
  p("princess-polly-flared-black", "Mid rise slim fit button detail flared tailored pants in black", "Princess Polly", "bottoms", 64,
    "https://www.asos.com/us/princess-polly/princess-polly-kinkirk-mid-rise-slim-fit-button-detail-flared-tailored-pants-in-black/prd/208491339",
    ["black"], ["Scorpio", "Capricorn", "Leo"],
    { structure: 80, bodyConscious: 72, polished: 82, sensual: 60, colourIntensity: 15, edge: 55 }),
  p("topshop-sequin-white", "Sequined tailored pants in white", "Topshop", "bottoms", 85,
    "https://www.asos.com/us/topshop/topshop-sequined-tailored-pants-in-white/prd/209319577",
    ["white", "silver"], ["Leo", "Aquarius", "Gemini"],
    { glamour: 90, maximal: 85, futuristic: 70, structure: 65, minimal: 20, texture: 75 }),
  p("asos-mesh-midi-chocolate", "Mesh low rise midi skirt with godets in chocolate", "ASOS DESIGN", "bottoms", 37.99,
    "https://www.asos.com/us/asos-design/asos-design-mesh-low-rise-midi-skirt-with-godets-in-chocolate/prd/210953754",
    ["chocolate"], ["Pisces", "Taurus", "Scorpio"],
    { fluidity: 85, sensual: 75, texture: 70, structure: 25, romantic: 65 }),
  p("asos-linen-slip-skirt-red", "Linen blend 90s slip skirt in red", "ASOS DESIGN", "bottoms", 47.99,
    "https://www.asos.com/us/asos-design/asos-design-linen-blend-90s-slip-skirt-in-red/prd/211004916",
    ["red"], ["Aries", "Leo", "Sagittarius"],
    { colourIntensity: 90, fluidity: 65, sensual: 65, casual: 55, edge: 55 }),
  p("topshop-techy-90s-black", "Techy 90s length skirt in black", "Topshop", "bottoms", 48,
    "https://www.asos.com/us/topshop/topshop-techy-90s-length-skirt-in-black/prd/211358217",
    ["black"], ["Aquarius", "Scorpio", "Capricorn"],
    { futuristic: 80, edge: 70, minimal: 70, structure: 65, colourIntensity: 15 }),
  p("topshop-organza-gray", "Organza 90s length skirt in gray", "Topshop", "bottoms", 50,
    "https://www.asos.com/us/topshop/topshop-organza-90s-length-skirt-in-gray/prd/210941663",
    ["gray"], ["Pisces", "Aquarius", "Libra"],
    { fluidity: 85, texture: 75, romantic: 70, experimental: 60, structure: 30 }),

  // ── tops ─────────────────────────────────────────────────────────────────────
  p("jjxx-poplin-olive", "Jamie oversized striped poplin shirt in olive", "JJXX", "tops", 45,
    "https://www.asos.com/us/jjxx/jjxx-jamie-oversized-striped-poplin-shirt-in-olive/prd/210992027",
    ["olive"], ["Virgo", "Sagittarius", "Taurus"],
    { oversized: 78, casual: 70, printIntensity: 55, classic: 65, structure: 55 }),
  p("other-stories-poplin-blue", "Pure cotton poplin shirt with back tie detail in light blue", "& Other Stories", "tops", 125,
    "https://www.asos.com/us/other-stories/other-stories-pure-cotton-poplin-shirt-with-back-tie-detail-in-light-blue/prd/210373840",
    ["light blue"], ["Virgo", "Cancer", "Libra"],
    { polished: 88, minimal: 78, classic: 80, structure: 70, romantic: 55 }),
  p("jjxx-poplin-pink-green", "Jamie oversized poplin shirt in pink and green stripes", "JJXX", "tops", 45,
    "https://www.asos.com/us/jjxx/jjxx-jamie-oversized-poplin-shirt-in-pink-and-green-stripes/prd/210407063",
    ["pink", "green"], ["Gemini", "Libra", "Aries"],
    { printIntensity: 85, colourIntensity: 75, casual: 72, oversized: 70 }, ["clashing_print"]),
  p("mango-fine-knit-burgundy", "Round neck fine knit sweater in burgundy", "Mango", "tops", 69.99,
    "https://www.asos.com/us/mango/mango-round-neck-fine-knit-sweater-in-burgundy/prd/211550404",
    ["burgundy"], ["Scorpio", "Taurus", "Capricorn"],
    { texture: 80, minimal: 72, classic: 78, sensual: 62, bodyConscious: 62, colourIntensity: 45 }),
  p("gina-fine-knit-brown", "Long sleeve crew neck fine knit sweater in brown melange", "Gina Tricot", "tops", 63,
    "https://www.asos.com/us/gina-tricot/gina-tricot-long-sleeve-crew-neck-fine-knit-sweater-in-brown-melange-part-of-a-set/prd/209524942",
    ["brown"], ["Taurus", "Virgo", "Capricorn"],
    { texture: 82, minimal: 78, classic: 80, casual: 55, colourIntensity: 25 }),
  p("asos-knit-poplin-collar-gray", "Fine knit sweater with contrast poplin collar in gray", "ASOS DESIGN", "tops", 59.99,
    "https://www.asos.com/us/asos-design/asos-design-fine-knit-sweater-with-contrast-poplin-collar-in-gray/prd/210356570",
    ["gray"], ["Virgo", "Capricorn", "Gemini"],
    { polished: 85, classic: 78, minimal: 70, structure: 62 }),
  p("gina-metallic-knit-dark-brown", "Metallic fine knit sweater with wide sleeves in dark brown", "Gina Tricot", "tops", 63,
    "https://www.asos.com/us/gina-tricot/gina-tricot-metallic-fine-knit-sweater-with-wide-sleeves-in-dark-brown/prd/209572449",
    ["dark brown", "metallic"], ["Leo", "Aquarius", "Taurus"],
    { glamour: 78, texture: 80, futuristic: 60, oversized: 62, colourIntensity: 45 }),

  // ── outerwear ────────────────────────────────────────────────────────────────
  p("asos-cinch-mocha", "Cinch waist blazer in mocha", "ASOS DESIGN", "outerwear", 99.99,
    "https://www.asos.com/us/asos-design/asos-design-cinch-waist-blazer-in-mocha/prd/209074015",
    ["mocha"], ["Virgo", "Taurus", "Libra"],
    { structure: 88, polished: 88, classic: 78, bodyConscious: 68, texture: 60 }),
  p("asos-sculpted-plum", "Ultimate sculpted suit blazer in plum", "ASOS DESIGN", "outerwear", 119,
    "https://www.asos.com/us/asos-design/asos-design-ultimate-sculpted-suit-blazer-in-plum/prd/208996593",
    ["plum"], ["Scorpio", "Capricorn", "Leo"],
    { structure: 92, polished: 90, bodyConscious: 72, glamour: 65, colourIntensity: 55 }),
  p("asos-relaxed-black", "Tailored relaxed blazer in black", "ASOS DESIGN", "outerwear", 59.99,
    "https://www.asos.com/us/asos-design/asos-design-tailored-relaxed-blazer-in-black/prd/208898085",
    ["black"], ["Capricorn", "Virgo", "Scorpio", "Aquarius"],
    { structure: 82, minimal: 82, classic: 82, oversized: 62, colourIntensity: 10 }),
  p("asos-nipped-cutaway-black", "Tailored nipped waist blazer with cut away hem in black", "ASOS DESIGN", "outerwear", 94.99,
    "https://www.asos.com/us/asos-design/asos-design-tailored-nipped-waist-blazer-with-cut-away-hem-in-black/prd/208936219",
    ["black"], ["Leo", "Scorpio", "Aquarius"],
    { structure: 85, bodyConscious: 82, experimental: 65, edge: 68, glamour: 70 }),
  p("gina-trench-beige", "Rich cotton high neck trench coat in natural beige", "Gina Tricot", "outerwear", 174,
    "https://www.asos.com/us/gina-tricot/gina-tricot-rich-cotton-high-neck-trench-coat-in-natural-beige/prd/211468528",
    ["beige"], ["Virgo", "Capricorn", "Libra"],
    { structure: 85, classic: 92, polished: 88, minimal: 78, colourIntensity: 20 }),
  p("asos-trench-stone", "Longline water repellent trench coat in stone", "ASOS DESIGN", "outerwear", 86.99,
    "https://www.asos.com/us/asos-design/asos-design-longline-water-repellent-trench-coat-in-stone/prd/209453239",
    ["stone"], ["Virgo", "Capricorn", "Libra"],
    { structure: 82, classic: 90, minimal: 80, polished: 82, colourIntensity: 18 }),
  p("asos-trench-black", "Longline water repellent trench coat in black", "ASOS DESIGN", "outerwear", 86.99,
    "https://www.asos.com/us/asos-design/asos-design-longline-water-repellent-trench-coat-in-black/prd/209453616",
    ["black"], ["Scorpio", "Capricorn", "Aquarius"],
    { structure: 84, classic: 85, minimal: 82, edge: 60, colourIntensity: 10 }),
  p("vero-moda-trench-stone", "Longline belted trench coat in stone", "Vero Moda", "outerwear", 105,
    "https://www.asos.com/us/vero-moda/vero-moda-longline-belted-trench-coat-in-stone/prd/205972635",
    ["stone"], ["Virgo", "Libra", "Taurus"],
    { structure: 80, classic: 88, polished: 82, romantic: 55 }),

  // ── dresses ──────────────────────────────────────────────────────────────────
  p("topshop-satin-slip-mole", "Satin V-neck maxi slip dress with lace inserts in mole", "Topshop", "dresses", 119,
    "https://www.asos.com/us/topshop/topshop-satin-v-neck-maxi-slip-dress-with-lace-inserts-in-mole/prd/209959033",
    ["mole", "taupe"], ["Pisces", "Taurus", "Libra"],
    { fluidity: 88, sensual: 82, texture: 85, romantic: 82, glamour: 70 }),
  p("asos-satin-slip-fringe-black", "Satin midi slip dress with fringe detailing in black", "ASOS DESIGN", "dresses", 69.99,
    "https://www.asos.com/us/asos-design/asos-design-satin-midi-slip-dress-with-fringe-detailing-in-black/prd/211246970",
    ["black"], ["Scorpio", "Leo", "Capricorn"],
    { sensual: 85, glamour: 82, bodyConscious: 78, edge: 65, colourIntensity: 12 }),
  p("asos-corset-maxi-red", "Corset maxi slip dress with lace and side slit in red", "ASOS DESIGN", "dresses", 119,
    "https://www.asos.com/us/asos-design/asos-design-corset-maxi-slip-dress-with-lace-and-side-slit-in-red/prd/209948629",
    ["red"], ["Leo", "Aries", "Scorpio"],
    { glamour: 92, sensual: 90, bodyConscious: 85, colourIntensity: 92, maximal: 80 }),
  p("reclaimed-cami-satin-fig", "Cami satin maxi slip dress with lace trim in fig", "Reclaimed Vintage", "dresses", 54.99,
    "https://www.asos.com/us/reclaimed-vintage/reclaimed-vintage-cami-satin-maxi-slip-dress-with-lace-trim-in-fig/prd/209805827",
    ["fig", "plum"], ["Pisces", "Scorpio", "Cancer"],
    { fluidity: 85, romantic: 85, sensual: 80, vintage: 80, texture: 78 }),

  // ── shoes ────────────────────────────────────────────────────────────────────
  p("topshop-pascal-black", "Pascal real leather ankle boots in black", "Topshop", "shoes", 119,
    "https://www.asos.com/us/topshop/topshop-pascal-real-leather-ankle-boots-in-black/prd/210608773",
    ["black"], ["Scorpio", "Capricorn", "Virgo"],
    { classic: 82, minimal: 78, structure: 75, edge: 60, colourIntensity: 10 }),
  p("vagabond-blanca-black", "Blanca square toe leather ankle boots in black", "Vagabond Shoemakers", "shoes", 210,
    "https://www.asos.com/us/vagabond-shoemaker/vagabond-shoemakers-blanca-square-toe-leather-ankle-boots-in-black/prd/210869062",
    ["black"], ["Aquarius", "Capricorn", "Scorpio"],
    { experimental: 72, structure: 82, minimal: 80, edge: 68, futuristic: 62 }),
  p("ck-chunky-black", "Chunky leather ankle boots with zipper in black", "Calvin Klein", "shoes", 179.9,
    "https://www.asos.com/us/calvin-klein/calvin-klein-chunky-leather-ankle-boots-with-zipper-in-black/prd/209501493",
    ["black"], ["Aquarius", "Aries", "Scorpio"],
    { edge: 85, structure: 80, sporty: 62, futuristic: 65, colourIntensity: 10 }),
  p("other-stories-heeled-offwhite", "Premium leather heeled ankle boots with tan contrast in off white", "& Other Stories", "shoes", 293,
    "https://www.asos.com/us/other-stories/other-stories-premium-leather-heeled-ankle-boots-with-tan-contrast-in-off-white/prd/211193947",
    ["off white", "tan"], ["Libra", "Virgo", "Taurus"],
    { polished: 90, classic: 82, minimal: 75, texture: 72, glamour: 62 }),

  // ── bags ─────────────────────────────────────────────────────────────────────
  p("pasq-structured-brown", "Structured shoulder bag in brown", "PASQ", "bags", 42,
    "https://www.asos.com/us/pasq/pasq-structured-shoulder-bag-in-brown/prd/209008184",
    ["brown"], ["Taurus", "Virgo", "Sagittarius"],
    { structure: 82, classic: 78, minimal: 72, texture: 65 }),
  p("asos-structured-black", "Structured shoulder bag in black", "ASOS DESIGN", "bags", 44.99,
    "https://www.asos.com/us/asos-design/asos-design-structured-shoulder-bag-in-black/prd/209779620",
    ["black"], ["Capricorn", "Scorpio", "Virgo"],
    { structure: 85, minimal: 82, classic: 80, colourIntensity: 10 }),
  p("mango-slouch-black", "Small structured slouch shoulder bag in black", "Mango", "bags", 69.99,
    "https://www.asos.com/us/mango/mango-small-structured-slouch-shoulder-bag-in-black/prd/211045515",
    ["black"], ["Scorpio", "Aquarius", "Pisces"],
    { structure: 65, fluidity: 62, minimal: 75, edge: 58 }),
  p("mango-tote-burgundy", "Structured tote bag in burgundy", "Mango", "bags", 69.99,
    "https://www.asos.com/us/mango/mango-structured-tote-bag-in-burgundy/prd/211407963",
    ["burgundy"], ["Scorpio", "Taurus", "Capricorn"],
    { structure: 85, classic: 80, texture: 68, colourIntensity: 45 }),
];

/**
 * Every outbound link passes through here, so switching on affiliate tracking later is a one-line
 * change rather than an edit to thirty-five URLs. Set NEXT_PUBLIC_AFFILIATE_TAG once the network
 * account exists (Awin for ASOS).
 */
export function affiliateWrap(url: string): string {
  const tag = process.env.NEXT_PUBLIC_AFFILIATE_TAG;
  if (!tag) return url;
  return `${tag}${encodeURIComponent(url)}`;
}

export function productsForSeason(season: Sign): Product[] {
  return PRODUCTS.filter((product) => product.seasons.includes(season));
}

// ── second curation pass, 30 August 2026 ────────────────────────────────────────
// Broadens the catalogue beyond Virgo-season tailoring: leather, denim, knitwear, maxi and mini
// dresses, winter coats, heels, jewellery and activewear, so every season and every situation has
// something real to rank rather than falling back on the same six tailored pieces.
PRODUCTS.push(
  // outerwear: leather and winter coats
  p("only-moto-black", "Faux leather moto jacket in black", "Only", "outerwear", 81,
    "https://www.asos.com/us/only/only-faux-leather-moto-jacket-in-black/prd/204977941",
    ["black"], ["Aries", "Scorpio", "Aquarius"],
    { edge: 88, structure: 78, bodyConscious: 68, colourIntensity: 10, classic: 62 }),
  p("yas-sophie-leather-biker", "Sophie soft leather biker jacket", "YAS", "outerwear", 252,
    "https://www.asos.com/us/yas/yas-sophie-soft-leather-biker-jacket/prd/202442518",
    ["black"], ["Scorpio", "Aries", "Capricorn"],
    { edge: 85, texture: 85, classic: 72, structure: 78 }),
  p("vero-moda-faux-biker", "Faux leather biker jacket", "Vero Moda", "outerwear", 87,
    "https://www.asos.com/us/vero-moda/vero-moda-faux-leather-biker-jacket/prd/202431585",
    ["black"], ["Aries", "Scorpio", "Aquarius"],
    { edge: 80, structure: 74, casual: 62 }),
  p("topshop-faux-bomber-black", "Faux leather bomber jacket in black", "Topshop", "outerwear", 129,
    "https://www.asos.com/us/topshop/topshop-faux-leather-bomber-jacket-in-black/prd/209963561",
    ["black"], ["Aquarius", "Gemini", "Aries"],
    { edge: 72, sporty: 65, oversized: 70, casual: 70 }),
  p("asos-funnel-chocolate", "Faux leather funnel neck jacket in chocolate brown", "ASOS DESIGN", "outerwear", 149,
    "https://www.asos.com/us/asos-design/asos-design-faux-leather-funnel-neck-jacket-in-chocolate-brown/prd/210194842",
    ["chocolate"], ["Taurus", "Capricorn", "Virgo"],
    { structure: 84, texture: 75, minimal: 74, classic: 70 }),
  p("asos-waterfall-cream", "Short formal waterfall coat with wool in cream", "ASOS DESIGN", "outerwear", 99.99,
    "https://www.asos.com/us/asos-design/asos-design-short-formal-waterfall-coat-with-wool-in-cream/prd/210355276",
    ["cream"], ["Libra", "Pisces", "Cancer"],
    { fluidity: 74, polished: 82, romantic: 68, texture: 70 }),
  p("asos-waterfall-burgundy", "Short formal waterfall coat with wool in burgundy", "ASOS DESIGN", "outerwear", 99.99,
    "https://www.asos.com/us/asos-design/asos-design-short-formal-waterfall-coat-with-wool-in-burgundy/prd/210356385",
    ["burgundy"], ["Scorpio", "Taurus", "Leo"],
    { polished: 82, colourIntensity: 55, texture: 72, glamour: 62 }),
  p("topshop-wool-animal-print", "Wool blend jacket in animal print", "Topshop", "outerwear", 139,
    "https://www.asos.com/us/topshop/topshop-wool-blend-jacket-in-animal-print/prd/210421473",
    ["animal print", "brown"], ["Leo", "Sagittarius", "Gemini"],
    { printIntensity: 92, glamour: 80, maximal: 82, texture: 72 }, ["busy_print"]),
  p("weekday-logan-black", "Logan wool blend oversized double breasted coat in black", "Weekday", "outerwear", 234,
    "https://www.asos.com/us/weekday/weekday-logan-wool-blend-oversized-double-breasted-coat-in-black/prd/211044160",
    ["black"], ["Capricorn", "Scorpio", "Aquarius"],
    { structure: 92, classic: 88, oversized: 74, minimal: 84, colourIntensity: 10 }),
  p("weekday-logan-mole", "Logan wool blend oversized coat in mole melange twill", "Weekday", "outerwear", 234,
    "https://www.asos.com/us/weekday/weekday-logan-wool-blend-oversized-coat-in-mole-melange-twill/prd/211044146",
    ["mole", "taupe"], ["Virgo", "Taurus", "Capricorn"],
    { structure: 86, classic: 86, texture: 74, minimal: 80 }),

  // dresses: maxi and mini
  p("asos-smock-maxi-olive", "Smock maxi dress with funnel neck in techy fabric in dark olive", "ASOS DESIGN", "dresses", 69.99,
    "https://www.asos.com/us/asos-design/asos-design-smock-maxi-dress-with-funnel-neck-and-dropped-waist-in-techy-fabric-in-dark-olive/prd/210660812",
    ["olive"], ["Sagittarius", "Aquarius", "Virgo"],
    { fluidity: 80, casual: 72, oversized: 74, futuristic: 62 }),
  p("asos-floral-mesh-buttermilk", "Floral printed sweetheart neck mesh fishtail maxi dress", "ASOS DESIGN", "dresses", 79.99,
    "https://www.asos.com/us/asos-design/asos-design-floral-printed-sweetheart-neck-mesh-fishtail-maxi-dress-in-buttermilk/prd/210872259",
    ["buttermilk"], ["Cancer", "Libra", "Pisces"],
    { romantic: 90, printIntensity: 80, fluidity: 84, feminine: 88 }),
  p("asos-chiffon-godet-taupe", "Chiffon shirred waist panel godet maxi dress in taupe", "ASOS DESIGN", "dresses", 109,
    "https://www.asos.com/us/asos-design/asos-design-chiffon-shirred-waist-panel-godet-maxi-dress-in-taupe/prd/209901722",
    ["taupe"], ["Pisces", "Taurus", "Libra"],
    { fluidity: 90, romantic: 82, texture: 78, glamour: 65 }),
  p("asos-plisse-halter-rum-raisin", "Plisse contrast draped halter neck maxi dress in rum raisin", "ASOS DESIGN", "dresses", 74.99,
    "https://www.asos.com/us/asos-design/asos-design-plisse-contrast-draped-halter-neck-maxi-dress-in-rum-raisin/prd/210897641",
    ["rum raisin", "plum"], ["Scorpio", "Leo", "Taurus"],
    { fluidity: 80, sensual: 80, glamour: 74, texture: 76 }),
  p("asos-poplin-maxi-choc-polka", "Poplin maxi dress with asymmetric waist and volume sleeves", "ASOS DESIGN", "dresses", 84.99,
    "https://www.asos.com/us/asos-design/asos-design-poplin-maxi-dress-with-asymmetric-waist-and-volume-sleeves-in-chocolate-polka-dots/prd/210385862",
    ["chocolate"], ["Gemini", "Cancer", "Virgo"],
    { printIntensity: 78, romantic: 68, structure: 58, experimental: 60 }),
  p("topshop-organza-bubble-black", "Organza bubble hem mini dress in black", "Topshop", "dresses", 95,
    "https://www.asos.com/us/topshop/topshop-organza-bubble-hem-mini-dress-in-black/prd/210486268",
    ["black"], ["Aquarius", "Leo", "Libra"],
    { experimental: 80, glamour: 80, texture: 74, maximal: 70 }),
  p("asos-cape-sleeve-magenta", "High neck drape front extreme cape sleeve mini dress in magenta", "ASOS DESIGN", "dresses", 59.99,
    "https://www.asos.com/us/asos-design/asos-design-high-neck-drape-front-extreme-cape-sleeve-mini-dress-in-magenta/prd/210900792",
    ["magenta"], ["Leo", "Aries", "Sagittarius"],
    { maximal: 88, colourIntensity: 92, glamour: 84, experimental: 70 }),
  p("asos-satin-cami-berry", "Satin cami shift mini dress in berry", "ASOS DESIGN", "dresses", 59.99,
    "https://www.asos.com/us/asos-design/asos-design-satin-cami-shift-mini-dress-in-berry/prd/210554281",
    ["berry"], ["Scorpio", "Taurus", "Libra"],
    { sensual: 84, texture: 82, glamour: 70, colourIntensity: 55 }),
  p("asos-rib-slash-chocolate", "Rib slash neck shoulder seam mini dress in chocolate", "ASOS DESIGN", "dresses", 22.99,
    "https://www.asos.com/us/asos-design/asos-design-rib-slash-neck-shoulder-seam-mini-dress-in-chocolate/prd/210801014",
    ["chocolate"], ["Taurus", "Virgo", "Capricorn"],
    { minimal: 84, bodyConscious: 72, casual: 65, texture: 65 }),
  p("asos-cape-tassel-green", "Cape sleeve open back mini dress with tassels in green", "ASOS DESIGN", "dresses", 94.99,
    "https://www.asos.com/us/asos-design/asos-design-cape-sleeve-open-back-mini-dress-with-tassels-in-green/prd/210619544",
    ["green"], ["Sagittarius", "Aquarius", "Leo"],
    { maximal: 84, experimental: 78, glamour: 75, colourIntensity: 72 }),

  // bottoms: denim
  p("asos-wide-gray-wash", "High rise wide leg jeans in tinted gray wash", "ASOS DESIGN", "bottoms", 59.99,
    "https://www.asos.com/us/asos-design/asos-design-high-rise-wide-leg-jeans-in-tinted-gray-wash/prd/208696358",
    ["gray"], ["Aquarius", "Virgo", "Capricorn"],
    { casual: 74, structure: 64, minimal: 72, experimental: 58 }),
  p("asos-wide-crease-lightwash", "Wide leg jeans with crease front and belt in lightwash", "ASOS DESIGN", "bottoms", 74.99,
    "https://www.asos.com/us/asos-design/asos-design-wide-leg-jeans-with-crease-front-and-belt-in-lightwash/prd/210550175",
    ["lightwash"], ["Gemini", "Sagittarius", "Aquarius"],
    { casual: 78, structure: 62, colourIntensity: 45 }),
  p("asos-palazzo-lightwash", "Wide leg palazzo jeans in lightwash", "ASOS DESIGN", "bottoms", 64.99,
    "https://www.asos.com/us/asos-design/asos-design-wide-leg-palazzo-jeans-in-lightwash/prd/210169233",
    ["lightwash"], ["Sagittarius", "Pisces", "Gemini"],
    { fluidity: 74, casual: 80, oversized: 74 }),
  p("asos-straight-rinse", "High waist straight wide leg jeans in rinse", "ASOS DESIGN", "bottoms", 59.99,
    "https://www.asos.com/us/asos-design/asos-design-high-waist-straight-wide-leg-jeans-in-rinse/prd/210115331",
    ["indigo"], ["Capricorn", "Virgo", "Taurus"],
    { classic: 82, minimal: 76, structure: 66 }),
  p("collusion-x003-washed-black", "x003 wide leg jean in washed black", "COLLUSION", "bottoms", 52.99,
    "https://www.asos.com/us/collusion/collusion-x003-wide-leg-jean-in-washed-black/prd/208852917",
    ["washed black"], ["Aquarius", "Scorpio", "Aries"],
    { edge: 70, casual: 74, experimental: 65, colourIntensity: 15 }),

  // tops: knitwear and sets
  p("asos-waisted-cardigan-pink", "Waisted crew neck cardigan with wool and covered buttons in pink", "ASOS DESIGN", "tops", 47.99,
    "https://www.asos.com/us/asos-design/asos-design-waisted-crew-neck-cardigan-with-wool-and-covered-buttons-in-pink/prd/210360040",
    ["pink"], ["Libra", "Cancer", "Taurus"],
    { romantic: 82, feminine: 88, bodyConscious: 62, texture: 72, vintage: 65 }),
  p("asos-boxy-cardigan-black", "Boxy cardigan with side slit detail in black", "ASOS DESIGN", "tops", 44.99,
    "https://www.asos.com/us/asos-design/asos-design-boxy-cardigan-with-side-slit-detail-in-black/prd/210343526",
    ["black"], ["Aquarius", "Capricorn", "Scorpio"],
    { minimal: 80, oversized: 70, experimental: 62, colourIntensity: 10 }),
  p("monki-oversized-cardigan-chocolate", "Oversized cardigan in chocolate brown", "Monki", "tops", 70,
    "https://www.asos.com/us/monki/monki-oversized-cardigan-in-chocolate-brown/prd/208874486",
    ["chocolate"], ["Taurus", "Cancer", "Sagittarius"],
    { oversized: 82, texture: 82, casual: 78 }),
  p("topshop-fluffy-eyelash-ivory", "Fluffy eyelash knit cardigan in ivory", "Topshop", "tops", 65,
    "https://www.asos.com/us/topshop/topshop-fluffy-eyelash-knit-cardigan-in-ivory/prd/210333308",
    ["ivory"], ["Cancer", "Pisces", "Taurus"],
    { texture: 92, romantic: 84, casual: 72, feminine: 85 }),
  p("miss-selfridge-maxi-cardigan-oatmeal", "Maxi cardigan with lace detail in oatmeal", "Miss Selfridge", "tops", 74.99,
    "https://www.asos.com/us/miss-selfridge-petite/miss-selfridge-petite-maxi-cardigan-with-lace-detail-in-oatmeal/prd/210574274",
    ["oatmeal"], ["Pisces", "Cancer", "Taurus"],
    { fluidity: 82, oversized: 84, romantic: 78, texture: 78 }),
  p("asos-peplum-shell-brown", "Linen blend tailored peplum shell top in brown", "ASOS DESIGN", "tops", 49.99,
    "https://www.asos.com/us/asos-design/asos-design-linen-blend-tailored-peplum-shell-top-in-brown-part-of-a-set/prd/210140965",
    ["brown"], ["Virgo", "Libra", "Taurus"],
    { polished: 86, structure: 76, classic: 74, minimal: 70 }),
  p("asos-peplum-shell-pastel-yellow", "Tailored peplum shell top in pastel yellow", "ASOS DESIGN", "tops", 49.99,
    "https://www.asos.com/us/asos-design/asos-design-tailored-peplum-shell-top-in-pastel-yellow/prd/210140819",
    ["pastel yellow"], ["Gemini", "Libra", "Leo"],
    { polished: 82, colourIntensity: 58, feminine: 75 }, ["pastel_yellow"]),
  p("free-people-lounge-butter", "Intimately FP fresh in love lounge set", "Free People", "tops", 98,
    "https://www.asos.com/us/free-people/free-people-intimately-fp-fresh-in-love-lounge-set-in-butter-combo/prd/210071706",
    ["butter"], ["Cancer", "Pisces", "Taurus"],
    { casual: 90, texture: 82, romantic: 72, fluidity: 78 }),

  // shoes: heels
  p("topshop-asher-kitten-red", "Asher kitten heel pumps in red leather", "Topshop", "shoes", 80,
    "https://www.asos.com/us/topshop/topshop-asher-kitten-heel-pumps-in-red-hair-on-real-leather/prd/211037644",
    ["red"], ["Aries", "Leo", "Libra"],
    { colourIntensity: 90, polished: 80, glamour: 72, texture: 70 }),
  p("asos-nigella-flower-sandals", "Nigella oversized flower detailing tie leg high heel sandals", "ASOS DESIGN", "shoes", 59.99,
    "https://www.asos.com/us/asos-design/asos-design-nigella-oversized-flower-detailing-tie-leg-high-heel-sandals-in-olive-and-pink/prd/209635375",
    ["olive", "pink"], ["Libra", "Pisces", "Cancer"],
    { romantic: 88, feminine: 85, printIntensity: 60, glamour: 70 }),
  p("adidas-samba-maryjane-burgundy", "Samba Mary Jane pumps in burgundy and cream", "adidas Originals", "shoes", 100,
    "https://www.asos.com/us/adidas-originals/adidas-originals-samba-mary-jane-pumps-in-burgundy-and-cream/prd/209218228",
    ["burgundy", "cream"], ["Gemini", "Aquarius", "Sagittarius"],
    { sporty: 80, casual: 80, experimental: 68, vintage: 62 }),
  p("topshop-nancy-caramel-dalmatian", "Nancy toe thong mid heel sandals in caramel dalmatian print", "Topshop", "shoes", 80,
    "https://www.asos.com/us/topshop/topshop-nancy-toe-thong-mid-heel-sandals-in-caramel-dalmatian-print-hair-on-real-leather/prd/210578093",
    ["caramel"], ["Sagittarius", "Gemini", "Leo"],
    { printIntensity: 82, experimental: 65, texture: 72 }),
  p("asos-huddle-purple-velvet", "Huddle padded toe thong heeled sandals in purple velvet", "ASOS DESIGN", "shoes", 47.99,
    "https://www.asos.com/us/asos-design/asos-design-huddle-padded-toe-thong-heeled-sandals-in-purple-velvet/prd/210761929",
    ["purple"], ["Scorpio", "Pisces", "Leo"],
    { texture: 88, sensual: 74, glamour: 70, colourIntensity: 60 }),

  // jewellery
  p("pieces-flower-chain-gold", "2 pack flower and chain necklaces in gold tone", "PIECES", "jewellery", 22,
    "https://www.asos.com/us/pieces/pieces-2-pack-flower-and-chain-necklaces-in-gold-tone/prd/210715762",
    ["gold"], ["Leo", "Libra", "Taurus"],
    { glamour: 72, feminine: 80, romantic: 70 }),
  p("kingsley-square-stud-gold", "3mm gem set square stud in 14kt gold plated brass", "Kingsley Ryan", "jewellery", 10.5,
    "https://www.asos.com/us/kingsley-ryan/kingsley-ryan-3mm-gem-set-square-stud-in-14kt-gold-plated-brass/prd/211131031",
    ["gold"], ["Virgo", "Capricorn", "Taurus"],
    { minimal: 92, classic: 84, polished: 82 }),
  p("kingsley-star-hoops-gold", "20mm chunky gem set star hoops in 14kt gold plated brass", "Kingsley Ryan", "jewellery", 25,
    "https://www.asos.com/us/kingsley-ryan/kingsley-ryan-20mm-chunky-gem-set-star-hoops-in-14kt-gold-plated-brass/prd/211130858",
    ["gold"], ["Leo", "Sagittarius", "Aquarius"],
    { glamour: 84, maximal: 74, experimental: 62 }),
  p("asos-emerald-crystal-necklace", "Emerald black and crystal stone set necklace in gold", "ASOS DESIGN", "jewellery", 34.99,
    "https://www.asos.com/us/asos-design/asos-design-emerald-black-and-crystal-stone-set-necklace-in-gold/prd/209948662",
    ["gold", "black", "emerald"], ["Leo", "Scorpio", "Capricorn"],
    { glamour: 90, maximal: 80, colourIntensity: 60 }),
  p("asos-emerald-crystal-bracelet", "Emerald black and crystal stone set bracelet in gold tone", "ASOS DESIGN", "jewellery", 22.99,
    "https://www.asos.com/us/asos-design/asos-design-emerald-black-and-crystal-stone-set-bracelet-in-gold-tone/prd/209948645",
    ["gold", "black"], ["Leo", "Scorpio", "Taurus"],
    { glamour: 82, maximal: 72 }),

  // activewear
  p("nike-poplin-shorts-pink", "Poplin stripe woven shorts in pink", "Nike", "activewear", 55,
    "https://www.asos.com/us/nike/nike-poplin-stripe-woven-shorts-in-pink/prd/209785355",
    ["pink"], ["Aries", "Gemini", "Leo"],
    { sporty: 90, casual: 82, colourIntensity: 70 }),
  p("4505-vneck-bra-black", "Active V-neck racer back medium support sports bra in black", "4505", "activewear", 37.99,
    "https://www.asos.com/us/4505/4505-active-v-neck-racer-back-medium-support-sports-bra-in-black/prd/210368502",
    ["black"], ["Aries", "Scorpio", "Capricorn"],
    { sporty: 92, bodyConscious: 86, minimal: 80, colourIntensity: 10 }),
  p("nike-swoosh-bra-black", "Training swoosh medium support sports bra in black", "Nike", "activewear", 40,
    "https://www.asos.com/us/nike-training/nike-training-swoosh-medium-support-sports-bra-in-black/prd/206094783",
    ["black"], ["Aries", "Aquarius", "Capricorn"],
    { sporty: 94, minimal: 78, structure: 72, colourIntensity: 10 }),
  p("4505-soft-touch-bra-black", "Soft touch medium support sports bra with removable padding", "4505", "activewear", 29.99,
    "https://www.asos.com/us/4505/4505-soft-touch-medium-support-sports-bra-with-removable-padding-in-black/prd/210367318",
    ["black"], ["Cancer", "Taurus", "Pisces"],
    { sporty: 84, texture: 74, casual: 78 })
);

// ── third pass: balancing the thinner seasons and categories ────────────────────
// Gemini, Cancer, Sagittarius and Pisces had roughly half the coverage of Taurus and Scorpio, and
// bags were the thinnest category, so this pass targets prints, florals, sheers, suede and bags.
PRODUCTS.push(
  // bags
  p("asos-frame-bag-mustard", "Frame shoulder bag in mustard yellow", "ASOS DESIGN", "bags", 39.99,
    "https://www.asos.com/us/asos-design/asos-design-frame-shoulder-bag-in-mustard-yellow/prd/210916929",
    ["mustard"], ["Leo", "Sagittarius", "Gemini"],
    { colourIntensity: 80, vintage: 68, structure: 70 }),
  p("asos-sequin-bag-gunmetal", "Sequin and bead shoulder bag in gunmetal silver", "ASOS DESIGN", "bags", 63.99,
    "https://www.asos.com/us/asos-design/asos-design-sequin-bead-shoulder-bag-in-gunmetal-silver/prd/210314594",
    ["gunmetal", "silver"], ["Aquarius", "Scorpio", "Pisces"],
    { glamour: 84, futuristic: 72, texture: 80, maximal: 70 }),
  p("asos-hair-on-deer-print", "Hair on leather grab bag in deer print", "ASOS DESIGN", "bags", 47.99,
    "https://www.asos.com/us/asos-design/asos-design-hair-on-leather-grab-bag-in-deer-print/prd/210831359",
    ["brown", "print"], ["Sagittarius", "Gemini", "Leo"],
    { printIntensity: 86, texture: 80, vintage: 65 }),
  p("asos-bag-gold-hardware-chocolate", "Shoulder bag with gold hardware in chocolate", "ASOS DESIGN", "bags", 39.99,
    "https://www.asos.com/us/asos-design/asos-design-shoulder-bag-with-gold-hardware-in-chocolate/prd/210184208",
    ["chocolate", "gold"], ["Taurus", "Leo", "Libra"],
    { classic: 78, texture: 70, glamour: 66 }),
  p("glamorous-woven-bag-brown", "Oversized woven shoulder bag in deep brown", "Glamorous", "bags", 56,
    "https://www.asos.com/us/glamorous/glamorous-oversized-woven-shoulder-bag-in-deep-brown/prd/208640234",
    ["brown"], ["Sagittarius", "Taurus", "Cancer"],
    { texture: 84, casual: 76, oversized: 78, vintage: 70 }),

  // dresses: florals for Cancer, Libra, Pisces, Gemini
  p("asos-halter-trapeze-floral", "Halter trapeze midi dress in blurred floral print", "ASOS DESIGN", "dresses", 47.99,
    "https://www.asos.com/us/asos-design/asos-design-halter-trapeze-midi-dress-in-blurred-floral-print/prd/209988845",
    ["floral"], ["Cancer", "Pisces", "Gemini"],
    { printIntensity: 84, romantic: 82, fluidity: 80, feminine: 85 }),
  p("asos-devore-floral-black", "Devore floral midi dress with fringing detail in black", "ASOS DESIGN", "dresses", 69.99,
    "https://www.asos.com/us/asos-design/asos-design-devore-floral-midi-dress-with-fringing-detail-in-black/prd/211448025",
    ["black"], ["Scorpio", "Pisces", "Leo"],
    { texture: 86, glamour: 78, sensual: 76, printIntensity: 70 }),
  p("other-stories-3d-floral-black", "3D floral midi dress with V-drop waist in black", "& Other Stories", "dresses", 139,
    "https://www.asos.com/us/other-stories/other-stories-3d-floral-midi-dress-with-v-drop-waist-in-black/prd/208535043",
    ["black"], ["Libra", "Scorpio", "Cancer"],
    { romantic: 84, polished: 84, texture: 82, glamour: 74 }),
  p("topshop-3d-flower-chocolate", "Asymmetric one shoulder 3D flower midi dress in chocolate", "Topshop", "dresses", 95,
    "https://www.asos.com/us/topshop/topshop-asymmetric-one-shoulder-3d-flower-midi-dress-in-chocolate/prd/207910993",
    ["chocolate"], ["Taurus", "Libra", "Aquarius"],
    { experimental: 74, romantic: 76, texture: 80, glamour: 72 }),
  p("bardot-louisa-floral-pink", "Louisa cami floral mesh midi dress in light pink", "Bardot", "dresses", 170,
    "https://www.asos.com/us/bardot/bardot-louisa-exclusive-cami-floral-mesh-midi-dress-in-light-pink/prd/210410690",
    ["light pink"], ["Libra", "Cancer", "Pisces"],
    { romantic: 90, feminine: 92, printIntensity: 76, glamour: 76 }),

  // tops: stripes and sheers for Gemini, Pisces, Scorpio
  p("asos-sheer-striped-shirt", "Sheer striped shirt", "ASOS DESIGN", "tops", 47.99,
    "https://www.asos.com/us/asos-design/asos-design-sheer-striped-shirt/prd/209975855",
    ["stripe"], ["Gemini", "Pisces", "Aquarius"],
    { printIntensity: 78, fluidity: 74, experimental: 68, sensual: 65 }),
  p("jjxx-poplin-stripe-blue", "Poplin striped shirt in blue", "JJXX", "tops", 44,
    "https://www.asos.com/us/jjxx/jjxx-poplin-striped-shirt-in-blue/prd/210075949",
    ["blue", "stripe"], ["Gemini", "Virgo", "Aquarius"],
    { printIntensity: 70, classic: 74, casual: 72, polished: 70 }),
  p("kaiia-bow-stripe-chocolate", "Shoulder pad bow tie back detail striped shirt in chocolate", "Kaiia", "tops", 66,
    "https://www.asos.com/us/kaiia/kaiia-exclusive-shoulder-pad-bow-tie-back-detail-striped-shirt-in-chocolate/prd/210725107",
    ["chocolate", "stripe"], ["Libra", "Leo", "Taurus"],
    { structure: 78, romantic: 74, printIntensity: 68, polished: 78 }),
  p("free-people-seaside-stripe", "Seaside cotton striped shirt in ivory combo", "Free People", "tops", 128,
    "https://www.asos.com/us/free-people/free-people-seaside-cotton-striped-shirt-in-ivory-combo/prd/210522965",
    ["ivory", "stripe"], ["Cancer", "Sagittarius", "Gemini"],
    { casual: 84, texture: 74, vintage: 72, oversized: 74 }),
  p("free-people-oversized-wine", "Relaxed oversized striped shirt in wine", "Free People", "tops", 148,
    "https://www.asos.com/us/free-people/free-people-relaxed-oversized-striped-shirt-in-wine/prd/207647540",
    ["wine"], ["Sagittarius", "Scorpio", "Taurus"],
    { oversized: 84, casual: 82, texture: 76, colourIntensity: 55 }),
  p("asos-sheer-cami-polka", "Sheer mesh cami top in black polka dot", "ASOS DESIGN", "tops", 27.99,
    "https://www.asos.com/us/asos-design/asos-design-sheer-mesh-cami-top-in-black-polka-dot/prd/210381488",
    ["black"], ["Gemini", "Scorpio", "Pisces"],
    { sensual: 78, printIntensity: 70, fluidity: 72, edge: 62 }),
  p("asos-sheer-cami-black", "Sheer mesh cami top in black", "ASOS DESIGN", "tops", 22.99,
    "https://www.asos.com/us/asos-design/asos-design-sheer-mesh-cami-top-in-black/prd/210441915",
    ["black"], ["Scorpio", "Pisces", "Aquarius"],
    { sensual: 84, fluidity: 76, minimal: 72, edge: 68, colourIntensity: 10 }),
  p("asos-sheer-cami-chocolate", "Sheer mesh cami top in chocolate", "ASOS DESIGN", "tops", 22.99,
    "https://www.asos.com/us/asos-design/asos-design-sheer-mesh-cami-top-in-chocolate/prd/210441950",
    ["chocolate"], ["Taurus", "Pisces", "Scorpio"],
    { sensual: 80, fluidity: 76, texture: 70 }),
  p("asos-sheer-cami-red-gingham", "Sheer mesh cami top in red gingham", "ASOS DESIGN", "tops", 27.99,
    "https://www.asos.com/us/asos-design/asos-design-sheer-mesh-cami-top-in-red-gingham/prd/210381565",
    ["red"], ["Gemini", "Aries", "Leo"],
    { printIntensity: 82, colourIntensity: 78, casual: 68 }),

  // outerwear: suede for Sagittarius, Taurus, Cancer
  p("topshop-faux-suede-bomber-chocolate", "Faux suede bomber jacket with snap details in chocolate", "Topshop", "outerwear", 139,
    "https://www.asos.com/us/topshop/topshop-faux-suede-bomber-jacket-with-snap-details-in-chocolate/prd/208549738",
    ["chocolate"], ["Sagittarius", "Taurus", "Cancer"],
    { texture: 86, casual: 76, vintage: 72, oversized: 68 }),
  p("kaiia-faux-suede-light-blue", "Faux suede cargo pocket funnel neck bomber jacket in light blue", "Kaiia", "outerwear", 113,
    "https://www.asos.com/us/kaiia/kaiia-exclusive-faux-suede-cargo-pocket-front-balloon-sleeve-funnel-neck-bomber-jacket-in-light-blue/prd/210816558",
    ["light blue"], ["Aquarius", "Gemini", "Pisces"],
    { experimental: 78, texture: 78, oversized: 74, colourIntensity: 60 }),
  p("only-curve-suede-dark-brown", "Faux suede jacket in dark brown", "ONLY", "outerwear", 81,
    "https://www.asos.com/us/only-curve/only-curve-faux-suede-jacket-in-dark-brown/prd/211407166",
    ["dark brown"], ["Taurus", "Sagittarius", "Capricorn"],
    { texture: 84, classic: 74, casual: 70 }),
  p("topshop-premium-suede-blue", "Premium real suede jacket in blue", "Topshop", "outerwear", 439,
    "https://www.asos.com/us/topshop/topshop-premium-real-suede-jacket-in-blue/prd/208747345",
    ["blue"], ["Sagittarius", "Aquarius", "Taurus"],
    { texture: 90, colourIntensity: 70, experimental: 66, classic: 68 })
);

// ── fourth pass: broad expansion across every rising and Venus sign ─────────────
PRODUCTS.push(
  p("asos-cape-red-mini", "High neck drape front extreme cape sleeves mini dress in red", "ASOS DESIGN", "dresses", 59.99,
    "https://www.asos.com/us/asos-design/asos-design-high-neck-drape-front-extreme-cape-sleeves-mini-dress-in-red/prd/210136795",
    ["red"], ["Aries", "Leo", "Sagittarius"], { maximal: 88, colourIntensity: 92, glamour: 82 }),
  p("asos-peplum-maxi-red", "V-neck nipped waist peplum maxi dress in red", "ASOS DESIGN", "dresses", 74.99,
    "https://www.asos.com/us/asos-design/asos-design-v-neck-nipped-waist-peplum-maxi-dress-in-red/prd/210167642",
    ["red"], ["Leo", "Libra", "Aries"], { glamour: 82, romantic: 74, colourIntensity: 90, bodyConscious: 72 }),
  p("asos-strapless-trapeze-red", "Strapless trapeze mini dress in red", "ASOS DESIGN", "dresses", 54.99,
    "https://www.asos.com/us/asos-design/asos-design-strapless-trapeze-mini-dress-in-red/prd/210816940",
    ["red"], ["Aries", "Leo", "Gemini"], { colourIntensity: 90, casual: 58, sensual: 70 }),
  p("asos-satin-bias-red", "Satin bias split detail maxi dress in red", "ASOS DESIGN", "dresses", 99.99,
    "https://www.asos.com/us/asos-design/asos-design-satin-bias-split-detail-maxi-dress-in-red/prd/210282853",
    ["red"], ["Scorpio", "Leo", "Taurus"], { sensual: 86, texture: 84, colourIntensity: 88, fluidity: 80 }),
  p("asos-cape-maxi-burgundy", "Exaggerated cape maxi dress in burgundy", "ASOS DESIGN", "dresses", 74.99,
    "https://www.asos.com/us/asos-design/asos-design-exaggerated-cape-maxi-dress-in-burgundy/prd/209675511",
    ["burgundy"], ["Scorpio", "Capricorn", "Leo"], { maximal: 80, glamour: 78, structure: 72 }),
  p("asos-rib-halter-red-mini", "Rib knit seam detailing halter neck mini dress in red", "ASOS DESIGN", "dresses", 27.99,
    "https://www.asos.com/us/asos-design/asos-design-rib-knit-seam-detailing-halter-neck-mini-dress-in-red/prd/210061785",
    ["red"], ["Aries", "Scorpio", "Leo"], { bodyConscious: 84, colourIntensity: 88, minimal: 66 }),
  p("asos-luxe-bandeau-white", "Pleated bandeau long sleeve top in white", "ASOS LUXE", "tops", 94.99,
    "https://www.asos.com/us/asos-luxe/asos-luxe-pleated-bandeau-long-sleeve-top-in-white/prd/209973010",
    ["white"], ["Libra", "Leo", "Aquarius"], { polished: 88, structure: 76, glamour: 74, experimental: 62 }),
  p("asos-corset-boning-black", "Corset top with boning in black", "ASOS DESIGN", "tops", 29.99,
    "https://www.asos.com/us/asos-design/asos-design-corset-top-with-boning-in-black/prd/208668815",
    ["black"], ["Scorpio", "Leo", "Aries"], { bodyConscious: 90, sensual: 84, edge: 74, colourIntensity: 10 }),
  p("asos-lace-corset-chocolate", "Lace mix detailing corset top with boning in chocolate", "ASOS DESIGN", "tops", 49.99,
    "https://www.asos.com/us/asos-design/asos-design-lace-mix-detailing-corset-top-with-boning-in-chocolate/prd/210257950",
    ["chocolate"], ["Taurus", "Scorpio", "Pisces"], { sensual: 84, texture: 84, romantic: 74 }),
  p("ohpolly-satin-corset-black", "Satin square neck corset top in black", "Oh Polly", "tops", 104,
    "https://www.asos.com/us/oh-polly/oh-polly-satin-square-neck-corset-top-in-black/prd/211344514",
    ["black"], ["Scorpio", "Leo", "Capricorn"], { sensual: 88, glamour: 84, bodyConscious: 88, texture: 78 }),
  p("ohpolly-laceup-corset-black", "Lace up back corset top in black lace", "Oh Polly", "tops", 87,
    "https://www.asos.com/us/oh-polly/oh-polly-lace-up-back-corset-top-in-black-lace/prd/209571392",
    ["black"], ["Scorpio", "Aries", "Leo"], { edge: 84, sensual: 90, texture: 80 }),
  p("asos-mesh-corset-black", "Long sleeve mesh corset top with hook and eye closures in black", "ASOS DESIGN", "tops", 54.99,
    "https://www.asos.com/us/asos-design/asos-design-long-sleeve-mesh-corset-top-with-hook-and-eye-closures-in-black/prd/210929645",
    ["black"], ["Aquarius", "Scorpio", "Aries"], { experimental: 78, edge: 80, sensual: 82 }),
  p("asos-shoulderpad-satin-pink", "Shoulder pad satin blouse in pink", "ASOS DESIGN", "tops", 54.99,
    "https://www.asos.com/us/asos-design/asos-design-shoulder-pad-satin-blouse-in-pink/prd/211336204",
    ["pink"], ["Libra", "Leo", "Cancer"], { romantic: 82, glamour: 76, feminine: 88, structure: 70 }),
  p("topshop-satin-scarf-burgundy", "Satin scarf blouse in burgundy", "Topshop", "tops", 65,
    "https://www.asos.com/us/topshop/topshop-satin-scarf-blouse-in-burgundy/prd/209573959",
    ["burgundy"], ["Scorpio", "Taurus", "Libra"], { texture: 84, sensual: 76, vintage: 70 }),
  p("asos-volume-satin-black", "Volume sleeve satin blouse in black", "ASOS DESIGN", "tops", 49.99,
    "https://www.asos.com/us/asos-design/asos-design-volume-sleeve-satin-blouse-in-black-part-of-a-set/prd/208886694",
    ["black"], ["Leo", "Capricorn", "Scorpio"], { glamour: 78, structure: 72, polished: 84 }),
  p("asos-lace-satin-surf-spray", "Lace insert satin tiered blouse in surf spray", "ASOS DESIGN", "tops", 59.99,
    "https://www.asos.com/us/asos-design/asos-design-lace-insert-satin-tiered-blouse-in-surf-spray/prd/210594731",
    ["surf spray", "aqua"], ["Pisces", "Cancer", "Libra"], { romantic: 86, fluidity: 82, texture: 78 }),
  p("missselfridge-satin-tie-fig", "Satin tie front blouse in fig", "Miss Selfridge", "tops", 59.99,
    "https://www.asos.com/us/miss-selfridge/miss-selfridge-satin-tie-front-blouse-in-fig/prd/209825443",
    ["fig"], ["Scorpio", "Pisces", "Taurus"], { sensual: 80, texture: 82, romantic: 70 }),
  p("wednesdays-satin-lace-navy", "Long sleeve satin lace detailed blouse in navy", "Wednesday's Girl", "tops", 49,
    "https://www.asos.com/us/wednesdays-girl/wednesdays-girl-long-sleeve-satin-lace-detailed-blouse-in-navy/prd/209462307",
    ["navy"], ["Cancer", "Pisces", "Libra"], { romantic: 84, texture: 78, feminine: 82 }),
  p("veromoda-crochet-red-cream", "Stretch crochet knit bell sleeve mini dress in red and cream stripes", "Vero Moda", "dresses", 58,
    "https://www.asos.com/us/vero-moda/vero-moda-stretch-crochet-knit-bell-sleeve-mini-dress-in-red-and-cream-stripes/prd/210548670",
    ["red", "cream"], ["Gemini", "Leo", "Sagittarius"], { printIntensity: 80, casual: 74, vintage: 72 }),
  p("missselfridge-knit-mandarin-choc", "Knit dress with mandarin collar in chocolate", "Miss Selfridge", "dresses", 59.99,
    "https://www.asos.com/us/miss-selfridge/miss-selfridge-knit-dress-with-mandarin-collar-in-chocolate/prd/210979796",
    ["chocolate"], ["Virgo", "Taurus", "Capricorn"], { minimal: 80, classic: 80, texture: 76 }),
  p("veromoda-crochet-black-cream", "Stretch crochet knit bell sleeve mini dress in black and cream stripe", "Vero Moda", "dresses", 58,
    "https://www.asos.com/us/vero-moda/vero-moda-stretch-crochet-knit-bell-sleeve-mini-dress-in-black-and-cream-stripe/prd/210548520",
    ["black", "cream"], ["Gemini", "Aquarius", "Libra"], { printIntensity: 78, casual: 74, experimental: 62 }),
  p("other-stories-zip-knit-black", "Zip up compact knit mini dress in black", "& Other Stories", "dresses", 156,
    "https://www.asos.com/us/other-stories/other-stories-zip-up-compact-knit-mini-dress-in-black/prd/210150757",
    ["black"], ["Capricorn", "Scorpio", "Aquarius"], { minimal: 88, structure: 80, bodyConscious: 78, colourIntensity: 10 }),
  p("asos-knit-sweater-dress-black", "Knit sweater dress in black", "ASOS DESIGN", "dresses", 59.99,
    "https://www.asos.com/us/asos-design/asos-design-knit-sweater-dress-in-black/prd/210483345",
    ["black"], ["Taurus", "Capricorn", "Cancer"], { texture: 82, casual: 72, minimal: 78 }),
  p("asos-glass-sequin-blue", "Glass sequins batwing sleeve mini dress with draped front bodice in blue", "ASOS DESIGN", "dresses", 109,
    "https://www.asos.com/us/asos-design/asos-design-glass-sequins-batwing-sleeve-mini-dress-with-draped-front-bodice-in-blue/prd/210074015",
    ["blue"], ["Aquarius", "Leo", "Pisces"], { glamour: 90, futuristic: 76, colourIntensity: 80, maximal: 78 }),
  p("asos-sheer-lace-teal", "Sheer lace cami mini dress with placement embellishment in teal", "ASOS DESIGN", "dresses", 149,
    "https://www.asos.com/us/asos-design/asos-design-sheer-lace-cami-mini-dress-with-placement-embellishment-in-teal/prd/210885435",
    ["teal"], ["Pisces", "Scorpio", "Libra"], { romantic: 84, texture: 86, glamour: 82, sensual: 78 }),
  p("arrange-disc-sequin-ice-blue", "Embellished disc sequin square neck full skirt midi dress in ice blue", "ARRANGE", "dresses", 379,
    "https://www.asos.com/us/arrange/arrange-curve-embellished-disc-sequin-square-neck-full-skirt-midi-dress-in-ice-blue/prd/209949395",
    ["ice blue"], ["Aquarius", "Pisces", "Leo"], { glamour: 94, maximal: 90, futuristic: 78 }),
  p("asos-paillette-olive-maxi", "Scattered paillette sequins scoop neck maxi dress in dark olive", "ASOS DESIGN", "dresses", 139,
    "https://www.asos.com/us/asos-design/asos-design-scattered-paillette-sequins-scoop-neck-maxi-dress-in-dark-olive/prd/210484681",
    ["olive"], ["Sagittarius", "Leo", "Aquarius"], { glamour: 86, maximal: 82, colourIntensity: 70 }),
  p("asos-luxe-feather-pink", "Embellished scoop neck mini dress with faux feather hem in pink", "ASOS LUXE", "dresses", 260,
    "https://www.asos.com/us/asos-luxe/asos-luxe-embellished-scoop-neck-mini-dress-with-faux-feather-hem-in-pink/prd/209081889",
    ["pink"], ["Leo", "Libra", "Pisces"], { glamour: 96, maximal: 92, romantic: 86, feminine: 90 }),
  p("asos-sequin-cami-green-maxi", "Embellished sheer scattered sequin cami maxi dress in green", "ASOS DESIGN", "dresses", 64.99,
    "https://www.asos.com/us/asos-design/asos-design-embellished-sheer-scattered-sequin-cami-maxi-dress-in-green/prd/210079772",
    ["green"], ["Sagittarius", "Leo", "Aquarius"], { glamour: 84, fluidity: 78, colourIntensity: 76 }),
  p("topshop-fallen-shoulder-white-tee", "Fallen shoulder T-shirt in white", "Topshop", "tops", 30,
    "https://www.asos.com/us/topshop/topshop-fallen-shoulder-t-shirt-in-white/prd/210538286",
    ["white"], ["Virgo", "Capricorn", "Aquarius"], { minimal: 88, casual: 84, structure: 60 }),
  p("collusion-unisex-white-tee", "Unisex white T-shirt", "COLLUSION", "tops", 12.99,
    "https://www.asos.com/us/collusion/collusion-unisex-white-t-shirt/prd/208940053",
    ["white"], ["Aquarius", "Capricorn", "Virgo"], { minimal: 92, masculine: 72, casual: 90 }),
  p("asos-satc-white-tee", "X Sex and the City licensed white t-shirt", "ASOS DESIGN", "tops", 44.99,
    "https://www.asos.com/us/asos-design/asos-design-x-sex-and-the-city-official-licensed-merch-white-t-shirt/prd/210547231",
    ["white"], ["Gemini", "Leo", "Libra"], { printIntensity: 76, casual: 84, vintage: 64 }),
  p("collusion-double-layer-white-tee", "Short sleeve double layer white T-shirt", "COLLUSION", "tops", 29.99,
    "https://www.asos.com/us/collusion/collusion-short-sleeve-double-layer-white-t-shirt/prd/210591006",
    ["white"], ["Aquarius", "Gemini", "Virgo"], { experimental: 72, casual: 86, minimal: 74 }),
  p("mango-white-tee", "Round neck white T-shirt", "Mango", "tops", 22.99,
    "https://www.asos.com/us/mango/mango-round-neck-white-t-shirt/prd/210491915",
    ["white"], ["Virgo", "Taurus", "Libra"], { minimal: 90, classic: 84, casual: 82 }),
  p("asos-wonder-woman-tee", "Short sleeve oversized T-shirt with Wonder Woman graphic in white", "ASOS DESIGN", "tops", 47.99,
    "https://www.asos.com/us/asos-design/asos-design-short-sleeve-oversized-t-shirt-with-wonder-woman-graphic-in-white/prd/210550178",
    ["white"], ["Leo", "Gemini", "Aries"], { printIntensity: 84, casual: 84, oversized: 76 }),
  p("topshop-funnel-denim-mid-blue", "Funnel neck elastic hem detail jacket in mid blue", "Topshop", "outerwear", 119,
    "https://www.asos.com/us/topshop/topshop-funnel-neck-elastic-hem-detail-jacket-mid-blue/prd/210300419",
    ["mid blue"], ["Aquarius", "Gemini", "Sagittarius"], { experimental: 76, casual: 80, structure: 70 }),
  p("topshop-denim-bomber-zebra", "Padded denim bomber jacket in zebra", "Topshop", "outerwear", 129,
    "https://www.asos.com/us/topshop/topshop-padded-denim-bomber-jacket-in-zebra/prd/211273866",
    ["zebra", "black"], ["Leo", "Gemini", "Sagittarius"], { printIntensity: 92, maximal: 82, edge: 68 }, ["busy_print"]),
  p("topshop-denim-bubble-bleach", "Denim funnel neck bubble hem top in bleach", "Topshop", "tops", 95,
    "https://www.asos.com/us/topshop/topshop-denim-funnel-neck-bubble-hem-top-in-bleach/prd/210577129",
    ["bleach"], ["Aquarius", "Gemini", "Pisces"], { experimental: 84, casual: 76, oversized: 70 }),
  p("asos-funnel-bubble-mid-blue", "Funnel neck bubble hem jacket in mid blue", "ASOS DESIGN", "outerwear", 84.99,
    "https://www.asos.com/us/asos-design/asos-design-funnel-neck-bubble-hem-jacket-in-mid-blue-part-of-a-set/prd/210598738",
    ["mid blue"], ["Aquarius", "Pisces", "Gemini"], { experimental: 78, fluidity: 70, casual: 76 }),
  p("topshop-funnel-bleached-denim", "Funnel neck elasticized hem detail jacket in bleached denim", "Topshop", "outerwear", 119,
    "https://www.asos.com/us/topshop/topshop-funnel-neck-elasticized-hem-detail-jacket-in-bleached-denim/prd/210922045",
    ["bleached denim"], ["Aquarius", "Sagittarius", "Gemini"], { experimental: 76, casual: 80 }),
  p("lioness-bronx-denim-dark", "The Bronx structured rolled cuffs denim jacket in dark blue wash", "Lioness", "outerwear", 130,
    "https://www.asos.com/us/lioness/lioness-the-bronx-structured-rolled-cuffs-denim-jacket-in-dark-blue-wash/prd/211038908",
    ["dark blue"], ["Capricorn", "Scorpio", "Aries"], { structure: 82, classic: 76, edge: 68 }),
  p("asos-utility-khaki-volume", "Volume laundered utility pants in khaki", "ASOS DESIGN", "bottoms", 47.99,
    "https://www.asos.com/us/asos-design/asos-design-volume-laundered-utility-pants-in-khaki/prd/211267948",
    ["khaki"], ["Sagittarius", "Aquarius", "Virgo"], { casual: 86, oversized: 80, structure: 60 }),
  p("asos-cargo-turnup-black", "Casual turn up cuff cargo pants in black", "ASOS DESIGN", "bottoms", 69.99,
    "https://www.asos.com/us/asos-design/asos-design-casual-turn-up-cuff-cargo-pants-in-black/prd/210777109",
    ["black"], ["Aries", "Aquarius", "Scorpio"], { sporty: 78, edge: 72, casual: 84 }),
  p("asos-cargo-knee-mocha", "Cargo pants with knee seams in mocha", "ASOS DESIGN", "bottoms", 69.99,
    "https://www.asos.com/us/asos-design/asos-design-cargo-pants-with-knee-seams-in-mocha/prd/210431324",
    ["mocha"], ["Virgo", "Taurus", "Sagittarius"], { casual: 80, structure: 68, texture: 62 }),
  p("asos-cargo-soft-khaki", "Cargo pants in soft khaki", "ASOS DESIGN", "bottoms", 74.99,
    "https://www.asos.com/us/asos-design/asos-design-cargo-pants-in-soft-khaki/prd/210445612",
    ["khaki"], ["Sagittarius", "Virgo", "Aquarius"], { casual: 84, oversized: 68 })
);

PRODUCTS.push(
  p("collusion-baggy-cargo-khaki", "Utility pocket baggy cargo pants in khaki", "COLLUSION", "bottoms", 69.99,
    "https://www.asos.com/us/collusion/collusion-utility-pocket-baggy-cargo-pants-in-khaki/prd/211081910",
    ["khaki"], ["Aquarius", "Sagittarius", "Gemini"], { oversized: 86, casual: 88, edge: 64 }),
  p("asos-parachute-cargo-chocolate", "Parachute cargo pants in chocolate", "ASOS DESIGN", "bottoms", 59.99,
    "https://www.asos.com/us/asos-design/asos-design-parachute-cargo-pants-in-chocolate/prd/210623350",
    ["chocolate"], ["Aquarius", "Sagittarius", "Taurus"], { experimental: 76, oversized: 82, casual: 82 }),
  p("asos-culotte-chocolate", "Wide leg culotte pants in chocolate", "ASOS DESIGN", "bottoms", 49.99,
    "https://www.asos.com/us/asos-design/asos-design-wide-leg-culotte-pants-in-chocolate/prd/210475545",
    ["chocolate"], ["Virgo", "Taurus", "Libra"], { polished: 80, minimal: 76, classic: 74 }),
  p("asos-curve-twill-wide-chocolate", "Cotton twill wide leg pants in chocolate", "ASOS DESIGN", "bottoms", 59.99,
    "https://www.asos.com/us/asos-curve/asos-design-curve-cotton-twill-wide-leg-pants-in-chocolate/prd/210005274",
    ["chocolate"], ["Taurus", "Virgo", "Capricorn"], { classic: 80, texture: 70, structure: 72 }),
  p("asos-linen-pleat-navy", "Wide leg pants with pleat detail in linen blend in navy", "ASOS DESIGN", "bottoms", 49,
    "https://www.asos.com/us/asos-tall/asos-design-tall-wide-leg-pants-with-pleat-detail-in-linen-blend-in-navy/prd/209846640",
    ["navy"], ["Virgo", "Libra", "Capricorn"], { polished: 82, classic: 80, minimal: 78 }),
  p("asos-linen-pullon-black", "Linen look pull on pants in black", "ASOS DESIGN", "bottoms", 44,
    "https://www.asos.com/us/asos-tall/asos-design-tall-linen-look-pull-on-pants-in-black/prd/209848868",
    ["black"], ["Virgo", "Capricorn", "Aquarius"], { minimal: 86, casual: 72, colourIntensity: 10 }),
  p("asos-linen-wide-cream", "Linen blend wide leg pants with pleated detailing in cream", "ASOS DESIGN", "bottoms", 47.99,
    "https://www.asos.com/us/asos-design/asos-design-linen-blend-wide-leg-pants-with-pleated-detailing-in-cream/prd/209846937",
    ["cream"], ["Libra", "Taurus", "Virgo"], { polished: 80, fluidity: 72, texture: 74 }),
  p("asos-linen-natural", "Wide leg linen blend pants with pleated detailing in natural", "ASOS DESIGN", "bottoms", 49,
    "https://www.asos.com/us/asos-tall/asos-design-tall-wide-leg-linen-blend-pants-with-pleated-detailing-in-natural/prd/209846529",
    ["natural"], ["Taurus", "Virgo", "Cancer"], { texture: 76, classic: 78, casual: 66 }),
  p("hollister-graphic-hoodie-cream", "Back graphic zip up hoodie in cream", "Hollister", "tops", 59.95,
    "https://www.asos.com/us/hollister/hollister-back-graphic-zip-up-hoodie-in-cream/prd/211152970",
    ["cream"], ["Cancer", "Gemini", "Taurus"], { casual: 90, texture: 72, sporty: 66 }),
  p("weekday-oversized-hoodie-blue", "Oversized hoodie with embroidery detail in dark blue", "Weekday", "tops", 104,
    "https://www.asos.com/us/weekday/weekday-oversized-hoodie-with-embroidery-detail-in-dark-blue/prd/211310098",
    ["dark blue"], ["Aquarius", "Capricorn", "Sagittarius"], { oversized: 88, casual: 88, minimal: 72 }),
  p("jordan-cropped-hoodie-camo", "Jordan cropped hoodie in camo print", "Nike", "tops", 80,
    "https://www.asos.com/us/jordan/nike-jordan-cropped-hoodie-in-camo-print/prd/210260462",
    ["camo"], ["Aries", "Aquarius", "Sagittarius"], { sporty: 90, printIntensity: 78, edge: 72 }),
  p("kaiia-zip-hoodie-gray", "Cotton rich cinched waistband drop shoulder zip through hoodie in light gray", "Kaiia", "tops", 56,
    "https://www.asos.com/us/kaiia/kaiia-cotton-rich-cinched-waistband-drop-shoulder-zip-through-hoodie-in-light-gray/prd/210736356",
    ["light gray"], ["Cancer", "Virgo", "Taurus"], { casual: 88, minimal: 74, sporty: 62 }),
  p("collusion-washed-hoodie-yellow", "Oversized washed hoodie in yellow", "COLLUSION", "tops", 49.99,
    "https://www.asos.com/us/collusion/collusion-oversized-washed-hoodie-in-yellow/prd/209486033",
    ["yellow"], ["Gemini", "Leo", "Sagittarius"], { colourIntensity: 84, casual: 90, oversized: 82 }),
  p("asos-reign-platform-burgundy", "Reign square toe mid-heel platform boots in burgundy", "ASOS DESIGN", "shoes", 74.99,
    "https://www.asos.com/us/asos-design/asos-design-reign-square-toe-mid-heel-platform-boots-in-burgundy/prd/208592524",
    ["burgundy"], ["Scorpio", "Taurus", "Leo"], { edge: 76, structure: 78, colourIntensity: 55 }),
  p("asos-reign-platform-black", "Reign square toe mid-heel platform boots in black", "ASOS DESIGN", "shoes", 74.99,
    "https://www.asos.com/us/asos-design/asos-design-reign-square-toe-mid-heel-platform-boots-in-black/prd/208592548",
    ["black"], ["Scorpio", "Aquarius", "Capricorn"], { edge: 80, structure: 80, colourIntensity: 10 }),
  p("asos-evelyn-platform-black", "Evelyn platform heeled ankle boots in black", "ASOS DESIGN", "shoes", 79.99,
    "https://www.asos.com/us/asos-design/asos-design-evelyn-platform-heeled-ankle-boots-in-black/prd/208592895",
    ["black"], ["Aquarius", "Scorpio", "Aries"], { edge: 84, structure: 78, futuristic: 66 }),
  p("asos-evelyn-platform-tan", "Evelyn platform heeled ankle boots in tan", "ASOS DESIGN", "shoes", 79.99,
    "https://www.asos.com/us/asos-design/asos-design-evelyn-platform-heeled-ankle-boots-in-tan/prd/208592768",
    ["tan"], ["Sagittarius", "Taurus", "Virgo"], { texture: 74, casual: 72, structure: 70 }),
  p("asos-reign-platform-mocha", "Reign square toe mid-heel platform boots in mocha suedette", "ASOS DESIGN", "shoes", 74.99,
    "https://www.asos.com/us/asos-design/asos-design-reign-square-toe-mid-heel-platform-boots-in-mocha-suedette/prd/208592493",
    ["mocha"], ["Taurus", "Virgo", "Sagittarius"], { texture: 80, casual: 68, structure: 72 }),
  p("asos-lion-bow-flats-black", "Lion bow ballet flats in black", "ASOS DESIGN", "shoes", 22.99,
    "https://www.asos.com/us/asos-design/asos-design-lion-bow-ballet-flats-in-black/prd/209828058",
    ["black"], ["Libra", "Cancer", "Virgo"], { romantic: 80, feminine: 86, polished: 76 }),
  p("asos-widefit-bow-flats-black", "Lion bow trim ballet flats in black", "ASOS DESIGN", "shoes", 25,
    "https://www.asos.com/us/asos-design/asos-design-wide-fit-lion-bow-trim-ballet-flats-in-black/prd/209828133",
    ["black"], ["Libra", "Cancer", "Pisces"], { romantic: 78, feminine: 84, polished: 74 }),
  p("mango-classic-flats-black", "Classic ballet flats in black", "Mango", "shoes", 89.99,
    "https://www.asos.com/us/mango/mango-classic-ballet-flats-in-black/prd/211411631",
    ["black"], ["Virgo", "Capricorn", "Libra"], { classic: 90, minimal: 86, polished: 88 }),
  p("asos-lillie-maryjane-borg", "Lillie mary jane ballet flats in natural borg", "ASOS DESIGN", "shoes", 44.99,
    "https://www.asos.com/us/asos-design/asos-design-lillie-mary-jane-ballet-flats-in-natural-borg/prd/210779212",
    ["natural"], ["Cancer", "Pisces", "Taurus"], { texture: 88, romantic: 76, casual: 74 }),
  p("topshop-bella-leather-flats", "Bella leather round toe ballet flats in black", "Topshop", "shoes", 77,
    "https://www.asos.com/us/topshop/topshop-bella-leather-round-toe-ballet-flats-in-black/prd/210605683",
    ["black"], ["Virgo", "Capricorn", "Taurus"], { classic: 86, minimal: 82, texture: 72 }),
  p("topshop-dorothy-satin-flats", "Dorothy round toe ballet flats in black satin", "Topshop", "shoes", 48,
    "https://www.asos.com/us/topshop/topshop-dorothy-round-toe-ballet-flats-in-black-satin/prd/210605867",
    ["black"], ["Libra", "Pisces", "Cancer"], { romantic: 80, texture: 82, feminine: 82 }),
  p("asos-lariat-teardrop-silver", "Long lariat necklace with teardrop pendant in silver tone", "ASOS DESIGN", "jewellery", 19.99,
    "https://www.asos.com/us/asos-design/asos-design-long-lariat-necklace-with-teardrop-pendant-in-silver-tone/prd/209759019",
    ["silver"], ["Pisces", "Aquarius", "Scorpio"], { minimal: 78, futuristic: 64, romantic: 62 }),
  p("asos-western-bolo-silver", "Western bolo necklace in silver", "ASOS DESIGN", "jewellery", 22.99,
    "https://www.asos.com/us/asos-design/asos-design-western-bolo-necklace-in-silver/prd/210393739",
    ["silver"], ["Sagittarius", "Aquarius", "Aries"], { experimental: 78, vintage: 72, edge: 68 }),
  p("topshop-mason-choker-silver", "Mason statement choker necklace in silver", "Topshop", "jewellery", 39,
    "https://www.asos.com/us/topshop/topshop-mason-statement-choker-necklace-in-silver/prd/210934786",
    ["silver"], ["Scorpio", "Aquarius", "Aries"], { edge: 86, maximal: 74, futuristic: 72 }),
  p("reclaimed-mixed-metal-chain", "Mixed metal chunky neck chain in gold and silver tone", "Reclaimed Vintage", "jewellery", 27.99,
    "https://www.asos.com/us/reclaimed-vintage/reclaimed-vintage-mixed-metal-chunky-neck-chain-in-gold-tone-and-silver-tone/prd/211283724",
    ["gold", "silver"], ["Gemini", "Aquarius", "Sagittarius"], { experimental: 80, maximal: 72, vintage: 66 }),
  p("pieces-two-chain-silver", "Two chain necklace in silver", "Pieces", "jewellery", 22,
    "https://www.asos.com/us/pieces/pieces-two-chain-necklace-in-silver/prd/207423611",
    ["silver"], ["Aquarius", "Virgo", "Capricorn"], { minimal: 84, futuristic: 62, classic: 70 }),
  p("topshop-matilda-teardrop-silver", "Matilda teardrop pendant necklace in silver", "Topshop", "jewellery", 23,
    "https://www.asos.com/us/topshop/topshop-matilda-teardrop-pendant-necklace-in-silver/prd/210838564",
    ["silver"], ["Pisces", "Cancer", "Libra"], { romantic: 78, minimal: 74, feminine: 78 }),
  p("kaiia-studded-tote-brown", "Silver hardware studded faux leather tote bag in brown", "Kaiia", "bags", 56,
    "https://www.asos.com/us/kaiia/kaiia-exclusive-silver-hardware-studded-faux-leather-tote-bag-in-brown/prd/210899088",
    ["brown"], ["Sagittarius", "Scorpio", "Taurus"], { texture: 80, edge: 70, casual: 72 }),
  p("dragon-diffusion-woven-tan", "Japan woven tote bag in tan", "Dragon Diffusion", "bags", 716,
    "https://www.asos.com/us/dragon-diffusion/dragon-diffusion-japan-woven-tote-bag-in-tan/prd/210025141",
    ["tan"], ["Taurus", "Libra", "Virgo"], { texture: 94, classic: 90, polished: 88 }),
  p("glamorous-woven-tote-burgundy", "Large woven shoulder tote bag in deep burgundy", "Glamorous", "bags", 52,
    "https://www.asos.com/us/glamorous/glamorous-large-woven-shoulder-tote-bag-in-deep-burgundy/prd/208640365",
    ["burgundy"], ["Taurus", "Sagittarius", "Scorpio"], { texture: 84, casual: 74, colourIntensity: 50 }),
  p("asos-canvas-tote-leopard", "Tubular handle canvas tote bag in brown leopard", "ASOS DESIGN", "bags", 27.99,
    "https://www.asos.com/us/asos-design/asos-design-tubular-handle-canvas-tote-bag-in-brown-leopard/prd/207052909",
    ["leopard", "brown"], ["Leo", "Gemini", "Sagittarius"], { printIntensity: 90, casual: 82 }, ["busy_print"]),
  p("asos-bonded-tote-blue", "Oversized bonded tote in blue", "ASOS DESIGN", "bags", 47.99,
    "https://www.asos.com/us/asos-design/asos-design-oversized-bonded-tote-in-blue/prd/210972852",
    ["blue"], ["Aquarius", "Gemini", "Capricorn"], { minimal: 76, oversized: 82, futuristic: 62 }),
  p("glamorous-suede-tote-khaki", "Slouchy faux suede shoulder tote bag with metal buckle in khaki green", "Glamorous", "bags", 56,
    "https://www.asos.com/us/glamorous/glamorous-slouchy-faux-suede-shoulder-tote-bag-with-metal-buckle-in-khaki-green/prd/209451791",
    ["khaki"], ["Sagittarius", "Taurus", "Cancer"], { texture: 86, casual: 80, oversized: 74 }),
  p("asos-luxe-velvet-sequin-cream", "Velvet sequined maxi dress with draped waist in cream", "ASOS LUXE", "dresses", 209,
    "https://www.asos.com/us/asos-luxe/asos-luxe-velvet-sequined-maxi-dress-with-draped-waist-in-cream/prd/209482957",
    ["cream"], ["Leo", "Libra", "Pisces"], { glamour: 94, texture: 92, maximal: 86, fluidity: 78 }),
  p("arrange-velvet-halter-chocolate", "Velvet plunge halter cinch waist maxi dress with train in chocolate", "ARRANGE", "dresses", 309,
    "https://www.asos.com/us/arrange/arrange-velvet-plunge-halter-cinch-waist-maxi-dress-with-train-in-chocolate/prd/208967950",
    ["chocolate"], ["Scorpio", "Taurus", "Leo"], { sensual: 92, texture: 94, glamour: 90, bodyConscious: 80 }),
  p("asos-luxe-velvet-bow-white", "White mini dress with velvet bow detail", "ASOS LUXE", "dresses", 189,
    "https://www.asos.com/us/asos-luxe/asos-luxe-white-mini-dress-with-velvet-bow-detail/prd/209814288",
    ["white"], ["Libra", "Cancer", "Leo"], { romantic: 90, polished: 86, glamour: 82, feminine: 90 }),
  p("princess-polly-velvet-pearl-black", "Fellaire velvet open pearl detail back mini dress in black", "Princess Polly", "dresses", 75,
    "https://www.asos.com/us/princess-polly/princess-polly-fellaire-velvet-open-pearl-detail-back-mini-dress-in-black/prd/208999243",
    ["black"], ["Scorpio", "Cancer", "Pisces"], { sensual: 86, texture: 88, romantic: 78 }),
  p("asos-luxe-velvet-sequin-chocolate", "Velvet sequin drape side mini dress in chocolate", "ASOS LUXE", "dresses", 189,
    "https://www.asos.com/us/asos-luxe/asos-luxe-velvet-sequin-drape-side-mini-dress-in-chocolate/prd/208824571",
    ["chocolate"], ["Taurus", "Scorpio", "Leo"], { texture: 92, glamour: 88, sensual: 82 })
);
