/**
 * Money Blueprint engine validation sweep.
 *
 * Runs the shared covering set from __tests__/support/charts.ts through the engine and writes
 * money-blueprint/engine/test/RESULTS.md.
 *
 * Not a pass/fail unit test. It is the instrument for tuning the weights.
 */

import fs from "fs";
import path from "path";
import type { EvidenceItem } from "@/lib/money-blueprint/evidence";
import { analyse, type Profile } from "@/lib/money-blueprint/analyse";
import { buildSweep, NEED, type Sample } from "./support/charts";

jest.setTimeout(900_000);

describe("money blueprint engine sweep", () => {
  it("runs the covering set and writes RESULTS.md", () => {
    const { pop, freq, chosen, covered } = buildSweep();

    // ---------------------------------------------------------------- 4. run
    const profiles: Array<{ s: Sample; p: Profile }> = chosen.map((s) => ({
      s,
      p: analyse(s.bd.name, s.chart, s.hd, freq),
    }));

    // ---------------------------------------------------------------- 5. aggregate
    const shadowThemeCounts = new Map<string, number>();
    const topThemeCounts = new Map<string, number>();
    const confCounts = new Map<string, number>();
    let hdShareSum = 0;
    let openCentreShadowClusters = 0;
    let totalShadowClusters = 0;

    // shadow-composition instrumentation
    let seedHD = 0, seedAstro = 0, clusterHasHD = 0, clusterCentreSupport = 0, clusterCentreSeed = 0;
    let seedChannel = 0, seedCircuit = 0, clusterDesignSide = 0;
    const confAll = new Map<string, number>();
    let indepSum = 0, indepN = 0;
    const centreLedCandidates: string[] = [];

    for (const { s, p } of profiles) {
      hdShareSum += p.hdShare;
      if (p.themes[0]) topThemeCounts.set(p.themes[0].theme, (topThemeCounts.get(p.themes[0].theme) ?? 0) + 1);
      for (const sh of p.shadows) {
        shadowThemeCounts.set(sh.theme, (shadowThemeCounts.get(sh.theme) ?? 0) + 1);
        totalShadowClusters++;
        const seed = sh.cluster[0];
        if (seed.system === "human-design") seedHD++; else seedAstro++;
        if (seed.id.startsWith("hd:channel:")) seedChannel++;
        if (seed.id.startsWith("hd:circuit:")) seedCircuit++;
        if (seed.id.startsWith("hd:centre:")) clusterCentreSeed++;
        if (sh.cluster.some((i: EvidenceItem) => i.system === "human-design")) clusterHasHD++;
        if (sh.cluster.slice(1).some((i: EvidenceItem) => i.id.startsWith("hd:centre:"))) clusterCentreSupport++;
        if (sh.cluster.some((i: EvidenceItem) => i.id.startsWith("hd:centre:"))) openCentreShadowClusters++;
        if (sh.side === "design") clusterDesignSide++;
      }
      // would any chart legitimately have a centre-led shadow? a centre is the single strongest
      // carrier of one of its top-3 themes
      for (const t of p.themes.slice(0, 3)) {
        const w = (i: EvidenceItem) => (i.themes.find(([th]: [string, number]) => th === t.theme)?.[1] ?? 0) * i.adjustedStrength;
        const best = [...t.items].sort((a, b) => w(b) - w(a))[0];
        if (best?.id.startsWith("hd:centre:")) centreLedCandidates.push(`${s.bd.name}:${t.theme}:${best.id}`);
      }
      for (const t of p.themes) {
        confAll.set(t.confidence, (confAll.get(t.confidence) ?? 0) + 1);
        indepSum += t.independence; indepN++;
      }
      for (const t of p.themes.slice(0, 5)) confCounts.set(t.confidence, (confCounts.get(t.confidence) ?? 0) + 1);
    }

    // ---------------------------------------------------------------- 6. write
    const L: string[] = [];
    const P = (s = "") => L.push(s);

    P("# Engine validation sweep — results");
    P();
    P(`Generated by \`__tests__/money-blueprint-engine.test.ts\`. Population ${pop.length} charts, covering set ${profiles.length}.`);
    P(`Weights per \`engine/HD-ENGINE.md\`, evidence rules per \`engine/EVIDENCE-ENGINE.md\`.`);
    P();
    P("## Coverage");
    P();
    P("| Target | Covered |");
    P("|---|---|");
    for (const n of NEED) P(`| \`${n}\` | ${covered.has(n) ? "yes" : "**NO**"} |`);
    P();

    P("## Population frequencies (rarity inputs)");
    P();
    P("Measured across the sampled population. Lower is rarer, therefore more diagnostic.");
    P();
    P("| Configuration | Frequency |");
    P("|---|---|");
    const interesting = Object.entries(freq)
      .filter(([k]) => /^(open|defined|type|channel|circuit):/.test(k))
      .sort((a, b) => b[1] - a[1]);
    for (const [k, v] of interesting.slice(0, 14)) P(`| \`${k}\` | ${(v * 100).toFixed(0)}% |`);
    P("| ... | ... |");
    for (const [k, v] of interesting.slice(-8)) P(`| \`${k}\` | ${(v * 100).toFixed(0)}% |`);
    P();

    P("## Per-chart results");
    P();
    for (const { s, p } of profiles) {
      const hd = s.hd;
      P(`### ${s.bd.name}`);
      P();
      P(`${hd.type} · ${hd.authorityLabel} · ${hd.profile} · ${hd.definition} · open [${hd.openCenters.join(", ") || "none"}] · ${hd.definedChannels.length} channels · ${(s.chart.aspects ?? []).length} aspects · circuit ${p.dominantCircuit ?? "none"}`);
      P();
      P("| Theme | Score | Indep | Cross-system | Confidence |");
      P("|---|---|---|---|---|");
      for (const t of p.themes.slice(0, 5)) {
        P(`| ${t.theme} | ${t.score.toFixed(1)} | ${t.independence} | ${t.crossSystem ? "yes" : "no"} | ${t.confidence} |`);
      }
      P();
      P(`**Shadows (${p.shadows.length}):**`);
      for (const sh of p.shadows) {
        P(`- \`${sh.theme}\` / ${sh.side} — ${sh.cluster.map((c) => c.id).join(" + ")}`);
      }
      if (p.shadows.length === 0) P("- none");
      P();
      P(`Astrology ${(p.astroShare * 100).toFixed(0)}% / Human Design ${(p.hdShare * 100).toFixed(0)}% of top-3 evidence. Contradictions: ${p.contradictions.map((c) => `${c.a}/${c.b}`).join(", ") || "none"}.`);
      P();
    }

    P("## Aggregate");
    P();
    P("### Shadow theme distribution");
    P();
    P("| Theme | Times selected | Share |");
    P("|---|---|---|");
    for (const [t, c] of [...shadowThemeCounts].sort((a, b) => b[1] - a[1])) {
      P(`| ${t} | ${c} | ${((c / totalShadowClusters) * 100).toFixed(0)}% |`);
    }
    P();
    P("### Top theme distribution");
    P();
    for (const [t, c] of [...topThemeCounts].sort((a, b) => b[1] - a[1])) P(`- ${t}: ${c}`);
    P();
    P("### Confidence distribution (top 5 themes per chart)");
    P();
    for (const [c, n] of [...confCounts].sort((a, b) => b[1] - a[1])) P(`- ${c}: ${n}`);
    P();
    P("### Confidence distribution (ALL themes, every chart)");
    P();
    P("| Tier | Count | Share |");
    P("|---|---|---|");
    const confTotal = [...confAll.values()].reduce((a: number, b: number) => a + b, 0);
    for (const tier of ["very-high", "high", "moderate", "low", "insufficient"]) {
      const n = confAll.get(tier) ?? 0;
      P(`| ${tier} | ${n} | ${((n / confTotal) * 100).toFixed(1)}% |`);
    }
    P();
    P(`Mean independence per theme: **${(indepSum / indepN).toFixed(1)}**`);
    P();
    const iv = profiles.flatMap((x) => x.p.themes.map((t) => t.independence)).sort((a: number, b: number) => a - b);
    const pct = (q: number) => iv[Math.floor(iv.length * q)];
    P(`Independence percentiles: p50 ${pct(0.5)} · p75 ${pct(0.75)} · p85 ${pct(0.85)} · p90 ${pct(0.9)} · p95 ${pct(0.95)} · max ${iv[iv.length - 1]}`);
    P();
    P("### Shadow composition");
    P();
    const pc = (n: number) => `${((n / totalShadowClusters) * 100).toFixed(0)}%`;
    P("| Measure | Count | Share of shadows |");
    P("|---|---|---|");
    P(`| Seeded by Human Design | ${seedHD} | ${pc(seedHD)} |`);
    P(`| Seeded by astrology | ${seedAstro} | ${pc(seedAstro)} |`);
    P(`| Cluster contains any HD evidence | ${clusterHasHD} | ${pc(clusterHasHD)} |`);
    P(`| Seeded by a defined channel | ${seedChannel} | ${pc(seedChannel)} |`);
    P(`| Seeded by circuitry | ${seedCircuit} | ${pc(seedCircuit)} |`);
    P(`| Centre as SEED (primary evidence) | ${clusterCentreSeed} | ${pc(clusterCentreSeed)} |`);
    P(`| Centre as SUPPORT (not seed) | ${clusterCentreSupport} | ${pc(clusterCentreSupport)} |`);
    P(`| Cluster resolves to Design side | ${clusterDesignSide} | ${pc(clusterDesignSide)} |`);
    P();
    P(`Charts where a centre is the strongest carrier of a top-3 theme (i.e. arguably *should* seed): **${centreLedCandidates.length}**`);
    for (const c of centreLedCandidates.slice(0, 12)) P(`- \`${c}\``);
    P();
    P(`### Headline numbers`);
    P();
    P(`- Mean Human Design share of top-3 evidence: **${((hdShareSum / profiles.length) * 100).toFixed(0)}%**`);
    P(`- Shadow clusters containing an open or defined centre: **${((openCentreShadowClusters / totalShadowClusters) * 100).toFixed(0)}%**`);
    P(`- Charts producing fewer than 3 shadows: **${profiles.filter((x) => x.p.shadows.length < 3).length} of ${profiles.length}**`);
    const shadowCounts = [3, 4, 5].map((n) => `${n}: ${profiles.filter((x) => x.p.shadows.length === n).length}`);
    P(`- Shadow count distribution: **${shadowCounts.join(" · ")}**`);
    P(`- Single-item shadow clusters: **${profiles.reduce((a, x) => a + x.p.shadows.filter((s) => s.cluster.length < 2).length, 0)}**`);
    P(`- Distinct shadow themes used across the set: **${shadowThemeCounts.size} of 14**`);

    const out = path.join(__dirname, "../../money-blueprint/engine/test");
    fs.mkdirSync(out, { recursive: true });
    fs.writeFileSync(path.join(out, "RESULTS.md"), L.join("\n"));

    expect(profiles.length).toBeGreaterThan(20);
  });
});
